// Code generated by raorm. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/raorm/runtime"

	authzrquery "github.com/gsoultan/anubis/internal/authz/adapter/postgres/rquery"
	"github.com/gsoultan/raorm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"roles": 0,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
func init() {
	raorm.RegisterScanner(scanAuthorizeRow)
	raorm.RegisterScanner(scanRoleNameRow)
	raorm.RegisterScanner(scanCreatedRoleRow)
}

func scanAuthorizeRow(rv [][]byte, r *authzrquery.AuthorizeRow, sl *runtime.Slab) error {
	r.Allow = runtime.Bool(rv[0])
	return nil
}

func scanRoleNameRow(rv [][]byte, r *authzrquery.RoleNameRow, sl *runtime.Slab) error {
	r.Name = sl.Str(rv[0])
	return nil
}

func scanCreatedRoleRow(rv [][]byte, r *authzrquery.CreatedRoleRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}
