// Code generated by storm v0.10.0. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/storm/runtime"

	authzrquery "github.com/gsoultan/anubis/internal/authz/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"roles": 0,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanAuthorizeRow)
	storm.RegisterScanner(scanExplainRow)
	storm.RegisterScanner(scanPermissionMetaRow)
	storm.RegisterScanner(scanRoleNameRow)
	storm.RegisterScanner(scanPermissionKeyRow)
	storm.RegisterScanner(scanStrictSimRow)
	storm.RegisterScanner(scanDecisionDetailRow)
	storm.RegisterScanner(scanRoleRow)
	storm.RegisterScanner(scanCreatedRoleRow)
	storm.RegisterScanner(scanParentRow)
	storm.RegisterScanner(scanPatternRow)
	storm.RegisterScanner(scanDoneRow)
	storm.RegisterScanner(scanRoleIDRow)
	storm.RegisterScanner(scanEffectiveRow)
	storm.RegisterScanner(scanGrantRow)
	storm.RegisterScanner(scanGrantScopeRow)
	storm.RegisterScanner(scanCreatedGrantRow)
	storm.RegisterScanner(scanRevokedGrantRow)
	storm.RegisterScanner(scanSearchGrantRow)
	storm.RegisterScanner(scanCountRow)
	storm.RegisterScanner(scanMembershipListRow)
	storm.RegisterScanner(scanMembershipRow)
	storm.RegisterScanner(scanCreatedMembershipRow)
	storm.RegisterScanner(scanEntryRow)
	storm.RegisterScanner(scanEntryScopeRow)
	storm.RegisterScanner(scanInsertedEntryRow)
	storm.RegisterScanner(scanAssignRow)
	storm.RegisterScanner(scanUnassignRow)
	storm.RegisterScanner(scanResyncRow)
	storm.RegisterScanner(scanPermissionRow)
	storm.RegisterScanner(scanUpsertedPermissionRow)
	storm.RegisterScanner(scanDeprecatedKeyRow)
	storm.RegisterScanner(scanPermissionIDRow)
	storm.RegisterStatement(`
DELETE FROM membership_entries WHERE membership_id = $1`)
	storm.RegisterStatement(`
DELETE FROM role_parents WHERE role_id = $1`)
	storm.RegisterStatement(`
DELETE FROM role_permission_patterns WHERE role_id = $1`)
	storm.RegisterStatement(`
DELETE FROM role_permissions WHERE role_id = $1`)
	storm.RegisterStatement(`
INSERT INTO grant_scopes (grant_id, tenant_id, axis_code, scope_node_id, inherit)
VALUES ($1, $2, $3, $4, $5)`)
	storm.RegisterStatement(`
INSERT INTO grants (tenant_id, identity_id, role_id, granted_by, reason,
                    self_scoped, valid_until)
VALUES ($1, $2, $3, $4, nullif($5, ''), $6, $7)
RETURNING id::text AS id, valid_from`)
	storm.RegisterStatement(`
INSERT INTO membership_entries (membership_id, tenant_id, role_id)
VALUES ($1, $2, $3)
RETURNING id::text AS id`)
	storm.RegisterStatement(`
INSERT INTO membership_entry_scopes (entry_id, tenant_id, axis_code,
                                     scope_node_id, inherit)
VALUES ($1, $2, $3, $4, $5)`)
	storm.RegisterStatement(`
INSERT INTO memberships (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id::text AS id`)
	storm.RegisterStatement(`
INSERT INTO permissions (application_id, tenant_id, app_slug, resource, action,
                         description, risk, min_assurance, requires_amr, max_auth_age)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::text[], nullif($10, '')::interval)
ON CONFLICT (application_id, resource, action) DO UPDATE
    SET description = EXCLUDED.description,
        risk = EXCLUDED.risk,
        min_assurance = EXCLUDED.min_assurance,
        requires_amr = EXCLUDED.requires_amr,
        max_auth_age = EXCLUDED.max_auth_age,
        deprecated_at = NULL
RETURNING id::text AS id, key, (xmax = 0) AS inserted`)
	storm.RegisterStatement(`
INSERT INTO role_parents (role_id, parent_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING`)
	storm.RegisterStatement(`
INSERT INTO role_permission_patterns (role_id, pattern)
VALUES ($1, $2)
ON CONFLICT DO NOTHING`)
	storm.RegisterStatement(`
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING`)
	storm.RegisterStatement(`
INSERT INTO roles (tenant_id, name, description, application_id, is_system,
                   allowed_realm_kinds, assignable_at)
VALUES ($1, $2, $3, $4, $5, $6::text[], $7::text[])
RETURNING id::text AS id`)
	storm.RegisterStatement(`
SELECT (role_recompute_effective($1) IS NULL) AS done`)
	storm.RegisterStatement(`
SELECT DISTINCT p.key
FROM grants g
JOIN role_permissions_effective rpe ON rpe.role_id = g.role_id
JOIN permissions p ON p.id = rpe.permission_id
WHERE g.identity_id = $1 AND g.tenant_id = $2
  AND g.revoked_at IS NULL AND g.valid_from <= now()
  AND (g.valid_until IS NULL OR g.valid_until > now())
  AND p.deprecated_at IS NULL
ORDER BY p.key`)
	storm.RegisterStatement(`
SELECT DISTINCT r.name
FROM grants g
JOIN roles r ON r.id = g.role_id
WHERE g.identity_id = $1 AND g.tenant_id = $2
  AND g.revoked_at IS NULL AND g.valid_from <= now()
  AND (g.valid_until IS NULL OR g.valid_until > now())
ORDER BY r.name`)
	storm.RegisterStatement(`
SELECT DISTINCT rp.role_id::text AS role_id
FROM role_permission_patterns rp
JOIN roles r ON r.id = rp.role_id
WHERE r.tenant_id = $1`)
	storm.RegisterStatement(`
SELECT authorize($1, $2, $3, $4::jsonb) AS allow`)
	storm.RegisterStatement(`
SELECT authorize_explain($1, $2, $3, $4::jsonb)::text AS detail`)
	storm.RegisterStatement(`
SELECT count(*) AS count FROM grants
WHERE tenant_id = $1 AND revoked_at IS NULL
  AND (valid_until IS NULL OR valid_until > now())`)
	storm.RegisterStatement(`
SELECT detail
FROM audit_log
WHERE tenant_id = $1
  AND action = 'authorize' AND result = 'allow'
ORDER BY occurred_at DESC
LIMIT $2`)
	storm.RegisterStatement(`
SELECT g.id::text AS id, g.identity_id::text AS identity_id,
       g.role_id::text AS role_id, r.name AS role_name, g.self_scoped,
       g.valid_from, g.valid_until, g.revoked_at,
       g.granted_by::text AS granted_by, g.reason,
       g.via_membership_id::text AS via_membership_id
FROM grants g
JOIN roles r ON r.id = g.role_id
WHERE g.identity_id = $1 AND g.tenant_id = $2
  AND ($3::boolean OR g.revoked_at IS NULL)
ORDER BY g.created_at DESC`)
	storm.RegisterStatement(`
SELECT g.id::text AS id, g.identity_id::text AS identity_id, i.username,
       g.role_id::text AS role_id, r.name AS role_name,
       g.self_scoped, g.valid_from, g.valid_until, g.revoked_at,
       g.granted_by::text AS granted_by, g.reason,
       g.via_membership_id::text AS via_membership_id, g.created_at
  FROM grants g
  JOIN roles r      ON r.id = g.role_id
  JOIN identities i ON i.id = g.identity_id
 WHERE g.tenant_id = $1
   AND ($2::boolean OR g.revoked_at IS NULL)
   AND ($3::text = '' OR g.identity_id::text = $3::text)
   AND ($4::text = ''     OR g.role_id::text = $4::text)
   AND ($5::text <> 'direct'     OR g.via_membership_id IS NULL)
   AND ($5::text <> 'membership' OR g.via_membership_id IS NOT NULL)
   AND ($6::text = ''
        OR i.username ILIKE '%' || $6::text || '%'
        OR r.name     ILIKE '%' || $6::text || '%')
   AND ($7::text = ''
        OR (g.created_at, g.id) < (
              SELECT g2.created_at, g2.id FROM grants g2
               WHERE g2.id::text = $7::text))
 ORDER BY g.created_at DESC, g.id DESC
 LIMIT $8`)
	storm.RegisterStatement(`
SELECT gs.grant_id::text AS grant_id, gs.axis_code,
       gs.scope_node_id::text AS scope_node_id, gs.inherit,
       sn.name AS node_name
FROM grant_scopes gs
JOIN scope_nodes sn ON sn.id = gs.scope_node_id
WHERE gs.grant_id = ANY($1::uuid[])
ORDER BY gs.grant_id, gs.axis_code, sn.name`)
	storm.RegisterStatement(`
SELECT id::text AS id FROM permissions
WHERE tenant_id = $1 AND key = $2
  AND deprecated_at IS NULL`)
	storm.RegisterStatement(`
SELECT id::text AS id, key, risk, min_assurance, requires_amr,
       COALESCE(max_auth_age::text, '')::text AS max_auth_age, deprecated_at
FROM permissions
WHERE tenant_id = $1 AND key = $2`)
	storm.RegisterStatement(`
SELECT id::text AS id, tenant_id::text AS tenant_id, name, description
FROM memberships
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
SELECT m.id::text AS id, m.name, m.description,
       (SELECT count(*) FROM membership_members mm
         WHERE mm.membership_id = m.id)::int AS member_count
FROM memberships m
WHERE m.tenant_id = $1
ORDER BY m.name`)
	storm.RegisterStatement(`
SELECT me.id::text AS id, me.membership_id::text AS membership_id,
       me.role_id::text AS role_id, r.name AS role_name
FROM membership_entries me
JOIN roles r ON r.id = me.role_id
WHERE me.membership_id = ANY($1::uuid[])
ORDER BY r.name`)
	storm.RegisterStatement(`
SELECT membership_assign($1, $2, $3) AS grants_created`)
	storm.RegisterStatement(`
SELECT membership_resync($1) AS grants_changed`)
	storm.RegisterStatement(`
SELECT membership_unassign($1, $2) AS grants_revoked`)
	storm.RegisterStatement(`
SELECT mes.entry_id::text AS entry_id, mes.axis_code,
       mes.scope_node_id::text AS scope_node_id, mes.inherit,
       sn.name AS node_name
FROM membership_entry_scopes mes
JOIN scope_nodes sn ON sn.id = mes.scope_node_id
WHERE mes.entry_id = ANY($1::uuid[])`)
	storm.RegisterStatement(`
SELECT p.id::text AS id, p.key, p.app_slug, p.resource, p.action, p.risk,
       p.description, p.min_assurance, p.requires_amr,
       COALESCE(p.max_auth_age::text, '')::text AS max_auth_age,
       p.deprecated_at
FROM permissions p
WHERE p.tenant_id = $1
  AND ($2::uuid IS NULL OR p.application_id = $2)
  AND ($3::boolean OR p.deprecated_at IS NULL)
ORDER BY p.key`)
	storm.RegisterStatement(`
SELECT p.key AS permission_key, vr.name AS via_role
FROM role_permissions_effective rpe
JOIN permissions p ON p.id = rpe.permission_id
JOIN roles vr ON vr.id = rpe.via_role_id
WHERE rpe.role_id = $1
ORDER BY p.key`)
	storm.RegisterStatement(`
SELECT parent_id::text AS parent_id FROM role_parents WHERE role_id = $1`)
	storm.RegisterStatement(`
SELECT pattern FROM role_permission_patterns WHERE role_id = $1
ORDER BY pattern`)
	storm.RegisterStatement(`
SELECT r.id::text AS id, r.tenant_id::text AS tenant_id, r.name, r.description,
       r.is_system, r.allowed_realm_kinds, r.assignable_at,
       r.application_id::text AS application_id,
       a.slug AS application_slug
FROM roles r
LEFT JOIN applications a ON a.id = r.application_id
WHERE r.id = $1 AND r.tenant_id = $2`)
	storm.RegisterStatement(`
SELECT r.id::text AS id, r.tenant_id::text AS tenant_id, r.name, r.description,
       r.is_system, r.allowed_realm_kinds, r.assignable_at,
       r.application_id::text AS application_id,
       a.slug AS application_slug
FROM roles r
LEFT JOIN applications a ON a.id = r.application_id
WHERE r.tenant_id = $1
  AND ($2::text IS NULL OR r.name ILIKE '%' || $2 || '%')
ORDER BY r.name`)
	storm.RegisterStatement(`
UPDATE grants
SET revoked_at = now(),
    reason = CASE WHEN $3 = '' THEN reason ELSE $3 END
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
RETURNING id::text AS id, identity_id::text AS identity_id,
          role_id::text AS role_id`)
	storm.RegisterStatement(`
UPDATE permissions
SET deprecated_at = now()
WHERE application_id = $1
  AND deprecated_at IS NULL
  AND NOT (id = ANY($2::uuid[]))
RETURNING key`)
	storm.RegisterStatement(`
UPDATE roles
SET description = $3,
    allowed_realm_kinds = $4::text[],
    assignable_at = $5::text[],
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND NOT is_system`)
	storm.RegisterStatement(`
WITH RECURSIVE down AS (
    SELECT rp.role_id FROM role_parents rp WHERE rp.parent_id = $1
    UNION
    SELECT rp.role_id FROM role_parents rp JOIN down d ON rp.parent_id = d.role_id
)
SELECT DISTINCT role_id::text AS role_id FROM down`)
	storm.RegisterStatement(`
WITH targets AS MATERIALIZED (
    SELECT t.key AS axis_code, t.value::uuid AS node_id
      FROM jsonb_each_text($4::jsonb) AS t(key, value)
     WHERE t.key NOT LIKE '\_%'
),
candidates AS (
    SELECT g.id, g.self_scoped
      FROM grants g
      JOIN identities i
        ON i.id = g.identity_id AND i.tenant_id = g.tenant_id
      JOIN role_permissions_effective rpe ON rpe.role_id = g.role_id
      JOIN permissions p ON p.id = rpe.permission_id
     WHERE g.identity_id = $1
       AND g.tenant_id   = $2
       AND g.revoked_at IS NULL
       AND g.valid_from <= now()
       AND (g.valid_until IS NULL OR g.valid_until > now())
       AND i.status = 'active'
       AND i.disabled_at IS NULL
       AND i.anonymized_at IS NULL
       AND p.tenant_id = $2
       AND p.key = $3
       AND p.deprecated_at IS NULL
       AND p.min_assurance <= i.assurance_level
),
axis_eval AS (
    SELECT gs.grant_id, gs.axis_code,
           bool_or(EXISTS (SELECT 1
                     FROM targets t
                     JOIN scope_closure c
                       ON c.descendant_id = t.node_id
                      AND c.ancestor_id   = gs.scope_node_id
                    WHERE t.axis_code = gs.axis_code
                      AND (gs.inherit OR c.depth = 0))) AS satisfied
      FROM grant_scopes gs JOIN candidates cd ON cd.id = gs.grant_id
     GROUP BY gs.grant_id, gs.axis_code
)
SELECT EXISTS (
    SELECT 1 FROM candidates cd
     WHERE (NOT cd.self_scoped
            OR ($4::jsonb ? '_owner'
                AND ($4::jsonb->>'_owner')::uuid = $1))
       AND NOT EXISTS (SELECT 1 FROM axis_eval ae
                        WHERE ae.grant_id = cd.id AND NOT ae.satisfied)
       AND NOT EXISTS (SELECT 1 FROM scope_axes a
                        WHERE ((a.default_effect = 'deny' AND a.status = 'active')
                               OR a.code = $5)
                          AND NOT EXISTS (SELECT 1 FROM grant_scopes gs2
                                           WHERE gs2.grant_id = cd.id
                                             AND gs2.axis_code = a.code))
)::boolean AS allow`)
}

func scanAuthorizeRow(rv [][]byte, r *authzrquery.AuthorizeRow, sl *runtime.Slab) error {
	r.Allow = runtime.Bool(rv[0])
	return nil
}

func scanExplainRow(rv [][]byte, r *authzrquery.ExplainRow, sl *runtime.Slab) error {
	r.Detail = sl.Str(rv[0])
	return nil
}

func scanPermissionMetaRow(rv [][]byte, r *authzrquery.PermissionMetaRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.Key = runtime.NullText(rv[1], sl)
	r.Risk = sl.Str(rv[2])
	r.MinAssurance = runtime.Int2(rv[3])
	r.RequiresAmr, decErr = runtime.TextArray(rv[4], sl)
	if decErr != nil {
		return decErr
	}
	r.MaxAuthAge = sl.Str(rv[5])
	r.DeprecatedAt = runtime.Nullable(rv[6], runtime.Timestamptz)
	return nil
}

func scanRoleNameRow(rv [][]byte, r *authzrquery.RoleNameRow, sl *runtime.Slab) error {
	r.Name = sl.Str(rv[0])
	return nil
}

func scanPermissionKeyRow(rv [][]byte, r *authzrquery.PermissionKeyRow, sl *runtime.Slab) error {
	r.Key = runtime.NullText(rv[0], sl)
	return nil
}

func scanStrictSimRow(rv [][]byte, r *authzrquery.StrictSimRow, sl *runtime.Slab) error {
	r.Allow = runtime.Bool(rv[0])
	return nil
}

func scanDecisionDetailRow(rv [][]byte, r *authzrquery.DecisionDetailRow, sl *runtime.Slab) error {
	r.Detail = runtime.JSON(runtime.JSONB(rv[0], sl))
	return nil
}

func scanRoleRow(rv [][]byte, r *authzrquery.RoleRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Name = sl.Str(rv[2])
	r.Description = sl.Str(rv[3])
	r.IsSystem = runtime.Bool(rv[4])
	r.AllowedRealmKinds, decErr = runtime.TextArray(rv[5], sl)
	if decErr != nil {
		return decErr
	}
	r.AssignableAt, decErr = runtime.TextArray(rv[6], sl)
	if decErr != nil {
		return decErr
	}
	r.ApplicationID = runtime.NullText(rv[7], sl)
	r.ApplicationSlug = runtime.NullText(rv[8], sl)
	return nil
}

func scanCreatedRoleRow(rv [][]byte, r *authzrquery.CreatedRoleRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}

func scanParentRow(rv [][]byte, r *authzrquery.ParentRow, sl *runtime.Slab) error {
	r.ParentID = sl.Str(rv[0])
	return nil
}

func scanPatternRow(rv [][]byte, r *authzrquery.PatternRow, sl *runtime.Slab) error {
	r.Pattern = sl.Str(rv[0])
	return nil
}

func scanDoneRow(rv [][]byte, r *authzrquery.DoneRow, sl *runtime.Slab) error {
	r.Done = runtime.Bool(rv[0])
	return nil
}

func scanRoleIDRow(rv [][]byte, r *authzrquery.RoleIDRow, sl *runtime.Slab) error {
	r.RoleID = sl.Str(rv[0])
	return nil
}

func scanEffectiveRow(rv [][]byte, r *authzrquery.EffectiveRow, sl *runtime.Slab) error {
	r.PermissionKey = runtime.NullText(rv[0], sl)
	r.ViaRole = sl.Str(rv[1])
	return nil
}

func scanGrantRow(rv [][]byte, r *authzrquery.GrantRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.RoleID = sl.Str(rv[2])
	r.RoleName = sl.Str(rv[3])
	r.SelfScoped = runtime.Bool(rv[4])
	r.ValidFrom = runtime.Timestamptz(rv[5])
	r.ValidUntil = runtime.Nullable(rv[6], runtime.Timestamptz)
	r.RevokedAt = runtime.Nullable(rv[7], runtime.Timestamptz)
	r.GrantedBy = sl.Str(rv[8])
	r.Reason = runtime.NullText(rv[9], sl)
	r.ViaMembershipID = runtime.NullText(rv[10], sl)
	return nil
}

func scanGrantScopeRow(rv [][]byte, r *authzrquery.GrantScopeRow, sl *runtime.Slab) error {
	r.GrantID = sl.Str(rv[0])
	r.AxisCode = sl.Str(rv[1])
	r.ScopeNodeID = sl.Str(rv[2])
	r.Inherit = runtime.Bool(rv[3])
	r.NodeName = sl.Str(rv[4])
	return nil
}

func scanCreatedGrantRow(rv [][]byte, r *authzrquery.CreatedGrantRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.ValidFrom = runtime.Timestamptz(rv[1])
	return nil
}

func scanRevokedGrantRow(rv [][]byte, r *authzrquery.RevokedGrantRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.RoleID = sl.Str(rv[2])
	return nil
}

func scanSearchGrantRow(rv [][]byte, r *authzrquery.SearchGrantRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.Username = sl.Str(rv[2])
	r.RoleID = sl.Str(rv[3])
	r.RoleName = sl.Str(rv[4])
	r.SelfScoped = runtime.Bool(rv[5])
	r.ValidFrom = runtime.Timestamptz(rv[6])
	r.ValidUntil = runtime.Nullable(rv[7], runtime.Timestamptz)
	r.RevokedAt = runtime.Nullable(rv[8], runtime.Timestamptz)
	r.GrantedBy = sl.Str(rv[9])
	r.Reason = runtime.NullText(rv[10], sl)
	r.ViaMembershipID = runtime.NullText(rv[11], sl)
	r.CreatedAt = runtime.Timestamptz(rv[12])
	return nil
}

func scanCountRow(rv [][]byte, r *authzrquery.CountRow, sl *runtime.Slab) error {
	r.Count = runtime.Int8(rv[0])
	return nil
}

func scanMembershipListRow(rv [][]byte, r *authzrquery.MembershipListRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.Name = sl.Str(rv[1])
	r.Description = sl.Str(rv[2])
	r.MemberCount = runtime.Int4(rv[3])
	return nil
}

func scanMembershipRow(rv [][]byte, r *authzrquery.MembershipRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Name = sl.Str(rv[2])
	r.Description = sl.Str(rv[3])
	return nil
}

func scanCreatedMembershipRow(rv [][]byte, r *authzrquery.CreatedMembershipRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}

func scanEntryRow(rv [][]byte, r *authzrquery.EntryRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.MembershipID = sl.Str(rv[1])
	r.RoleID = sl.Str(rv[2])
	r.RoleName = sl.Str(rv[3])
	return nil
}

func scanEntryScopeRow(rv [][]byte, r *authzrquery.EntryScopeRow, sl *runtime.Slab) error {
	r.EntryID = sl.Str(rv[0])
	r.AxisCode = sl.Str(rv[1])
	r.ScopeNodeID = sl.Str(rv[2])
	r.Inherit = runtime.Bool(rv[3])
	r.NodeName = sl.Str(rv[4])
	return nil
}

func scanInsertedEntryRow(rv [][]byte, r *authzrquery.InsertedEntryRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}

func scanAssignRow(rv [][]byte, r *authzrquery.AssignRow, sl *runtime.Slab) error {
	r.GrantsCreated = runtime.Int4(rv[0])
	return nil
}

func scanUnassignRow(rv [][]byte, r *authzrquery.UnassignRow, sl *runtime.Slab) error {
	r.GrantsRevoked = runtime.Int4(rv[0])
	return nil
}

func scanResyncRow(rv [][]byte, r *authzrquery.ResyncRow, sl *runtime.Slab) error {
	r.GrantsChanged = runtime.Int4(rv[0])
	return nil
}

func scanPermissionRow(rv [][]byte, r *authzrquery.PermissionRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.Key = runtime.NullText(rv[1], sl)
	r.AppSlug = sl.Str(rv[2])
	r.Resource = sl.Str(rv[3])
	r.Action = sl.Str(rv[4])
	r.Risk = sl.Str(rv[5])
	r.Description = sl.Str(rv[6])
	r.MinAssurance = runtime.Int2(rv[7])
	r.RequiresAmr, decErr = runtime.TextArray(rv[8], sl)
	if decErr != nil {
		return decErr
	}
	r.MaxAuthAge = sl.Str(rv[9])
	r.DeprecatedAt = runtime.Nullable(rv[10], runtime.Timestamptz)
	return nil
}

func scanUpsertedPermissionRow(rv [][]byte, r *authzrquery.UpsertedPermissionRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.Key = runtime.NullText(rv[1], sl)
	r.Inserted = runtime.Nullable(rv[2], runtime.Bool)
	return nil
}

func scanDeprecatedKeyRow(rv [][]byte, r *authzrquery.DeprecatedKeyRow, sl *runtime.Slab) error {
	r.Key = runtime.NullText(rv[0], sl)
	return nil
}

func scanPermissionIDRow(rv [][]byte, r *authzrquery.PermissionIDRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}
