// Code generated by storm v0.6.3. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/anubis/internal/authz/adapter/postgres/rmodel"
)

// _assertRoleShape fails to compile if m0.Role gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertRoleShape(m m0.Role) {
	type shape m0.Role
	_ = shape{
		m.Model,
		m.TenantID,
		m.ApplicationID,
		m.IsSystem,
		m.Name,
		m.Description,
		m.AssignableAt,
		m.AllowedRealmKinds,
	}
}
