/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as IdentitiesRouteImport } from './routes/identities'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as RealmsRouteImport } from './routes/realms'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as SigninPageRouteImport } from './routes/signin-page'
import { Route as TenantsRouteImport } from './routes/tenants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesRoute = IdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmsRoute = RealmsRouteImport.update({
  id: '/realms',
  path: '/realms',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninPageRoute = SigninPageRouteImport.update({
  id: '/signin-page',
  path: '/signin-page',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/grants': typeof GrantsRoute
  '/identities': typeof IdentitiesRoute
  '/keys': typeof KeysRoute
  '/memberships': typeof MembershipsRoute
  '/playground': typeof PlaygroundRoute
  '/realms': typeof RealmsRoute
  '/roles': typeof RolesRoute
  '/scope': typeof ScopeRoute
  '/signin-page': typeof SigninPageRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/grants': typeof GrantsRoute
  '/identities': typeof IdentitiesRoute
  '/keys': typeof KeysRoute
  '/memberships': typeof MembershipsRoute
  '/playground': typeof PlaygroundRoute
  '/realms': typeof RealmsRoute
  '/roles': typeof RolesRoute
  '/scope': typeof ScopeRoute
  '/signin-page': typeof SigninPageRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/grants': typeof GrantsRoute
  '/identities': typeof IdentitiesRoute
  '/keys': typeof KeysRoute
  '/memberships': typeof MembershipsRoute
  '/playground': typeof PlaygroundRoute
  '/realms': typeof RealmsRoute
  '/roles': typeof RolesRoute
  '/scope': typeof ScopeRoute
  '/signin-page': typeof SigninPageRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/grants'
    | '/identities'
    | '/keys'
    | '/memberships'
    | '/playground'
    | '/realms'
    | '/roles'
    | '/scope'
    | '/signin-page'
    | '/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/grants'
    | '/identities'
    | '/keys'
    | '/memberships'
    | '/playground'
    | '/realms'
    | '/roles'
    | '/scope'
    | '/signin-page'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/grants'
    | '/identities'
    | '/keys'
    | '/memberships'
    | '/playground'
    | '/realms'
    | '/roles'
    | '/scope'
    | '/signin-page'
    | '/tenants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  GrantsRoute: typeof GrantsRoute
  IdentitiesRoute: typeof IdentitiesRoute
  KeysRoute: typeof KeysRoute
  MembershipsRoute: typeof MembershipsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RealmsRoute: typeof RealmsRoute
  RolesRoute: typeof RolesRoute
  ScopeRoute: typeof ScopeRoute
  SigninPageRoute: typeof SigninPageRoute
  TenantsRoute: typeof TenantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities': {
      id: '/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof IdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realms': {
      id: '/realms'
      path: '/realms'
      fullPath: '/realms'
      preLoaderRoute: typeof RealmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-page': {
      id: '/signin-page'
      path: '/signin-page'
      fullPath: '/signin-page'
      preLoaderRoute: typeof SigninPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  GrantsRoute: GrantsRoute,
  IdentitiesRoute: IdentitiesRoute,
  KeysRoute: KeysRoute,
  MembershipsRoute: MembershipsRoute,
  PlaygroundRoute: PlaygroundRoute,
  RealmsRoute: RealmsRoute,
  RolesRoute: RolesRoute,
  ScopeRoute: ScopeRoute,
  SigninPageRoute: SigninPageRoute,
  TenantsRoute: TenantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
