/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as IdentitiesRouteImport } from './routes/identities'
import { Route as ImportRouteImport } from './routes/import'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as RealmsRouteImport } from './routes/realms'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SigninPageRouteImport } from './routes/signin-page'
import { Route as TenantsRouteImport } from './routes/tenants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesRoute = IdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmsRoute = RealmsRouteImport.update({
  id: '/realms',
  path: '/realms',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninPageRoute = SigninPageRouteImport.update({
  id: '/signin-page',
  path: '/signin-page',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/grants': typeof GrantsRoute
  '/identities': typeof IdentitiesRoute
  '/import': typeof ImportRoute
  '/keys': typeof KeysRoute
  '/memberships': typeof MembershipsRoute
  '/operators': typeof OperatorsRoute
  '/playground': typeof PlaygroundRoute
  '/realms': typeof RealmsRoute
  '/roles': typeof RolesRoute
  '/scope': typeof ScopeRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/signin-page': typeof SigninPageRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/grants': typeof GrantsRoute
  '/identities': typeof IdentitiesRoute
  '/import': typeof ImportRoute
  '/keys': typeof KeysRoute
  '/memberships': typeof MembershipsRoute
  '/operators': typeof OperatorsRoute
  '/playground': typeof PlaygroundRoute
  '/realms': typeof RealmsRoute
  '/roles': typeof RolesRoute
  '/scope': typeof ScopeRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/signin-page': typeof SigninPageRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/grants': typeof GrantsRoute
  '/identities': typeof IdentitiesRoute
  '/import': typeof ImportRoute
  '/keys': typeof KeysRoute
  '/memberships': typeof MembershipsRoute
  '/operators': typeof OperatorsRoute
  '/playground': typeof PlaygroundRoute
  '/realms': typeof RealmsRoute
  '/roles': typeof RolesRoute
  '/scope': typeof ScopeRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/signin-page': typeof SigninPageRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/audit'
    | '/grants'
    | '/identities'
    | '/import'
    | '/keys'
    | '/memberships'
    | '/operators'
    | '/playground'
    | '/realms'
    | '/roles'
    | '/scope'
    | '/setup'
    | '/signin'
    | '/signin-page'
    | '/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/audit'
    | '/grants'
    | '/identities'
    | '/import'
    | '/keys'
    | '/memberships'
    | '/operators'
    | '/playground'
    | '/realms'
    | '/roles'
    | '/scope'
    | '/setup'
    | '/signin'
    | '/signin-page'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/audit'
    | '/grants'
    | '/identities'
    | '/import'
    | '/keys'
    | '/memberships'
    | '/operators'
    | '/playground'
    | '/realms'
    | '/roles'
    | '/scope'
    | '/setup'
    | '/signin'
    | '/signin-page'
    | '/tenants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuditRoute: typeof AuditRoute
  GrantsRoute: typeof GrantsRoute
  IdentitiesRoute: typeof IdentitiesRoute
  ImportRoute: typeof ImportRoute
  KeysRoute: typeof KeysRoute
  MembershipsRoute: typeof MembershipsRoute
  OperatorsRoute: typeof OperatorsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RealmsRoute: typeof RealmsRoute
  RolesRoute: typeof RolesRoute
  ScopeRoute: typeof ScopeRoute
  SetupRoute: typeof SetupRoute
  SigninRoute: typeof SigninRoute
  SigninPageRoute: typeof SigninPageRoute
  TenantsRoute: typeof TenantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities': {
      id: '/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof IdentitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realms': {
      id: '/realms'
      path: '/realms'
      fullPath: '/realms'
      preLoaderRoute: typeof RealmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin-page': {
      id: '/signin-page'
      path: '/signin-page'
      fullPath: '/signin-page'
      preLoaderRoute: typeof SigninPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuditRoute: AuditRoute,
  GrantsRoute: GrantsRoute,
  IdentitiesRoute: IdentitiesRoute,
  ImportRoute: ImportRoute,
  KeysRoute: KeysRoute,
  MembershipsRoute: MembershipsRoute,
  OperatorsRoute: OperatorsRoute,
  PlaygroundRoute: PlaygroundRoute,
  RealmsRoute: RealmsRoute,
  RolesRoute: RolesRoute,
  ScopeRoute: ScopeRoute,
  SetupRoute: SetupRoute,
  SigninRoute: SigninRoute,
  SigninPageRoute: SigninPageRoute,
  TenantsRoute: TenantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
