-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-19.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- A TOTP secret is sealed ONCE at enrolment and read for the life of the
-- enrolment, but both the seal and the open asked for whichever local key was
-- active at the time. Rotating the local key -- `anubisd keys promote local`,
-- which operations.md requires after a key compromise -- therefore locked out
-- every enrolled user, and presented as "invalid code" rather than as an
-- outage.
--
-- NULL means the row predates this column. The reader falls back to the active
-- local key and writes the kid back on success, so existing enrolments heal on
-- next use rather than needing a backfill that would have to guess.
ALTER TABLE "credentials" ADD COLUMN "secret_kid" varchar(64);
