-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-20.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- browser_mfa is its OWN kind rather than reusing 'mfa'.
--
-- The two carry different payloads: the API's challenge is a signed token,
-- this one is the identity the password was just checked for. Sharing a kind
-- would make each a candidate for the other's ConsumeOneTime, and "both
-- happen to fail closed today" is not a property anybody stated or tested.
-- A distinct kind makes the confusion impossible instead of unlikely.
ALTER TABLE "one_time_tokens" DROP CONSTRAINT "one_time_tokens_kind_check";
ALTER TABLE "one_time_tokens" ADD CONSTRAINT "one_time_tokens_kind_check" CHECK (kind = ANY (ARRAY['mfa'::text, 'browser_mfa'::text, 'auth_code'::text, 'device_challenge'::text, 'email_verify'::text, 'password_reset'::text]));
