-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-20.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- A signed statement that a tenant's hash chain reached a given entry with a
-- given hash.
--
-- The chain alone catches a row edited in place or deleted: the next entry's
-- prev_hash stops matching, or a seq goes missing. It does NOT catch a
-- wholesale rewrite — recompute every forward hash and the result is
-- self-consistent. 0005 claimed "an attacker with UPDATE rights on this table
-- still cannot silently rewrite history"; what actually stood in the way was
-- that anubis_app holds no UPDATE grant, which is a permissions property
-- rather than a cryptographic one.
--
-- An anchor is the cryptographic half. Rewriting now also means producing a
-- chain whose hash at each anchored seq equals a value signed with the access
-- key, which is sealed under the master key. An attacker holding the database
-- but not the master cannot do that.
--
-- No UPDATE or DELETE is granted on this table either (0023): an anchor that
-- can be removed anchors nothing.
CREATE TABLE "audit_anchors" (
    "signed_at" timestamptz DEFAULT now() NOT NULL,
    "id" uuid DEFAULT uuidv7() NOT NULL,
    "seq" int8 NOT NULL,
    "entry_hash" bytea NOT NULL,
    "kid" varchar(64) NOT NULL,
    "signature" bytea NOT NULL,
    "tenant_id" uuid NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "audit_anchors_tenant_seq" ON "audit_anchors" ("tenant_id", "seq");
ALTER TABLE "audit_anchors" ADD CONSTRAINT "audit_anchors_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON DELETE CASCADE;
