-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-20.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- browser_enrol is its own kind for the same reason browser_mfa is (0048).
--
-- It carries what the hosted page needs to finish an enrolment on somebody's
-- behalf: the identity, the enrol grant minted for them, and the pending
-- enrolment handle. That is strictly more than browser_mfa's payload, and a
-- shared kind would make each a candidate for the other's ConsumeOneTime.
--
-- Why the page holds a grant at all: past a realm's factor_enrolment_deadline
-- the API answers an un-enrolled member with a grant token to enrol against,
-- and the browser had nowhere to spend one — so the refusal was a dead end
-- for the population that only ever uses SSO.

ALTER TABLE "one_time_tokens" DROP CONSTRAINT "one_time_tokens_kind_check";
ALTER TABLE "one_time_tokens" ADD CONSTRAINT "one_time_tokens_kind_check" CHECK (kind = ANY (ARRAY['mfa'::text, 'browser_mfa'::text, 'browser_enrol'::text, 'auth_code'::text, 'device_challenge'::text, 'email_verify'::text, 'password_reset'::text]));
