-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-26.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- A refresh token did not record which application it was issued to, so a
-- rotation re-issued with no client at all: audience "anubis" — this
-- server's own — instead of the application's, the default token format, and
-- the population's lifetimes instead of the application's stricter ones.
-- client_id is carried from generation to generation, and a rotation issues
-- for it.
--
-- Nullable, and NULL keeps the old behaviour: a family issued with no client
-- (AuthService.Login, the console) has none to remember, and a family issued
-- before this migration rotates exactly as it did until it expires. No
-- backfill is possible — the fact was never written down.
--
-- A nullable column with no default is a catalog change, not a rewrite, on
-- the parent and every partition.

ALTER TABLE "refresh_tokens" ADD COLUMN "client_id" text;
