-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-27.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- A client_credentials token's audience was whatever the caller asked for,
-- with no allowlist. So a machine client authenticated as one application
-- could mint a token audienced at any sibling application and be accepted by
-- it (pkg/anubis checks aud) — the confused-deputy control the whole aud
-- claim exists for, defeated for machine tokens. allowed_audiences is the
-- opt-in list of audiences an app's tokens may request beyond its own slug.
--
-- Default '{}' is self-only, which is secure and is what every existing app
-- gets: a client that was requesting a DIFFERENT app's audience stops being
-- issued one until that audience is added here. A nullable-free column add
-- with a default is a catalog change, not a table rewrite.
ALTER TABLE "applications" ADD COLUMN "allowed_audiences" text[] DEFAULT '{}'::text[] NOT NULL;
