-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-28.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- A grant had one reason column for two different answers. Revoking with a
-- reason wrote it over `reason` — the only place the note written when the
-- access was GIVEN was kept (grant.create's audit event does not carry it). So
-- "INC-1042, month-end close" became "console" the moment somebody revoked
-- the grant, and why the person ever had the access was gone.
--
-- `reason` is now why it was given and is never written by a revoke;
-- `revoke_reason` is why it was taken away. Sessions already keep theirs apart.
--
-- Rows revoked before this migration are left as they are. A revoke without a
-- reason kept the original, so nothing in a row says whether its `reason` is
-- the grant's or the revoke's; guessing would rewrite history with fiction.
--
-- Nullable with no default: a catalog change, not a table rewrite.
ALTER TABLE "grants" ADD COLUMN "revoke_reason" text;
