-- Generated by cmd/stormddl from internal/platform/schema on 2026-09-28, then
-- reordered by hand where marked: storm does not diff primary keys, and it
-- emitted the grants -> membership_members(id) key before that column existed.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.
--
-- CONTAINS DESTRUCTIVE STEPS — read every one before this is applied to
-- anything holding data. They are the two DROP FUNCTIONs at the end: the old
-- membership_assign / membership_unassign signatures, replaced here.

-- Two things memberships could not do, and one they could not survive.
--
-- 1. Apply WHERE EACH MEMBER IS ASSIGNED. A membership named its places once,
--    for everybody, so a seat on a council defined at group level was a seat
--    in every company of the group. memberships.anchor_axis (NULL keeps the old
--    behaviour, which every existing membership keeps) moves the place onto the
--    assignment instead — Organization A for one member, a single work office
--    for another, at any depth of that structure. Fixed at creation.
--
-- 2. Hold one membership at several places, with an end date and a note. An
--    assignment was a (membership, person) pair; it is now a row with its own
--    id, place, end date and reason, and grants.via_member_id records which
--    assignment each derived grant came from — so leaving one place takes back
--    that place's grants and nobody else's.
--
-- 3. Change after anybody had joined. Replacing a membership's roles DELETEd
--    its entries, and grants.via_entry_id is ON DELETE RESTRICT against a grants
--    table that keeps revoked rows as history: the first assignment froze the
--    membership's contents for good. Entries are now retired (retired_at),
--    never deleted, and membership_resync revokes what a retired entry gave.
--    Leaving is the same shape: removed_at, not DELETE.

-- Hand-ordered: an assignment gets its own identity before anything can point
-- at one, and the old (membership, person) key goes, or nobody could hold the
-- same membership at two places.
ALTER TABLE "membership_members" ADD COLUMN "id" uuid DEFAULT uuidv7() NOT NULL;
ALTER TABLE "membership_members" DROP CONSTRAINT "membership_members_pkey";
ALTER TABLE "membership_members" ADD PRIMARY KEY ("id");
ALTER TABLE "membership_members" ADD COLUMN "valid_until" timestamptz;
ALTER TABLE "membership_members" ADD COLUMN "removed_at" timestamptz;
ALTER TABLE "membership_members" ADD COLUMN "removed_by" uuid;
ALTER TABLE "membership_members" ADD COLUMN "scope_node_id" uuid;
ALTER TABLE "membership_members" ADD COLUMN "axis_code" text;
ALTER TABLE "membership_members" ADD COLUMN "inherit" bool DEFAULT true NOT NULL;
ALTER TABLE "membership_members" ADD COLUMN "reason" text;
ALTER TABLE "membership_members" ADD CONSTRAINT "membership_members_place_check" CHECK ((axis_code IS NULL) = (scope_node_id IS NULL));
ALTER TABLE "membership_members" ADD CONSTRAINT "membership_members_removal_check" CHECK ((removed_at IS NULL) = (removed_by IS NULL));
ALTER TABLE "membership_members" ADD CONSTRAINT "membership_members_scope_node_id_tenant_id_axis_code_fkey" FOREIGN KEY ("scope_node_id", "tenant_id", "axis_code") REFERENCES "scope_nodes" ("id", "tenant_id", "axis_code") ON DELETE RESTRICT;
CREATE INDEX "membership_members_identity_live" ON "membership_members" ("identity_id") WHERE removed_at IS NULL;
CREATE UNIQUE INDEX "membership_members_live_everywhere" ON "membership_members" ("membership_id", "identity_id") WHERE (removed_at IS NULL) AND (scope_node_id IS NULL);
CREATE UNIQUE INDEX "membership_members_live_placed" ON "membership_members" ("membership_id", "identity_id", "scope_node_id") WHERE (removed_at IS NULL) AND (scope_node_id IS NOT NULL);
ALTER TABLE "membership_entries" ADD COLUMN "retired_at" timestamptz;
ALTER TABLE "memberships" ADD COLUMN "anchor_axis" text;
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_anchor_axis_fkey" FOREIGN KEY ("anchor_axis") REFERENCES "scope_axes" ("code") ON DELETE RESTRICT;

ALTER TABLE "grants" ADD COLUMN "via_member_id" uuid;
ALTER TABLE "grants" ADD CONSTRAINT "grants_via_member_id_fkey" FOREIGN KEY ("via_member_id") REFERENCES "membership_members" ("id");
CREATE INDEX "grants_via_member" ON "grants" ("via_member_id") WHERE (via_member_id IS NOT NULL) AND (revoked_at IS NULL);

-- Hand-written: every derived grant learns which assignment it came from.
-- Until now an assignment WAS (membership, person), so that pair names it
-- exactly. Grants whose assignment had already been deleted — somebody who
-- left before this migration — keep a NULL: history with no row to point at.
UPDATE grants g SET via_member_id = mm.id
  FROM membership_members mm
 WHERE g.via_membership_id = mm.membership_id
   AND g.identity_id = mm.identity_id
   AND g.via_member_id IS NULL;

CREATE OR REPLACE FUNCTION "membership_assign"(p_identity uuid, p_membership uuid, p_by uuid, p_node uuid, p_inherit boolean, p_valid_until timestamp with time zone, p_reason text)
 RETURNS uuid
 LANGUAGE plpgsql
AS $storm$
DECLARE
    v_tenant uuid;
    v_anchor text;
    v_member uuid;
    e record;
BEGIN
    SELECT tenant_id, anchor_axis INTO v_tenant, v_anchor FROM memberships WHERE id = p_membership;
    IF v_tenant IS NULL THEN RAISE EXCEPTION 'unknown membership %', p_membership; END IF;
    IF v_anchor IS NULL AND p_node IS NOT NULL THEN
        RAISE EXCEPTION 'this membership gives every member the same places; an assignment names no place of its own'
              USING ERRCODE = 'check_violation';
    END IF;
    IF v_anchor IS NOT NULL AND p_node IS NULL THEN
        RAISE EXCEPTION 'this membership applies where each member is assigned: choose a place in "%"', v_anchor
              USING ERRCODE = 'check_violation';
    END IF;
    IF p_valid_until IS NOT NULL AND p_valid_until <= now() THEN
        RAISE EXCEPTION 'an assignment cannot end before it starts (%)', p_valid_until
              USING ERRCODE = 'check_violation';
    END IF;

    UPDATE membership_members SET removed_at = now(), removed_by = p_by
     WHERE membership_id = p_membership AND identity_id = p_identity AND removed_at IS NULL
       AND scope_node_id IS NOT DISTINCT FROM p_node
       AND valid_until IS NOT NULL AND valid_until <= now();
    IF EXISTS (SELECT 1 FROM membership_members
                WHERE membership_id = p_membership AND identity_id = p_identity
                  AND removed_at IS NULL AND scope_node_id IS NOT DISTINCT FROM p_node) THEN
        RETURN NULL;
    END IF;

    INSERT INTO membership_members (membership_id, identity_id, tenant_id, assigned_by,
                                    axis_code, scope_node_id, inherit, valid_until, reason)
    VALUES (p_membership, p_identity, v_tenant, p_by,
            CASE WHEN p_node IS NULL THEN NULL ELSE v_anchor END, p_node,
            COALESCE(p_inherit, true), p_valid_until, NULLIF(btrim(p_reason), ''))
    RETURNING id INTO v_member;

    FOR e IN SELECT id FROM membership_entries
              WHERE membership_id = p_membership AND retired_at IS NULL LOOP
        PERFORM membership_materialize(v_member, e.id);
    END LOOP;
    RETURN v_member;
END;
$storm$;
CREATE OR REPLACE FUNCTION "membership_leave"(p_member uuid, p_by uuid, p_reason text)
 RETURNS integer
 LANGUAGE plpgsql
AS $storm$
DECLARE v_n int;
BEGIN
    UPDATE grants SET revoked_at = now(),
                      revoke_reason = COALESCE(NULLIF(btrim(p_reason), ''), 'left the membership')
     WHERE via_member_id = p_member AND revoked_at IS NULL;
    GET DIAGNOSTICS v_n = ROW_COUNT;
    UPDATE membership_members SET removed_at = now(), removed_by = p_by
     WHERE id = p_member AND removed_at IS NULL;
    RETURN v_n;
END;
$storm$;
CREATE OR REPLACE FUNCTION "membership_materialize"(p_member uuid, p_entry uuid)
 RETURNS uuid
 LANGUAGE plpgsql
AS $storm$
DECLARE
    m membership_members%ROWTYPE;
    e membership_entries%ROWTYPE;
    v_grant uuid;
BEGIN
    SELECT * INTO m FROM membership_members WHERE id = p_member;
    SELECT * INTO e FROM membership_entries WHERE id = p_entry;
    -- realm-guard and role-live fire HERE, per row: a person one of the roles
    -- cannot serve aborts the whole assignment, never half of it.
    INSERT INTO grants (tenant_id, identity_id, role_id, granted_by, reason, valid_until,
                        via_membership_id, via_entry_id, via_member_id)
    VALUES (m.tenant_id, m.identity_id, e.role_id, m.assigned_by, m.reason, m.valid_until,
            m.membership_id, e.id, m.id)
    RETURNING id INTO v_grant;

    INSERT INTO grant_scopes (grant_id, tenant_id, axis_code, scope_node_id, inherit, mode)
    SELECT v_grant, s.tenant_id, s.axis_code, s.scope_node_id, s.inherit, s.mode
      FROM membership_entry_scopes s WHERE s.entry_id = e.id;
    IF m.scope_node_id IS NOT NULL THEN
        INSERT INTO grant_scopes (grant_id, tenant_id, axis_code, scope_node_id, inherit, mode)
        VALUES (v_grant, m.tenant_id, m.axis_code, m.scope_node_id, m.inherit, 'include');
    END IF;
    RETURN v_grant;
END;
$storm$;
CREATE OR REPLACE FUNCTION "membership_resync"(p_membership uuid)
 RETURNS integer
 LANGUAGE plpgsql
AS $storm$
DECLARE
    m record; e record; v_n int := 0;
BEGIN
    UPDATE grants g SET revoked_at = now(),
                        revoke_reason = COALESCE(g.revoke_reason, 'the membership no longer gives this role')
     WHERE g.via_membership_id = p_membership AND g.revoked_at IS NULL
       AND EXISTS (SELECT 1 FROM membership_entries me
                    WHERE me.id = g.via_entry_id AND me.retired_at IS NOT NULL);
    GET DIAGNOSTICS v_n = ROW_COUNT;

    FOR m IN SELECT id FROM membership_members
              WHERE membership_id = p_membership AND removed_at IS NULL
                AND (valid_until IS NULL OR valid_until > now()) LOOP
        FOR e IN SELECT me.id FROM membership_entries me
                  WHERE me.membership_id = p_membership AND me.retired_at IS NULL
                    AND NOT EXISTS (SELECT 1 FROM grants g
                                     WHERE g.via_entry_id = me.id AND g.via_member_id = m.id
                                       AND g.revoked_at IS NULL) LOOP
            PERFORM membership_materialize(m.id, e.id);
            v_n := v_n + 1;
        END LOOP;
    END LOOP;
    RETURN v_n;
END;
$storm$;
CREATE OR REPLACE FUNCTION "membership_unassign"(p_identity uuid, p_membership uuid, p_by uuid, p_reason text)
 RETURNS integer
 LANGUAGE plpgsql
AS $storm$
DECLARE v_n int;
BEGIN
    UPDATE grants SET revoked_at = now(),
                      revoke_reason = COALESCE(NULLIF(btrim(p_reason), ''), 'left the membership')
     WHERE identity_id = p_identity AND via_membership_id = p_membership
       AND revoked_at IS NULL;
    GET DIAGNOSTICS v_n = ROW_COUNT;
    UPDATE membership_members SET removed_at = now(), removed_by = p_by
     WHERE membership_id = p_membership AND identity_id = p_identity AND removed_at IS NULL;
    RETURN v_n;
END;
$storm$;
CREATE OR REPLACE FUNCTION "trg_membership_anchor_fixed"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $storm$
BEGIN
    RAISE EXCEPTION
      'where a membership applies is fixed when it is created (it applies %, not %)',
      COALESCE('where assigned in "' || OLD.anchor_axis || '"', 'the same for everyone'),
      COALESCE('where assigned in "' || NEW.anchor_axis || '"', 'the same for everyone')
      USING ERRCODE = 'check_violation';
END;
$storm$;
CREATE OR REPLACE FUNCTION "trg_membership_entry_anchor"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $storm$
BEGIN
    IF EXISTS (SELECT 1 FROM membership_entries e
                 JOIN memberships m ON m.id = e.membership_id
                WHERE e.id = NEW.entry_id AND m.anchor_axis = NEW.axis_code) THEN
        RAISE EXCEPTION
          'this membership applies where each member is assigned in "%", so its roles may not name places there themselves',
          NEW.axis_code
          USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$storm$;
CREATE OR REPLACE FUNCTION "trg_membership_member_place"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $storm$
DECLARE
    v_anchor text;
BEGIN
    SELECT anchor_axis INTO v_anchor FROM memberships WHERE id = NEW.membership_id;
    IF v_anchor IS NULL AND NEW.scope_node_id IS NOT NULL THEN
        RAISE EXCEPTION 'this membership gives every member the same places; an assignment names no place of its own'
              USING ERRCODE = 'check_violation';
    END IF;
    IF v_anchor IS NOT NULL AND (NEW.scope_node_id IS NULL OR NEW.axis_code IS DISTINCT FROM v_anchor) THEN
        RAISE EXCEPTION 'this membership applies where each member is assigned: choose a place in "%"', v_anchor
              USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$storm$;
CREATE CONSTRAINT TRIGGER membership_entry_scopes_anchor_guard AFTER INSERT OR UPDATE ON membership_entry_scopes DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION trg_membership_entry_anchor();
CREATE CONSTRAINT TRIGGER membership_members_place_guard AFTER INSERT OR UPDATE OF membership_id, axis_code, scope_node_id ON membership_members DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION trg_membership_member_place();
CREATE TRIGGER memberships_anchor_fixed BEFORE UPDATE OF anchor_axis ON memberships FOR EACH ROW WHEN ((old.anchor_axis IS DISTINCT FROM new.anchor_axis)) EXECUTE FUNCTION trg_membership_anchor_fixed();
-- storm:destructive function membership_assign(p_identity uuid, p_membership uuid, p_by uuid) is no longer in the model
DROP FUNCTION "membership_assign"(p_identity uuid, p_membership uuid, p_by uuid);
-- storm:destructive function membership_unassign(p_identity uuid, p_membership uuid) is no longer in the model
DROP FUNCTION "membership_unassign"(p_identity uuid, p_membership uuid);
