-- Generated by cmd/stormddl from internal/platform/schema on 2026-10-02.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.

-- The rules for what may sit under what were data nobody checked.
--
-- scope_node_types says which level may sit under which, and 0014 makes every
-- item obey it. Nothing made the rules themselves hold together:
--
-- - A level could name a parent that was no level at all, or a level of
--   another structure, and nothing could ever be placed under it.
-- - A structure could get a second top level (no parents). scope_ensure_root
--   then picked one alphabetically, which is how roots typed "department"
--   happened once already.
-- - Editing a level could take away a rule items already relied on, leaving
--   them placed where the rules say they cannot be — archived ones included,
--   since restoring an item does not re-run the placement guard.
-- - The top level could be given a parent, leaving the structure unable to
--   make a top item for the next tenant.
--
-- A constraint trigger now refuses each of those. It runs after the statement,
-- so a multi-row insert that names levels in any order (bench/seed.sql) and a
-- delete of a whole structure's levels still work. Existing rows are not
-- re-checked; every structure in the seeds and the dev data already conforms.
-- Self-nesting stays legal: a department may sit under a department.
--
-- And one name. scope_ensure_root called every new top item 'All <axis code>'
-- — "All cost_center" — and that name is what every picker prints. A new top
-- item now takes its level's name, which the seeds already write as
-- "All Partners". Existing items keep theirs; the console can rename them.

CREATE OR REPLACE FUNCTION "scope_ensure_root"(p_tenant uuid, p_axis text)
 RETURNS uuid
 LANGUAGE plpgsql
AS $storm$
DECLARE
    v_id uuid;
    v_type text;
    v_name text;
BEGIN
    SELECT id INTO v_id FROM scope_nodes
     WHERE tenant_id = p_tenant AND axis_code = p_axis AND is_axis_root;
    IF FOUND THEN RETURN v_id; END IF;

    -- The root type is the one with NO legal parents. Picking alphabetically
    -- silently produced roots typed 'department' on the org axis.
    SELECT code, display_name INTO v_type, v_name FROM scope_node_types
     WHERE axis_code = p_axis AND cardinality(parent_types) = 0
     ORDER BY code LIMIT 1;
    IF v_type IS NULL THEN
        RAISE EXCEPTION 'axis % has no root node type (none with empty parent_types)', p_axis;
    END IF;

    -- Named after its level ("All partners"), not after the axis code: the
    -- name is what every picker prints, and 'All cost_center' is not a name.
    INSERT INTO scope_nodes (tenant_id, axis_code, node_type, slug, name, is_axis_root)
         VALUES (p_tenant, p_axis, v_type, '_root', v_name, true)
      RETURNING id INTO v_id;

    INSERT INTO scope_closure (ancestor_id, descendant_id, depth)
         VALUES (v_id, v_id, 0);
    RETURN v_id;
END;
$storm$;
CREATE OR REPLACE FUNCTION "trg_scope_node_type_rules"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $storm$
DECLARE
    v_bad text;
BEGIN
    -- Levels are shared by every tenant, so these rules are about the
    -- structure's shape. No message names a count or a tenant.
    IF TG_OP = 'DELETE' THEN
        SELECT t.code INTO v_bad FROM scope_node_types t
         WHERE t.axis_code = OLD.axis_code AND OLD.code = ANY (t.parent_types)
         LIMIT 1;
        IF v_bad IS NOT NULL THEN
            RAISE EXCEPTION '"%" is still what "%" sits under', OLD.display_name,
                  (SELECT display_name FROM scope_node_types WHERE code = v_bad)
                  USING ERRCODE = 'check_violation';
        END IF;
        RETURN NULL;
    END IF;

    IF TG_OP = 'UPDATE' AND (NEW.code <> OLD.code OR NEW.axis_code <> OLD.axis_code) THEN
        RAISE EXCEPTION 'a level keeps its code and its structure; add a new level instead'
              USING ERRCODE = 'check_violation';
    END IF;

    -- A level sits under levels of its own structure, or under itself.
    SELECT p INTO v_bad FROM unnest(NEW.parent_types) AS p
     WHERE p <> NEW.code
       AND NOT EXISTS (SELECT 1 FROM scope_node_types t
                        WHERE t.code = p AND t.axis_code = NEW.axis_code)
     LIMIT 1;
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION '"%" is not a level of structure "%"', v_bad, NEW.axis_code
              USING ERRCODE = 'check_violation';
    END IF;

    -- One top level: scope_ensure_root builds every tenant's top item from
    -- it, and with two it would have to guess.
    IF cardinality(NEW.parent_types) = 0 AND EXISTS (
         SELECT 1 FROM scope_node_types t
          WHERE t.axis_code = NEW.axis_code AND t.code <> NEW.code
            AND cardinality(t.parent_types) = 0) THEN
        RAISE EXCEPTION 'this structure already has a top level; "%" has to sit under something', NEW.display_name
              USING ERRCODE = 'check_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN RETURN NULL; END IF;

    IF cardinality(OLD.parent_types) = 0 AND cardinality(NEW.parent_types) > 0 THEN
        RAISE EXCEPTION '"%" is the top of its structure and sits under nothing', NEW.display_name
              USING ERRCODE = 'check_violation';
    END IF;
    IF cardinality(OLD.parent_types) > 0 AND cardinality(NEW.parent_types) = 0 THEN
        RAISE EXCEPTION '"%" has to sit under something; only the top level sits under nothing', NEW.display_name
              USING ERRCODE = 'check_violation';
    END IF;

    -- A rule items already rely on stays. Archived items count: restoring one
    -- does not re-run the placement guard.
    SELECT p INTO v_bad FROM unnest(OLD.parent_types) AS p
     WHERE NOT (p = ANY (NEW.parent_types))
       AND EXISTS (SELECT 1 FROM scope_nodes n
                     JOIN scope_nodes up ON up.id = n.parent_id
                    WHERE n.axis_code = NEW.axis_code AND n.node_type = NEW.code
                      AND up.node_type = p)
     LIMIT 1;
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION 'some "%" items already sit under a "%"; move them before removing that rule',
              NEW.display_name, COALESCE((SELECT display_name FROM scope_node_types WHERE code = v_bad), v_bad)
              USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$storm$;
CREATE CONSTRAINT TRIGGER scope_node_types_rules AFTER INSERT OR DELETE OR UPDATE ON scope_node_types DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION trg_scope_node_type_rules();
