-- Generated by cmd/stormddl from internal/platform/schema on 2026-10-03, then
-- reordered by hand: storm does not diff primary keys, and its plan added a
-- NOT NULL tenant_id with nothing to fill it and dropped the old keys after
-- adding the new ones. The data step in the middle is hand-written.
--
-- Review before applying. The model is the source of truth; this file is
-- what runs, and what the checksum in schema_migrations pins.
--
-- CONTAINS DESTRUCTIVE STEPS — read every one before this is applied to
-- anything holding data. Each installation-wide structure and level is
-- replaced by one copy per tenant (step 3), and the function
-- trg_bump_catalog_all_tenants is dropped (step 6).

-- Each tenant owns its structures.
--
-- A structure (scope_axes) and its levels (scope_node_types) belonged to the
-- installation. Items, grants and memberships were each tenant's, but whether
-- a structure was STRICT was one row that authorize() and the gate read for
-- every tenant — so an operator assigned to one tenant could make a structure
-- strict and deny access in all the others, or reshape levels other tenants'
-- items relied on. The operator model says such an operator must not reach
-- another tenant; this is where it did.
--
-- Now both tables carry tenant_id, codes are unique within a tenant, and every
-- reference to a structure is (tenant_id, code). authorize(), its explanation,
-- the strict dry run and the gate read only the asking tenant's structures.
--
-- Existing structures and levels are COPIED into every tenant, so no tenant's
-- decisions change: each keeps every structure it could use and every
-- strictness it was subject to. A tenant created after this starts with none.

-- 1. Let go of the installation-wide keys. Everything that referenced a
--    structure or a level by its code alone.
ALTER TABLE "grant_scopes" DROP CONSTRAINT "grant_scopes_axis_code_fkey";
ALTER TABLE "membership_entry_scopes" DROP CONSTRAINT "membership_entry_scopes_axis_code_fkey";
ALTER TABLE "memberships" DROP CONSTRAINT "memberships_anchor_axis_fkey";
ALTER TABLE "scope_sync_sources" DROP CONSTRAINT "scope_sync_sources_axis_code_fkey";
ALTER TABLE "scope_nodes" DROP CONSTRAINT "scope_nodes_node_type_axis_code_fkey";
ALTER TABLE "scope_node_types" DROP CONSTRAINT "scope_node_types_axis_code_fkey";
ALTER TABLE "scope_node_types" DROP CONSTRAINT "scope_node_types_code_axis_code_key";
ALTER TABLE "scope_node_types" DROP CONSTRAINT "scope_node_types_pkey";
ALTER TABLE "scope_axes" DROP CONSTRAINT "scope_axes_pkey";
-- It bumped every tenant's catalog version per statement; step 3 would set it
-- off once per copied row's statement for nothing. Replaced in step 6.
DROP TRIGGER IF EXISTS "bump_scope_axes" ON "scope_axes";

-- 2. The column, and the rules that read it — before any row is copied, so
--    the level guard judges the copies by the tenant they belong to.
ALTER TABLE "scope_axes" ADD COLUMN "tenant_id" uuid;
ALTER TABLE "scope_node_types" ADD COLUMN "tenant_id" uuid;

CREATE OR REPLACE FUNCTION "authorize"(p_identity uuid, p_tenant uuid, p_permission text, p_targets jsonb)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $storm$
WITH targets AS MATERIALIZED (
    SELECT key AS axis_code, value::uuid AS node_id
      FROM jsonb_each_text(p_targets)
     WHERE key NOT LIKE '\_%'
),
candidates AS (
    SELECT g.id, g.self_scoped
      FROM grants g
      JOIN identities i
        ON i.id = g.identity_id AND i.tenant_id = g.tenant_id
      JOIN role_permissions_effective rpe ON rpe.role_id = g.role_id
      JOIN permissions p ON p.id = rpe.permission_id
     WHERE g.identity_id = p_identity
       AND g.tenant_id   = p_tenant
       AND g.revoked_at IS NULL
       AND g.valid_from <= now()
       AND (g.valid_until IS NULL OR g.valid_until > now())
       AND i.status = 'active'
       AND i.disabled_at IS NULL
       AND i.anonymized_at IS NULL
       AND p.tenant_id = p_tenant
       AND p.key = p_permission
       AND p.deprecated_at IS NULL
       AND p.min_assurance <= i.assurance_level
),
axis_eval AS (
    -- OR within the axis over the includes; any exclude covering the target
    -- vetoes the axis for THIS grant and no other.
    SELECT gs.grant_id, gs.axis_code,
           min(CASE WHEN NOT EXISTS (SELECT 1
                         FROM targets t
                         JOIN scope_closure c
                           ON c.descendant_id = t.node_id
                          AND c.ancestor_id   = gs.scope_node_id
                        WHERE t.axis_code = gs.axis_code
                          AND (gs.inherit OR c.depth = 0))   THEN 2
                    WHEN gs.mode = 'exclude'                 THEN 0
                    ELSE                                          1
               END) = 1 AS satisfied
      FROM grant_scopes gs JOIN candidates cd ON cd.id = gs.grant_id
     GROUP BY gs.grant_id, gs.axis_code
)
SELECT EXISTS (
    SELECT 1 FROM candidates cd
     WHERE (NOT cd.self_scoped
            OR (p_targets ? '_owner'
                AND (p_targets->>'_owner')::uuid = p_identity))
       AND NOT EXISTS (SELECT 1 FROM axis_eval ae
                        WHERE ae.grant_id = cd.id AND NOT ae.satisfied)
       AND NOT EXISTS (SELECT 1 FROM scope_axes a
                        WHERE a.tenant_id = p_tenant
                          AND a.default_effect = 'deny' AND a.status = 'active'
                          AND NOT EXISTS (SELECT 1 FROM grant_scopes gs2
                                           WHERE gs2.grant_id = cd.id
                                             AND gs2.axis_code = a.code))
);
$storm$;
CREATE OR REPLACE FUNCTION "authorize_explain"(p_identity uuid, p_tenant uuid, p_permission text, p_targets jsonb)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $storm$
WITH targets AS MATERIALIZED (
    SELECT key AS axis_code, value::uuid AS node_id
      FROM jsonb_each_text(p_targets)
     WHERE key NOT LIKE '\_%'
),
verdict AS (
    SELECT authorize(p_identity, p_tenant, p_permission, p_targets) AS allow
),
ident AS (
    SELECT i.status, i.disabled_at, i.anonymized_at, i.assurance_level
      FROM identities i
     WHERE i.id = p_identity AND i.tenant_id = p_tenant
),
perm AS (
    SELECT p.id, p.min_assurance, p.deprecated_at, p.requires_amr,
           p.max_auth_age::text AS max_auth_age, p.risk
      FROM permissions p
     WHERE p.tenant_id = p_tenant AND p.key = p_permission
),
cand AS (
    SELECT g.id, g.self_scoped, r.name AS role_name, vr.name AS via_role_name
      FROM grants g
      JOIN role_permissions_effective rpe ON rpe.role_id = g.role_id
      JOIN perm p  ON p.id = rpe.permission_id
      JOIN roles r  ON r.id = g.role_id
      JOIN roles vr ON vr.id = rpe.via_role_id
     WHERE g.identity_id = p_identity
       AND g.tenant_id   = p_tenant
       AND g.revoked_at IS NULL
       AND g.valid_from <= now()
       AND (g.valid_until IS NULL OR g.valid_until > now())
),
axis_probe AS (
    SELECT gs.grant_id, gs.axis_code, gs.mode, gs.inherit,
           gs.scope_node_id, sn.name AS node_name,
           EXISTS (SELECT 1
                     FROM targets t
                     JOIN scope_closure c
                       ON c.descendant_id = t.node_id
                      AND c.ancestor_id   = gs.scope_node_id
                    WHERE t.axis_code = gs.axis_code
                      AND (gs.inherit OR c.depth = 0)) AS covers
      FROM grant_scopes gs
      JOIN cand cd ON cd.id = gs.grant_id
      JOIN scope_nodes sn ON sn.id = gs.scope_node_id
),
axis_eval AS (
    SELECT grant_id, axis_code,
           bool_or(mode = 'include' AND covers) AS included,
           bool_or(mode = 'exclude' AND covers) AS excluded,
           bool_or(mode = 'include' AND covers)
             AND NOT bool_or(mode = 'exclude' AND covers) AS satisfied,
           jsonb_agg(jsonb_build_object(
               'node_id', scope_node_id,
               'node',    node_name,
               'inherit', inherit,
               'mode',    mode) ORDER BY mode DESC, node_name) AS nodes
      FROM axis_probe
     GROUP BY grant_id, axis_code
),
strict_axes AS (
    SELECT code, sort_order FROM scope_axes
     WHERE tenant_id = p_tenant AND default_effect = 'deny' AND status = 'active'
),
per_grant AS (
    SELECT cd.id, cd.self_scoped, cd.role_name, cd.via_role_name,
           (NOT cd.self_scoped
            OR (p_targets ? '_owner'
                AND (p_targets->>'_owner')::uuid = p_identity)) AS self_ok,
           NOT EXISTS (SELECT 1 FROM axis_eval ae
                        WHERE ae.grant_id = cd.id AND NOT ae.satisfied) AS axes_ok,
           COALESCE((SELECT jsonb_agg(jsonb_build_object(
                         'axis', ae.axis_code,
                         'satisfied', ae.satisfied,
                         'included', ae.included,
                         'excluded', ae.excluded,
                         'nodes', ae.nodes) ORDER BY ae.axis_code)
                       FROM axis_eval ae WHERE ae.grant_id = cd.id),
                    '[]'::jsonb) AS axes,
           COALESCE((SELECT jsonb_agg(sa.code ORDER BY sa.sort_order, sa.code)
                       FROM strict_axes sa
                      WHERE NOT EXISTS (SELECT 1 FROM grant_scopes gs2
                                         WHERE gs2.grant_id = cd.id
                                           AND gs2.axis_code = sa.code)),
                    '[]'::jsonb) AS strict_missing
      FROM cand cd
),
gates AS (
    SELECT EXISTS (SELECT 1 FROM ident) AS identity_found,
           COALESCE((SELECT status = 'active'
                        AND disabled_at IS NULL
                        AND anonymized_at IS NULL FROM ident), false) AS identity_ok,
           EXISTS (SELECT 1 FROM perm) AS permission_found,
           COALESCE((SELECT deprecated_at IS NULL FROM perm), false) AS permission_live,
           COALESCE((SELECT p.min_assurance <= i.assurance_level
                       FROM perm p, ident i), false) AS assurance_ok
)
SELECT jsonb_build_object(
    'allow', (SELECT allow FROM verdict),
    'identity', (SELECT jsonb_build_object(
        'found', identity_found, 'active', identity_ok,
        'assurance_ok', assurance_ok,
        'assurance_level', (SELECT assurance_level FROM ident)) FROM gates),
    'permission', jsonb_build_object(
        'found', (SELECT permission_found FROM gates),
        'live',  (SELECT permission_live  FROM gates),
        'risk',          (SELECT risk FROM perm),
        'min_assurance', (SELECT min_assurance FROM perm),
        'requires_amr',  (SELECT to_jsonb(requires_amr) FROM perm),
        'max_auth_age',  (SELECT max_auth_age FROM perm)),
    'grants', COALESCE((SELECT jsonb_agg(jsonb_build_object(
        'grant_id',       pg.id,
        'role',           pg.role_name,
        'via_role',       pg.via_role_name,
        'self_scoped',    pg.self_scoped,
        'self_ok',        pg.self_ok,
        'axes',           pg.axes,
        'axes_ok',        pg.axes_ok,
        'strict_missing', pg.strict_missing,
        'allowed', (pg.self_ok AND pg.axes_ok
                    AND pg.strict_missing = '[]'::jsonb))
        ORDER BY pg.role_name) FROM per_grant pg), '[]'::jsonb),
    'reason', CASE
        WHEN (SELECT allow FROM verdict) THEN NULL
        WHEN NOT (SELECT identity_found FROM gates) THEN 'identity_not_found'
        WHEN NOT (SELECT identity_ok    FROM gates) THEN 'identity_inactive'
        WHEN NOT (SELECT permission_found AND permission_live FROM gates)
             THEN 'permission_unknown'
        WHEN NOT EXISTS (SELECT 1 FROM cand) THEN 'permission_not_held'
        WHEN NOT (SELECT assurance_ok FROM gates) THEN 'insufficient_assurance'
        WHEN EXISTS (SELECT 1 FROM per_grant WHERE NOT self_ok)
             AND NOT EXISTS (SELECT 1 FROM per_grant WHERE self_ok)
             THEN 'self_scope_required'
        WHEN EXISTS (SELECT 1 FROM per_grant pg
                      WHERE pg.self_ok AND pg.axes_ok
                        AND pg.strict_missing <> '[]'::jsonb)
             THEN 'axis_unresolved'
        -- An exclusion only EXPLAINS the denial where it decided it: the
        -- include reached the target and the exclude took it back. Where
        -- nothing included the target the grant was never going to allow,
        -- and calling that an exclusion would send an operator to edit the
        -- wrong half of the grant.
        WHEN EXISTS (SELECT 1 FROM axis_eval ae
                      WHERE ae.included AND ae.excluded)
             THEN 'scope_excluded'
        ELSE 'scope_mismatch' END,
    'failing_axis', CASE WHEN (SELECT allow FROM verdict) THEN NULL ELSE
        (SELECT ae.axis_code
           FROM axis_eval ae
           JOIN scope_axes a ON a.tenant_id = p_tenant AND a.code = ae.axis_code
          WHERE NOT ae.satisfied
          ORDER BY a.sort_order, ae.axis_code
          LIMIT 1) END
);
$storm$;
CREATE OR REPLACE FUNCTION "scope_ensure_root"(p_tenant uuid, p_axis text)
 RETURNS uuid
 LANGUAGE plpgsql
AS $storm$
DECLARE
    v_id uuid;
    v_type text;
    v_name text;
BEGIN
    SELECT id INTO v_id FROM scope_nodes
     WHERE tenant_id = p_tenant AND axis_code = p_axis AND is_axis_root;
    IF FOUND THEN RETURN v_id; END IF;

    -- The root type is the one with NO legal parents. Picking alphabetically
    -- silently produced roots typed 'department' on the org axis.
    SELECT code, display_name INTO v_type, v_name FROM scope_node_types
     WHERE tenant_id = p_tenant AND axis_code = p_axis AND cardinality(parent_types) = 0
     ORDER BY code LIMIT 1;
    IF v_type IS NULL THEN
        RAISE EXCEPTION 'axis % has no root node type (none with empty parent_types)', p_axis;
    END IF;

    -- Named after its level ("All partners"), not after the axis code: the
    -- name is what every picker prints, and 'All cost_center' is not a name.
    INSERT INTO scope_nodes (tenant_id, axis_code, node_type, slug, name, is_axis_root)
         VALUES (p_tenant, p_axis, v_type, '_root', v_name, true)
      RETURNING id INTO v_id;

    INSERT INTO scope_closure (ancestor_id, descendant_id, depth)
         VALUES (v_id, v_id, 0);
    RETURN v_id;
END;
$storm$;
CREATE OR REPLACE FUNCTION "trg_scope_node_type_guard"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $storm$
DECLARE
    v_parent_type text;
    v_legal       text[];
BEGIN
    -- Roots are covered by the existing CHECK pair (root ⇔ no parent).
    IF NEW.parent_id IS NULL THEN RETURN NEW; END IF;

    SELECT node_type INTO v_parent_type FROM scope_nodes WHERE id = NEW.parent_id;
    SELECT parent_types INTO v_legal FROM scope_node_types
     WHERE tenant_id = NEW.tenant_id AND code = NEW.node_type AND axis_code = NEW.axis_code;

    IF NOT (v_parent_type = ANY (v_legal)) THEN
        RAISE EXCEPTION
          'a "%" may not sit under a "%" (legal parents: %)',
          NEW.node_type, v_parent_type, array_to_string(v_legal, ', ')
          USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$storm$;
CREATE OR REPLACE FUNCTION "trg_scope_node_type_rules"()
 RETURNS trigger
 LANGUAGE plpgsql
AS $storm$
DECLARE
    v_bad text;
BEGIN
    -- Every lookup stays inside the level's own tenant (0056): levels are a
    -- tenant's, and so are the items that rely on them.
    IF TG_OP = 'DELETE' THEN
        SELECT t.code INTO v_bad FROM scope_node_types t
         WHERE t.tenant_id = OLD.tenant_id AND t.axis_code = OLD.axis_code
           AND OLD.code = ANY (t.parent_types)
         LIMIT 1;
        IF v_bad IS NOT NULL THEN
            RAISE EXCEPTION '"%" is still what "%" sits under', OLD.display_name,
                  (SELECT display_name FROM scope_node_types
                    WHERE tenant_id = OLD.tenant_id AND code = v_bad)
                  USING ERRCODE = 'check_violation';
        END IF;
        RETURN NULL;
    END IF;

    IF TG_OP = 'UPDATE' AND (NEW.code <> OLD.code OR NEW.axis_code <> OLD.axis_code
                             OR NEW.tenant_id <> OLD.tenant_id) THEN
        RAISE EXCEPTION 'a level keeps its code and its structure; add a new level instead'
              USING ERRCODE = 'check_violation';
    END IF;

    -- A level sits under levels of its own structure, or under itself.
    SELECT p INTO v_bad FROM unnest(NEW.parent_types) AS p
     WHERE p <> NEW.code
       AND NOT EXISTS (SELECT 1 FROM scope_node_types t
                        WHERE t.tenant_id = NEW.tenant_id AND t.code = p
                          AND t.axis_code = NEW.axis_code)
     LIMIT 1;
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION '"%" is not a level of structure "%"', v_bad, NEW.axis_code
              USING ERRCODE = 'check_violation';
    END IF;

    -- One top level: scope_ensure_root builds the tenant's top item from it,
    -- and with two it would have to guess.
    IF cardinality(NEW.parent_types) = 0 AND EXISTS (
         SELECT 1 FROM scope_node_types t
          WHERE t.tenant_id = NEW.tenant_id AND t.axis_code = NEW.axis_code
            AND t.code <> NEW.code
            AND cardinality(t.parent_types) = 0) THEN
        RAISE EXCEPTION 'this structure already has a top level; "%" has to sit under something', NEW.display_name
              USING ERRCODE = 'check_violation';
    END IF;

    IF TG_OP = 'INSERT' THEN RETURN NULL; END IF;

    IF cardinality(OLD.parent_types) = 0 AND cardinality(NEW.parent_types) > 0 THEN
        RAISE EXCEPTION '"%" is the top of its structure and sits under nothing', NEW.display_name
              USING ERRCODE = 'check_violation';
    END IF;
    IF cardinality(OLD.parent_types) > 0 AND cardinality(NEW.parent_types) = 0 THEN
        RAISE EXCEPTION '"%" has to sit under something; only the top level sits under nothing', NEW.display_name
              USING ERRCODE = 'check_violation';
    END IF;

    -- A rule items already rely on stays. Archived items count: restoring one
    -- does not re-run the placement guard.
    SELECT p INTO v_bad FROM unnest(OLD.parent_types) AS p
     WHERE NOT (p = ANY (NEW.parent_types))
       AND EXISTS (SELECT 1 FROM scope_nodes n
                     JOIN scope_nodes up ON up.id = n.parent_id
                    WHERE n.tenant_id = NEW.tenant_id AND n.axis_code = NEW.axis_code
                      AND n.node_type = NEW.code
                      AND up.node_type = p)
     LIMIT 1;
    IF v_bad IS NOT NULL THEN
        RAISE EXCEPTION 'some "%" items already sit under a "%"; move them before removing that rule',
              NEW.display_name, COALESCE((SELECT display_name FROM scope_node_types
                                           WHERE tenant_id = NEW.tenant_id AND code = v_bad), v_bad)
              USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$storm$;

-- 3. One copy per tenant, then the installation-wide originals go.
INSERT INTO "scope_axes" (tenant_id, code, display_name, default_effect, status,
                          sort_order, resolution, ui_schema, created_at)
SELECT t.id, a.code, a.display_name, a.default_effect, a.status,
       a.sort_order, a.resolution, a.ui_schema, a.created_at
  FROM "scope_axes" a CROSS JOIN "tenants" t
 WHERE a.tenant_id IS NULL;
INSERT INTO "scope_node_types" (tenant_id, code, axis_code, display_name, parent_types)
SELECT t.id, n.code, n.axis_code, n.display_name, n.parent_types
  FROM "scope_node_types" n CROSS JOIN "tenants" t
 WHERE n.tenant_id IS NULL;
DELETE FROM "scope_node_types" WHERE tenant_id IS NULL;
DELETE FROM "scope_axes" WHERE tenant_id IS NULL;

-- 4. The tenant's keys.
ALTER TABLE "scope_axes" ALTER COLUMN "tenant_id" SET NOT NULL;
ALTER TABLE "scope_axes" ADD CONSTRAINT "scope_axes_pkey" PRIMARY KEY ("tenant_id", "code");
ALTER TABLE "scope_axes" ADD CONSTRAINT "scope_axes_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON DELETE CASCADE;
ALTER TABLE "scope_node_types" ALTER COLUMN "tenant_id" SET NOT NULL;
ALTER TABLE "scope_node_types" ADD CONSTRAINT "scope_node_types_pkey" PRIMARY KEY ("tenant_id", "code");
ALTER TABLE "scope_node_types" ADD CONSTRAINT "scope_node_types_tenant_id_code_axis_code_key" UNIQUE ("tenant_id", "code", "axis_code");
ALTER TABLE "scope_node_types" ADD CONSTRAINT "scope_node_types_tenant_id_axis_code_fkey" FOREIGN KEY ("tenant_id", "axis_code") REFERENCES "scope_axes" ("tenant_id", "code") ON DELETE RESTRICT;

-- 5. Every reference, by (tenant_id, code). A grant, a membership or a sync
--    source can now only name a structure of its own tenant.
ALTER TABLE "grant_scopes" ADD CONSTRAINT "grant_scopes_tenant_id_axis_code_fkey" FOREIGN KEY ("tenant_id", "axis_code") REFERENCES "scope_axes" ("tenant_id", "code") ON DELETE RESTRICT;
ALTER TABLE "membership_entry_scopes" ADD CONSTRAINT "membership_entry_scopes_tenant_id_axis_code_fkey" FOREIGN KEY ("tenant_id", "axis_code") REFERENCES "scope_axes" ("tenant_id", "code") ON DELETE RESTRICT;
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_tenant_id_anchor_axis_fkey" FOREIGN KEY ("tenant_id", "anchor_axis") REFERENCES "scope_axes" ("tenant_id", "code") ON DELETE RESTRICT;
ALTER TABLE "scope_sync_sources" ADD CONSTRAINT "scope_sync_sources_tenant_id_axis_code_fkey" FOREIGN KEY ("tenant_id", "axis_code") REFERENCES "scope_axes" ("tenant_id", "code") ON DELETE CASCADE;
ALTER TABLE "scope_nodes" ADD CONSTRAINT "scope_nodes_tenant_id_node_type_axis_code_fkey" FOREIGN KEY ("tenant_id", "node_type", "axis_code") REFERENCES "scope_node_types" ("tenant_id", "code", "axis_code") ON DELETE RESTRICT;

-- 6. A change to a tenant's structures invalidates that tenant's cached
--    decisions, and no one else's.
CREATE TRIGGER scope_axes_bump_del AFTER DELETE ON scope_axes REFERENCING OLD TABLE AS oldtab FOR EACH STATEMENT EXECUTE FUNCTION trg_bump_catalog_stmt();
CREATE TRIGGER scope_axes_bump_ins AFTER INSERT ON scope_axes REFERENCING NEW TABLE AS newtab FOR EACH STATEMENT EXECUTE FUNCTION trg_bump_catalog_stmt();
CREATE TRIGGER scope_axes_bump_upd AFTER UPDATE ON scope_axes REFERENCING NEW TABLE AS newtab FOR EACH STATEMENT EXECUTE FUNCTION trg_bump_catalog_stmt();
DROP FUNCTION "trg_bump_catalog_all_tenants"();
-- Every gate snapshot reloads once, now reading its own tenant's structures.
SELECT bump_catalog_version(id) FROM "tenants";

-- 7. Both tables were rewritten above. Without fresh statistics the planner
--    meets the decision path's strict-structure probe with the old row
--    counts; measured right after this step, authorize() p95 sat at 5–6 ms
--    until the next autovacuum. ANALYZE is allowed inside the migration's
--    transaction; VACUUM is not.
ANALYZE "scope_axes";
ANALYZE "scope_node_types";
