// Code generated by storm (devel). DO NOT EDIT.
// source: table scope_axes

package scopeaxis

import (
	"context"
	"errors"
	"net/netip"
	"time"

	"github.com/gsoultan/storm/runtime"
)

var (
	_ = time.Time{}
	_ = netip.Prefix{}
)

// Row is what a full read returns: the model struct with relations
// replaced by their scalar foreign keys and *T rewritten to Null[T].
type Row struct {
	CreatedAt     time.Time
	SortOrder     int32
	Code          string
	DisplayName   string
	DefaultEffect string
	Status        string
	Resolution    runtime.JSON
	UiSchema      runtime.JSON
}

// Operator ids. Argument-taking operators are numbered first, so the
// bind loop tests `op-1 < opsWithArg` with one unsigned compare.
const (
	opEq               runtime.Op = 1
	opNotEq            runtime.Op = 2
	opGt               runtime.Op = 3
	opGte              runtime.Op = 4
	opLt               runtime.Op = 5
	opLte              runtime.Op = 6
	opLike             runtime.Op = 7
	opILike            runtime.Op = 8
	opMatches          runtime.Op = 9
	opWebSearch        runtime.Op = 10
	opOverlaps         runtime.Op = 11
	opContainsRange    runtime.Op = 12
	opContainedBy      runtime.Op = 13
	opIn               runtime.Op = 14
	opNotIn            runtime.Op = 15
	opArrayContains    runtime.Op = 16
	opArrayContainedBy runtime.Op = 17
	opArrayOverlaps    runtime.Op = 18
	opJSONContains     runtime.Op = 19
	opJSONContainedBy  runtime.Op = 20
	opHasAnyKey        runtime.Op = 21
	opHasAllKeys       runtime.Op = 22
	opIsNull           runtime.Op = 23
	opIsNotNull        runtime.Op = 24
	// Existence operators apply to PSEUDO-COLUMNS — relation slots past
	// the real columns in the frag table. Argless, like IsNull: the
	// fragment is constant, which is what lets a semi-join ride the
	// ordinary predicate machinery and compose under And/Or/Not free.
	opExists    runtime.Op = 25
	opNotExists runtime.Op = 26
)

const nCols = 8

// Query is a value type: composing one allocates nothing. Predicates
// are a postfix token stream, so disjunction and negation are
// representable — a per-column operator mask cannot express either.
type Query struct {
	toks [16]runtime.Tok
	nt   uint8
	top  uint8 // top-level conjuncts, ANDed at compile time

	strs             [6]string
	nums             [6]int64
	tims             [4]time.Time
	jsns             [2]runtime.JSON
	ns, nn, ntm, njs uint8

	anyStr     [3][]string
	anyI32     [3][]int32
	nas, nai32 uint8

	// Order terms live in their own buffer and are appended to the stream
	// after the predicate tree. Sharing one buffer would let a Where after
	// an Order interleave the two, and the stream's order is its meaning.
	otoks [4]runtime.Tok
	no    uint8

	// lock is the row-lock mode: 0 none, then the dialect's mode order.
	// It is part of the STATEMENT, so it selects the cache as well as
	// the suffix.
	lock uint8

	limit  int64
	offset int64
	// over records that the query outgrew its fixed buffers. Terminals
	// return it as an error rather than silently dropping a predicate.
	over bool

	// mixed records an After() over an ordering that is not all in one
	// direction. No single row comparison expresses that.
	mixed bool

	// noOrder suppresses the default ordering. See Unordered.
	noOrder  bool
	badAfter bool
}

// New starts a query.
func New() Query { return Query{limit: 1000} }

// Limit caps the result set.
func (q Query) Limit(n int64) Query { q.limit = n; return q }

// Offset skips rows.
//
// It is here because callers expect it, not because it is a good idea: the
// database still walks and discards every skipped row, so page 5,000 costs
// 5,000 pages of work, and a row inserted mid-scroll shifts every later
// page. Order by a unique key and filter past the last one you saw instead.
func (q Query) Offset(n int64) Query { q.offset = n; return q }

// After filters past a row already seen: keyset pagination.
//
// The comparison follows the ACTIVE ordering, because it has to. Paging
// `ORDER BY email DESC` with `> $1` walks away from the rows you have
// not seen yet, and silently returns a wrong page rather than an error.
// So After reads the ordering off the query and builds the matching row
// comparison: (a, b) > ($1, $2) for ascending, < for descending.
//
// Unlike Offset the database does not walk the skipped rows — the
// comparison seeks straight into the index — and a row inserted
// mid-scroll cannot shift a page, because the cursor is a position in the
// data rather than a count.
//
// Mixing ascending and descending terms in one ordering is a query error:
// no single row comparison expresses it, and expanding it into ORs would
// silently give up the index walk that makes this worth doing.
func (q Query) After(r Row) Query {
	terms := q.otoks[:q.no]
	if q.no == 0 {
		if q.noOrder {
			// A keyset cursor without an order is a position in nothing.
			q.badAfter = true
			return q
		}
		terms = defaultOrder[:]
	}
	if len(terms) == 0 {
		return q
	}
	desc := terms[0].Op() == runtime.Desc || terms[0].Op() == runtime.DescNullsLast
	for _, t := range terms {
		d := t.Op() == runtime.Desc || t.Op() == runtime.DescNullsLast
		if d != desc {
			q.mixed = true
			return q
		}
	}
	for _, t := range terms {
		q.push(runtime.MakeCol(t.Col()))
		q.cursor(t.Col(), r)
	}
	op := runtime.CmpGt
	if desc {
		op = runtime.CmpLt
	}
	q.push(runtime.MakeRowCmp(op, uint32(len(terms))))
	q.top++
	return q
}

// cursor stores the bound value for one column of a keyset comparison.
func (q *Query) cursor(col uint32, r Row) {
	switch col {
	case 0:
		if int(q.ntm) >= len(q.tims) {
			q.over = true
			return
		}
		q.tims[q.ntm] = r.CreatedAt
		q.ntm++
	case 1:
		if int(q.nn) >= len(q.nums) {
			q.over = true
			return
		}
		q.nums[q.nn] = int64(r.SortOrder)
		q.nn++
	case 2:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.Code
		q.ns++
	case 3:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.DisplayName
		q.ns++
	case 4:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.DefaultEffect
		q.ns++
	case 5:
		if int(q.ns) >= len(q.strs) {
			q.over = true
			return
		}
		q.strs[q.ns] = r.Status
		q.ns++
	}
}

// Unordered drops the default ordering, for results consumed in an
// order-independent way — a batch loader that buckets rows into a map,
// an aggregation, a bulk export.
//
// The default exists because paging an unordered read is a bug; the
// escape exists because ordering a read NOBODY PAGES is a server-side
// sort for free. Measured on a 50k-row relation load: an external merge
// sort spilling 5MB to disk, for an order the loader's map bucketing
// destroyed on arrival. An explicit Order() still applies; After() on an
// unordered query with no explicit order is an error, because a keyset
// cursor without an order is a position in nothing.
func (q Query) Unordered() Query { q.noOrder = true; return q }

// Row locking.
//
// A lock is held to the end of the TRANSACTION, so one taken outside a
// transaction is released before the next statement runs and protects
// nothing — pass a pgxdrv.Tx, not a pool.
//
// Locking is refused on Count and Exists, and on the declared
// aggregations and joins. The server rejects a row lock combined with an
// aggregate, a grouping, a DISTINCT or a set operation, and on the
// nullable side of an outer join; refusing at the call site names the
// rule, where the server would name a SQLSTATE.
//
// The two weakest strengths are deliberately absent. They exist for the
// deadlock between updating a parent row and inserting a child that
// references it, which is real and rare, and a caller who has it knows
// the exact SQL they want — storm.SQL gives it to them typed.

// ForUpdate locks the rows this query returns, and takes the strongest row lock, waiting for anyone who already holds it.
func (q Query) ForUpdate() Query { q.lock = 1; return q }

// ForUpdateNoWait locks the rows this query returns, and fails immediately rather than wait for a lock someone else holds.
func (q Query) ForUpdateNoWait() Query { q.lock = 2; return q }

// ForUpdateSkipLocked locks the rows this query returns, and steps over the rows another transaction has locked. This is the queue claim, and the one form that returns FEWER rows than Limit asks for: that is the point of it, not a fault.
func (q Query) ForUpdateSkipLocked() Query { q.lock = 3; return q }

// ForShare locks the rows this query returns, and blocks writers while letting other readers share the lock.
func (q Query) ForShare() Query { q.lock = 4; return q }

// ForShareNoWait locks the rows this query returns, and is the shared lock, failing rather than waiting.
func (q Query) ForShareNoWait() Query { q.lock = 5; return q }

// ForShareSkipLocked locks the rows this query returns, and is the shared lock, stepping over rows another transaction holds.
func (q Query) ForShareSkipLocked() Query { q.lock = 6; return q }

// Sort is one ORDER BY term, produced by a column handle: Email.Asc().
type Sort runtime.Tok

// Order replaces the ordering. Passing none restores the default.
//
// An ordering is part of a statement's identity, not a decoration on it:
// two queries differing only in ORDER BY are different statements, so the
// terms join the token stream that keys the compiled-statement cache.
func (q Query) Order(ts ...Sort) Query {
	q.no = 0
	for _, t := range ts {
		if int(q.no) >= len(q.otoks) {
			q.over = true
			return q
		}
		q.otoks[q.no] = runtime.Tok(t)
		q.no++
	}
	return q
}

// Err reports a query that outgrew its buffers.
func (q Query) Err() error {
	if q.over {
		return errTooComplex
	}
	if q.mixed {
		return errMixedOrder
	}
	if q.badAfter {
		return errAfterUnordered
	}
	return nil
}

var errAfterUnordered = errors.New(
	"storm: After() on an Unordered() query with no explicit Order — a keyset cursor without an ordering is a position in nothing")

var errMixedOrder = errors.New(
	"storm: After() needs every ORDER BY term in the same direction; a mixed ordering has no single row comparison, and expanding it into ORs gives up the index walk that makes keyset pagination worth doing")

var errCountLocked = errors.New(
	"storm: a locked read cannot be counted — the server refuses a row lock with an aggregate; count first, then lock the rows you take")

var errExistsLocked = errors.New(
	"storm: a locked read cannot be an existence probe — locking a row to answer a boolean is a row nobody reads; use One() with the same lock")

var errTooComplex = errors.New(
	"storm: query has more predicates than the generated buffers hold (scale 1); split the query, or regenerate with a larger codegen.Budgets{Scale}")

// push and leaf mutate through a pointer so the builder loop does not
// copy the whole Query twice per predicate. They are only ever called on
// a local, so the public API keeps value semantics: q2 := q1.Where(x)
// must not mutate q1.
func (q *Query) push(t runtime.Tok) {
	if int(q.nt) >= len(q.toks) {
		q.over = true
		return
	}
	q.toks[q.nt] = t
	q.nt++
}

// preds returns the predicate stream with top-level conjuncts ANDed.
// A count uses this: ordering a scalar is wasted work, and including the
// terms would compile a second statement per ordering for no difference.
func (q Query) preds(buf *[21]runtime.Tok) []runtime.Tok {
	n := copy(buf[:], q.toks[:q.nt])
	if q.top > 1 {
		buf[n] = runtime.MakeGroup(runtime.KAnd, uint32(q.top))
		n++
	}
	return buf[:n]
}

// stream is the predicates followed by the ordering — the whole statement
// key. Order tokens go last so a splicer can find the boundary by kind.
func (q Query) stream(buf *[21]runtime.Tok) []runtime.Tok {
	n := len(q.preds(buf))
	if q.no == 0 {
		if q.noOrder {
			return buf[:n]
		}
		n += copy(buf[n:], defaultOrder[:])
		return buf[:n]
	}
	n += copy(buf[n:], q.otoks[:q.no])
	return buf[:n]
}

// Pred is one predicate, produced by a typed column handle. A value with
// a small union payload: no interface, nothing to allocate. Structure is
// assembled by Query into a token stream — see Where/Any/Not.
type Pred struct {
	col    uint8
	op     runtime.Op
	num    int64
	str    string
	tim    time.Time
	jsn    runtime.JSON
	anyStr []string
	anyI32 []int32
}

// Typed column handles. The type of the handle is what makes
// Age.Like(...) fail to compile.
var (
	CreatedAt     = TimeCol{0}
	SortOrder     = Int32Col{1}
	Code          = TextCol{2}
	DisplayName   = TextCol{3}
	DefaultEffect = TextCol{4}
	Status        = TextCol{5}
	Resolution    = JSONCol{6}
	UiSchema      = JSONCol{7}
)

// TimeCol addresses a timestamptz column.
type TimeCol struct{ c uint8 }

func (h TimeCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TimeCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TimeCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TimeCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h TimeCol) Eq(v time.Time) Pred    { return Pred{col: h.c, op: opEq, tim: v} }
func (h TimeCol) NotEq(v time.Time) Pred { return Pred{col: h.c, op: opNotEq, tim: v} }
func (h TimeCol) Gt(v time.Time) Pred    { return Pred{col: h.c, op: opGt, tim: v} }
func (h TimeCol) Gte(v time.Time) Pred   { return Pred{col: h.c, op: opGte, tim: v} }
func (h TimeCol) Lt(v time.Time) Pred    { return Pred{col: h.c, op: opLt, tim: v} }
func (h TimeCol) Lte(v time.Time) Pred   { return Pred{col: h.c, op: opLte, tim: v} }

// Int32Col addresses a int4 column.
type Int32Col struct{ c uint8 }

func (h Int32Col) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h Int32Col) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h Int32Col) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h Int32Col) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h Int32Col) Eq(v int32) Pred    { return Pred{col: h.c, op: opEq, num: int64(v)} }
func (h Int32Col) NotEq(v int32) Pred { return Pred{col: h.c, op: opNotEq, num: int64(v)} }
func (h Int32Col) Gt(v int32) Pred    { return Pred{col: h.c, op: opGt, num: int64(v)} }
func (h Int32Col) Gte(v int32) Pred   { return Pred{col: h.c, op: opGte, num: int64(v)} }
func (h Int32Col) Lt(v int32) Pred    { return Pred{col: h.c, op: opLt, num: int64(v)} }
func (h Int32Col) Lte(v int32) Pred   { return Pred{col: h.c, op: opLte, num: int64(v)} }
func (h Int32Col) In(v ...int32) Pred { return Pred{col: h.c, op: opIn, anyI32: v} }

// NotIn is `<> ALL($1)`. A NULL anywhere in v makes the
// comparison NULL for every row and the result empty —
// PostgreSQL's rule for NOT IN, not storm's.
func (h Int32Col) NotIn(v ...int32) Pred { return Pred{col: h.c, op: opNotIn, anyI32: v} }

// TextCol addresses a text column.
type TextCol struct{ c uint8 }

func (h TextCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h TextCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h TextCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h TextCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h TextCol) Eq(v string) Pred    { return Pred{col: h.c, op: opEq, str: v} }
func (h TextCol) NotEq(v string) Pred { return Pred{col: h.c, op: opNotEq, str: v} }
func (h TextCol) Gt(v string) Pred    { return Pred{col: h.c, op: opGt, str: v} }
func (h TextCol) Gte(v string) Pred   { return Pred{col: h.c, op: opGte, str: v} }
func (h TextCol) Lt(v string) Pred    { return Pred{col: h.c, op: opLt, str: v} }
func (h TextCol) Lte(v string) Pred   { return Pred{col: h.c, op: opLte, str: v} }
func (h TextCol) Like(v string) Pred  { return Pred{col: h.c, op: opLike, str: v} }
func (h TextCol) ILike(v string) Pred { return Pred{col: h.c, op: opILike, str: v} }
func (h TextCol) In(v ...string) Pred { return Pred{col: h.c, op: opIn, anyStr: v} }

// NotIn is `<> ALL($1)`. A NULL anywhere in v makes the
// comparison NULL for every row and the result empty —
// PostgreSQL's rule for NOT IN, not storm's.
func (h TextCol) NotIn(v ...string) Pred { return Pred{col: h.c, op: opNotIn, anyStr: v} }

// JSONCol addresses a jsonb column.
type JSONCol struct{ c uint8 }

func (h JSONCol) Asc() Sort  { return Sort(runtime.MakeOrder(runtime.Asc, uint32(h.c))) }
func (h JSONCol) Desc() Sort { return Sort(runtime.MakeOrder(runtime.Desc, uint32(h.c))) }
func (h JSONCol) AscNullsFirst() Sort {
	return Sort(runtime.MakeOrder(runtime.AscNullsFirst, uint32(h.c)))
}
func (h JSONCol) DescNullsLast() Sort {
	return Sort(runtime.MakeOrder(runtime.DescNullsLast, uint32(h.c)))
}

func (h JSONCol) Contains(v runtime.JSON) Pred { return Pred{col: h.c, op: opJSONContains, jsn: v} }
func (h JSONCol) ContainedBy(v runtime.JSON) Pred {
	return Pred{col: h.c, op: opJSONContainedBy, jsn: v}
}
func (h JSONCol) HasAnyKey(v ...string) Pred  { return Pred{col: h.c, op: opHasAnyKey, anyStr: v} }
func (h JSONCol) HasAllKeys(v ...string) Pred { return Pred{col: h.c, op: opHasAllKeys, anyStr: v} }

// Where applies predicates, ANDed together.
func (q Query) Where(ps ...Pred) Query {
	for i := range ps {
		q.leaf(ps[i])
		q.top++
	}
	return q
}

// WhenSet applies f(*v) only when v is non-nil — the optional-filter
// idiom without an if, and without the nil dereference WhereIf invites.
//
//	q = user.WhenSet(q, f.MinAge, user.Age.Gte)
//
// WhereIf takes an already-built Pred, so the caller has to evaluate
// user.Age.Gte(*f.MinAge) BEFORE the condition is tested — which panics
// on exactly the nil the condition was checking for. This takes the
// constructor instead, so nothing is dereferenced unless it is there.
//
// It still sets exactly one bit in the shape mask: a filter that is
// absent is a different SHAPE, compiled once, not a different value.
func WhenSet[T any](q Query, v *T, f func(T) Pred) Query {
	if v == nil {
		return q
	}
	return q.Where(f(*v))
}

// WhereIf applies a predicate only when cond holds.
func (q Query) WhereIf(cond bool, p Pred) Query {
	if !cond {
		return q
	}
	return q.Where(p)
}

// Any ORs its arguments and ANDs the group with the rest of the query:
// Where(a).Any(b, c) is a AND (b OR c).
func (q Query) Any(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.top++
	return q
}

// Not negates one predicate and ANDs it with the rest.
func (q Query) Not(p Pred) Query {
	q.leaf(p)
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// NotAny negates a disjunction: NOT (a OR b).
func (q Query) NotAny(ps ...Pred) Query {
	if len(ps) == 0 {
		return q
	}
	for i := range ps {
		q.leaf(ps[i])
	}
	q.push(runtime.MakeGroup(runtime.KOr, uint32(len(ps))))
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	q.top++
	return q
}

// Grp is one conjunction, built by And, that AnyOf ORs with the others.
//
// It holds the predicates rather than tokens because the ARENA a value
// lands in is chosen by leaf, in stream order, and a group has no stream
// position until AnyOf gives it one.
type Grp struct{ ps []Pred }

// And groups predicates into one conjunction, so AnyOf can OR whole
// conjunctions rather than single predicates:
//
//	q.AnyOf(And(Status.Eq("paid"), Total.Gt(big)),
//	        And(Status.Eq("trial"), Total.Gt(small)))
//
// is (status = $1 AND total > $2) OR (status = $3 AND total > $4). Any
// ORs single predicates and cannot say this: an advanced-search screen
// whose rows are each a field, an operator and a value produces exactly
// this shape, and without it the query has to be written in SQL.
//
// The variadic slice does not escape — AnyOf reads it and returns — so a
// warm call still builds its SQL without allocating.
func And(ps ...Pred) Grp { return Grp{ps: ps} }

// AnyOf ORs its groups and ANDs the result with the rest of the query.
//
// An empty group contributes nothing, so a screen that builds one group
// per filled-in filter row needs no special case for the rows the user
// left blank. A group of one predicate is that predicate: the SQL carries
// no parentheses it did not need, which keeps the statement — and so the
// shape it is cached under — the same as the equivalent Any.
func (q Query) AnyOf(gs ...Grp) Query {
	n := uint32(0)
	for i := range gs {
		if len(gs[i].ps) == 0 {
			continue
		}
		for j := range gs[i].ps {
			q.leaf(gs[i].ps[j])
		}
		if len(gs[i].ps) > 1 {
			q.push(runtime.MakeGroup(runtime.KAnd, uint32(len(gs[i].ps))))
		}
		n++
	}
	if n == 0 {
		return q
	}
	if n > 1 {
		q.push(runtime.MakeGroup(runtime.KOr, n))
	}
	q.top++
	return q
}

// NotAnyOf negates the disjunction AnyOf builds: NOT ((a AND b) OR c).
func (q Query) NotAnyOf(gs ...Grp) Query {
	before := q.top
	q = q.AnyOf(gs...)
	if q.top == before {
		return q
	}
	q.push(runtime.MakeGroup(runtime.KNot, 1))
	return q
}

// leaf records one predicate: its value goes to the arena for its type,
// its structure to the token stream.
func (q *Query) leaf(p Pred) {
	if p.op == opIn || p.op == opNotIn || p.op == opArrayContains || p.op == opArrayContainedBy || p.op == opArrayOverlaps || p.op == opHasAnyKey || p.op == opHasAllKeys {
		switch p.col {
		case 1:
			if int(q.nai32) >= 3 {
				q.over = true
				return
			}
			q.anyI32[q.nai32] = p.anyI32
			q.nai32++
		case 2:
			if int(q.nas) >= 3 {
				q.over = true
				return
			}
			q.anyStr[q.nas] = p.anyStr
			q.nas++
		case 3:
			if int(q.nas) >= 3 {
				q.over = true
				return
			}
			q.anyStr[q.nas] = p.anyStr
			q.nas++
		case 4:
			if int(q.nas) >= 3 {
				q.over = true
				return
			}
			q.anyStr[q.nas] = p.anyStr
			q.nas++
		case 5:
			if int(q.nas) >= 3 {
				q.over = true
				return
			}
			q.anyStr[q.nas] = p.anyStr
			q.nas++
		case 6:
			if int(q.nas) >= 3 {
				q.over = true
				return
			}
			q.anyStr[q.nas] = p.anyStr
			q.nas++
		case 7:
			if int(q.nas) >= 3 {
				q.over = true
				return
			}
			q.anyStr[q.nas] = p.anyStr
			q.nas++
		}
		q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
		return
	}
	if p.op == opIsNull || p.op == opIsNotNull {
		q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
		return
	}
	switch p.col {
	case 0:
		if int(q.ntm) >= 4 {
			q.over = true
			return
		}
		q.tims[q.ntm] = p.tim
		q.ntm++
	case 1:
		if int(q.nn) >= 6 {
			q.over = true
			return
		}
		q.nums[q.nn] = p.num
		q.nn++
	case 2:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 3:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 4:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 5:
		if int(q.ns) >= 6 {
			q.over = true
			return
		}
		q.strs[q.ns] = p.str
		q.ns++
	case 6:
		if int(q.njs) >= 2 {
			q.over = true
			return
		}
		q.jsns[q.njs] = p.jsn
		q.njs++
	case 7:
		if int(q.njs) >= 2 {
			q.over = true
			return
		}
		q.jsns[q.njs] = p.jsn
		q.njs++
	}
	q.push(runtime.MakeLeaf(uint32(p.op), uint32(p.col)))
}

// Chained predicate sugar. Identical to Where(Col.Op(v)).
func (q Query) CreatedAtEq(v time.Time) Query              { return q.Where(CreatedAt.Eq(v)) }
func (q Query) CreatedAtNotEq(v time.Time) Query           { return q.Where(CreatedAt.NotEq(v)) }
func (q Query) CreatedAtGt(v time.Time) Query              { return q.Where(CreatedAt.Gt(v)) }
func (q Query) CreatedAtGte(v time.Time) Query             { return q.Where(CreatedAt.Gte(v)) }
func (q Query) CreatedAtLt(v time.Time) Query              { return q.Where(CreatedAt.Lt(v)) }
func (q Query) CreatedAtLte(v time.Time) Query             { return q.Where(CreatedAt.Lte(v)) }
func (q Query) SortOrderEq(v int32) Query                  { return q.Where(SortOrder.Eq(v)) }
func (q Query) SortOrderNotEq(v int32) Query               { return q.Where(SortOrder.NotEq(v)) }
func (q Query) SortOrderGt(v int32) Query                  { return q.Where(SortOrder.Gt(v)) }
func (q Query) SortOrderGte(v int32) Query                 { return q.Where(SortOrder.Gte(v)) }
func (q Query) SortOrderLt(v int32) Query                  { return q.Where(SortOrder.Lt(v)) }
func (q Query) SortOrderLte(v int32) Query                 { return q.Where(SortOrder.Lte(v)) }
func (q Query) SortOrderIn(v ...int32) Query               { return q.Where(SortOrder.In(v...)) }
func (q Query) SortOrderNotIn(v ...int32) Query            { return q.Where(SortOrder.NotIn(v...)) }
func (q Query) CodeEq(v string) Query                      { return q.Where(Code.Eq(v)) }
func (q Query) CodeNotEq(v string) Query                   { return q.Where(Code.NotEq(v)) }
func (q Query) CodeGt(v string) Query                      { return q.Where(Code.Gt(v)) }
func (q Query) CodeGte(v string) Query                     { return q.Where(Code.Gte(v)) }
func (q Query) CodeLt(v string) Query                      { return q.Where(Code.Lt(v)) }
func (q Query) CodeLte(v string) Query                     { return q.Where(Code.Lte(v)) }
func (q Query) CodeLike(v string) Query                    { return q.Where(Code.Like(v)) }
func (q Query) CodeILike(v string) Query                   { return q.Where(Code.ILike(v)) }
func (q Query) CodeIn(v ...string) Query                   { return q.Where(Code.In(v...)) }
func (q Query) CodeNotIn(v ...string) Query                { return q.Where(Code.NotIn(v...)) }
func (q Query) DisplayNameEq(v string) Query               { return q.Where(DisplayName.Eq(v)) }
func (q Query) DisplayNameNotEq(v string) Query            { return q.Where(DisplayName.NotEq(v)) }
func (q Query) DisplayNameGt(v string) Query               { return q.Where(DisplayName.Gt(v)) }
func (q Query) DisplayNameGte(v string) Query              { return q.Where(DisplayName.Gte(v)) }
func (q Query) DisplayNameLt(v string) Query               { return q.Where(DisplayName.Lt(v)) }
func (q Query) DisplayNameLte(v string) Query              { return q.Where(DisplayName.Lte(v)) }
func (q Query) DisplayNameLike(v string) Query             { return q.Where(DisplayName.Like(v)) }
func (q Query) DisplayNameILike(v string) Query            { return q.Where(DisplayName.ILike(v)) }
func (q Query) DisplayNameIn(v ...string) Query            { return q.Where(DisplayName.In(v...)) }
func (q Query) DisplayNameNotIn(v ...string) Query         { return q.Where(DisplayName.NotIn(v...)) }
func (q Query) DefaultEffectEq(v string) Query             { return q.Where(DefaultEffect.Eq(v)) }
func (q Query) DefaultEffectNotEq(v string) Query          { return q.Where(DefaultEffect.NotEq(v)) }
func (q Query) DefaultEffectGt(v string) Query             { return q.Where(DefaultEffect.Gt(v)) }
func (q Query) DefaultEffectGte(v string) Query            { return q.Where(DefaultEffect.Gte(v)) }
func (q Query) DefaultEffectLt(v string) Query             { return q.Where(DefaultEffect.Lt(v)) }
func (q Query) DefaultEffectLte(v string) Query            { return q.Where(DefaultEffect.Lte(v)) }
func (q Query) DefaultEffectLike(v string) Query           { return q.Where(DefaultEffect.Like(v)) }
func (q Query) DefaultEffectILike(v string) Query          { return q.Where(DefaultEffect.ILike(v)) }
func (q Query) DefaultEffectIn(v ...string) Query          { return q.Where(DefaultEffect.In(v...)) }
func (q Query) DefaultEffectNotIn(v ...string) Query       { return q.Where(DefaultEffect.NotIn(v...)) }
func (q Query) StatusEq(v string) Query                    { return q.Where(Status.Eq(v)) }
func (q Query) StatusNotEq(v string) Query                 { return q.Where(Status.NotEq(v)) }
func (q Query) StatusGt(v string) Query                    { return q.Where(Status.Gt(v)) }
func (q Query) StatusGte(v string) Query                   { return q.Where(Status.Gte(v)) }
func (q Query) StatusLt(v string) Query                    { return q.Where(Status.Lt(v)) }
func (q Query) StatusLte(v string) Query                   { return q.Where(Status.Lte(v)) }
func (q Query) StatusLike(v string) Query                  { return q.Where(Status.Like(v)) }
func (q Query) StatusILike(v string) Query                 { return q.Where(Status.ILike(v)) }
func (q Query) StatusIn(v ...string) Query                 { return q.Where(Status.In(v...)) }
func (q Query) StatusNotIn(v ...string) Query              { return q.Where(Status.NotIn(v...)) }
func (q Query) ResolutionContains(v runtime.JSON) Query    { return q.Where(Resolution.Contains(v)) }
func (q Query) ResolutionContainedBy(v runtime.JSON) Query { return q.Where(Resolution.ContainedBy(v)) }
func (q Query) ResolutionHasAnyKey(v ...string) Query      { return q.Where(Resolution.HasAnyKey(v...)) }
func (q Query) ResolutionHasAllKeys(v ...string) Query     { return q.Where(Resolution.HasAllKeys(v...)) }
func (q Query) UiSchemaContains(v runtime.JSON) Query      { return q.Where(UiSchema.Contains(v)) }
func (q Query) UiSchemaContainedBy(v runtime.JSON) Query   { return q.Where(UiSchema.ContainedBy(v)) }
func (q Query) UiSchemaHasAnyKey(v ...string) Query        { return q.Where(UiSchema.HasAnyKey(v...)) }
func (q Query) UiSchemaHasAllKeys(v ...string) Query       { return q.Where(UiSchema.HasAllKeys(v...)) }

const selectPrefix = `SELECT "created_at", "sort_order", "code", "display_name", "default_effect", "status", "resolution", "ui_schema" FROM "scope_axes"`
const countPrefix = `SELECT count(*) FROM "scope_axes"`
const existsPrefix = `SELECT 1 FROM "scope_axes"`
const existsSuffix = ` LIMIT 1`
const limitSuffix = ` LIMIT $`
const limitOffsetSuffix = ` LIMIT $ OFFSET $`

// lockSuffix is the row-lock clause per mode, indexed by Query.lock.
// It goes at the very END of the statement — after LIMIT and OFFSET,
// which is what the grammar requires.
var lockSuffix = [7]string{
	``,
	` FOR UPDATE`,
	` FOR UPDATE NOWAIT`,
	` FOR UPDATE SKIP LOCKED`,
	` FOR SHARE`,
	` FOR SHARE NOWAIT`,
	` FOR SHARE SKIP LOCKED`,
}

// lockCaches holds one compiled-statement cache per (lock, offset)
// pair. The lock is part of the STATEMENT, so it has to be part of the
// key; a program that never locks never touches the locked entries and
// they stay the empty maps they start as.
var lockCaches = func() [7][2]*runtime.TreeCache {
	var cs [7][2]*runtime.TreeCache
	for i := range cs {
		cs[i][0], cs[i][1] = runtime.NewTreeCache(), runtime.NewTreeCache()
	}
	cs[0][0], cs[0][1] = cache, offsetCache
	return cs
}()

// orderTable is every ordering this table can express, lowered at build
// time. ORDER BY is chosen per query, so it cannot be a constant — but it
// still must not be built from strings at run time.
var orderTable = [nCols][4]string{
	{ // created_at
		"\"created_at\"",
		"\"created_at\" DESC",
		"\"created_at\" ASC NULLS FIRST",
		"\"created_at\" DESC NULLS LAST",
	},
	{ // sort_order
		"\"sort_order\"",
		"\"sort_order\" DESC",
		"\"sort_order\" ASC NULLS FIRST",
		"\"sort_order\" DESC NULLS LAST",
	},
	{ // code
		"\"code\"",
		"\"code\" DESC",
		"\"code\" ASC NULLS FIRST",
		"\"code\" DESC NULLS LAST",
	},
	{ // display_name
		"\"display_name\"",
		"\"display_name\" DESC",
		"\"display_name\" ASC NULLS FIRST",
		"\"display_name\" DESC NULLS LAST",
	},
	{ // default_effect
		"\"default_effect\"",
		"\"default_effect\" DESC",
		"\"default_effect\" ASC NULLS FIRST",
		"\"default_effect\" DESC NULLS LAST",
	},
	{ // status
		"\"status\"",
		"\"status\" DESC",
		"\"status\" ASC NULLS FIRST",
		"\"status\" DESC NULLS LAST",
	},
	{ // resolution
		"\"resolution\"",
		"\"resolution\" DESC",
		"\"resolution\" ASC NULLS FIRST",
		"\"resolution\" DESC NULLS LAST",
	},
	{ // ui_schema
		"\"ui_schema\"",
		"\"ui_schema\" DESC",
		"\"ui_schema\" ASC NULLS FIRST",
		"\"ui_schema\" DESC NULLS LAST",
	},
}

// identTable is each column's bare quoted name, for the left side of a
// row comparison.
var identTable = [nCols]string{
	"\"created_at\"",
	"\"sort_order\"",
	"\"code\"",
	"\"display_name\"",
	"\"default_effect\"",
	"\"status\"",
	"\"resolution\"",
	"\"ui_schema\"",
}

var lowering = runtime.Lowering{
	Frag:  fragOf,
	Order: orderOf,
	OB:    runtime.Order{Lead: " ORDER BY ", Sep: ", "},
	Ident: func(col uint32) string {
		if col >= nCols {
			return ""
		}
		return identTable[col]
	},
	RowCmp: func(op uint32) string {
		if op == runtime.CmpLt {
			return " < "
		}
		return " > "
	},
	TupleOpen:  "(",
	TupleSep:   ", ",
	TupleClose: ")",
}

func orderOf(dir, col uint32) string {
	if col >= nCols || int(dir) >= len(orderTable[0]) {
		return ""
	}
	return orderTable[col][dir]
}

// fragTable is every predicate this table can produce, lowered at build
// time. Runtime splices; it never formats.
var fragTable = [8][27]runtime.Frag{
	{ // created_at
		{}, // opNone
		{A: "\"created_at\" = $", B: ""},
		{A: "\"created_at\" <> $", B: ""},
		{A: "\"created_at\" > $", B: ""},
		{A: "\"created_at\" >= $", B: ""},
		{A: "\"created_at\" < $", B: ""},
		{A: "\"created_at\" <= $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // sort_order
		{}, // opNone
		{A: "\"sort_order\" = $", B: ""},
		{A: "\"sort_order\" <> $", B: ""},
		{A: "\"sort_order\" > $", B: ""},
		{A: "\"sort_order\" >= $", B: ""},
		{A: "\"sort_order\" < $", B: ""},
		{A: "\"sort_order\" <= $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{A: "\"sort_order\" = ANY($", B: ")"},
		{A: "\"sort_order\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // code
		{}, // opNone
		{A: "\"code\" = $", B: ""},
		{A: "\"code\" <> $", B: ""},
		{A: "\"code\" > $", B: ""},
		{A: "\"code\" >= $", B: ""},
		{A: "\"code\" < $", B: ""},
		{A: "\"code\" <= $", B: ""},
		{A: "\"code\" LIKE $", B: ""},
		{A: "\"code\" ILIKE $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{A: "\"code\" = ANY($", B: ")"},
		{A: "\"code\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // display_name
		{}, // opNone
		{A: "\"display_name\" = $", B: ""},
		{A: "\"display_name\" <> $", B: ""},
		{A: "\"display_name\" > $", B: ""},
		{A: "\"display_name\" >= $", B: ""},
		{A: "\"display_name\" < $", B: ""},
		{A: "\"display_name\" <= $", B: ""},
		{A: "\"display_name\" LIKE $", B: ""},
		{A: "\"display_name\" ILIKE $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{A: "\"display_name\" = ANY($", B: ")"},
		{A: "\"display_name\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // default_effect
		{}, // opNone
		{A: "\"default_effect\" = $", B: ""},
		{A: "\"default_effect\" <> $", B: ""},
		{A: "\"default_effect\" > $", B: ""},
		{A: "\"default_effect\" >= $", B: ""},
		{A: "\"default_effect\" < $", B: ""},
		{A: "\"default_effect\" <= $", B: ""},
		{A: "\"default_effect\" LIKE $", B: ""},
		{A: "\"default_effect\" ILIKE $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{A: "\"default_effect\" = ANY($", B: ")"},
		{A: "\"default_effect\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // status
		{}, // opNone
		{A: "\"status\" = $", B: ""},
		{A: "\"status\" <> $", B: ""},
		{A: "\"status\" > $", B: ""},
		{A: "\"status\" >= $", B: ""},
		{A: "\"status\" < $", B: ""},
		{A: "\"status\" <= $", B: ""},
		{A: "\"status\" LIKE $", B: ""},
		{A: "\"status\" ILIKE $", B: ""},
		{},
		{},
		{},
		{},
		{},
		{A: "\"status\" = ANY($", B: ")"},
		{A: "\"status\" <> ALL($", B: ")"},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
	},
	{ // resolution
		{}, // opNone
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{A: "\"resolution\" @> $", B: ""},
		{A: "\"resolution\" <@ $", B: ""},
		{A: "\"resolution\" ?| $", B: ""},
		{A: "\"resolution\" ?& $", B: ""},
		{},
		{},
		{},
		{},
	},
	{ // ui_schema
		{}, // opNone
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{},
		{A: "\"ui_schema\" @> $", B: ""},
		{A: "\"ui_schema\" <@ $", B: ""},
		{A: "\"ui_schema\" ?| $", B: ""},
		{A: "\"ui_schema\" ?& $", B: ""},
		{},
		{},
		{},
		{},
	},
}

func fragOf(op, col uint32) runtime.Frag {
	// Bounded by the table, not nCols: existence pseudo-columns live past
	// the real ones. Order, ident and arena lookups stay nCols-bounded,
	// so a pseudo-column can never be ordered by, cursored on, or bound.
	if int(col) >= len(fragTable) || int(op) >= len(fragTable[0]) {
		return runtime.Frag{}
	}
	return fragTable[col][op]
}

// defaultOrder is what a query with no Order() uses.
//
// It is never empty. A read without ORDER BY has no defined order, so
// paging one is a bug waiting for a plan change to expose it — and the
// primary key is the cheapest total order available.
var defaultOrder = [1]runtime.Tok{
	runtime.MakeOrder(runtime.Asc, 2), // code
}

var (
	cache       = runtime.NewTreeCache()
	offsetCache = runtime.NewTreeCache()
	countCache  = runtime.NewTreeCache()
	existsCache = runtime.NewTreeCache()
)

// Shapes reports how many distinct query structures have compiled.
// `storm lint` uses it to catch a builder minting a statement per request.
func Shapes() int { return cache.Shapes() }

// ShapeFlushes reports how many times a shape cache in this package hit
// runtime.ShapeCap and dropped. Zero is the expected value forever:
// nonzero means a call site is minting structures from request data
// rather than from code, and the fix is that call site, not a bigger
// cap. Export it as a gauge — it is the cheapest early warning that a
// filter screen turned into 2^n statements.
func ShapeFlushes() int {
	return cache.Flushes() + offsetCache.Flushes() +
		countCache.Flushes() + existsCache.Flushes()
}

// stmtFor compiles a read. LIMIT and LIMIT/OFFSET are different
// statements with different placeholder counts, so they get different
// caches rather than a sentinel token muddying the key.
func stmtFor(toks []runtime.Tok, withOffset bool, lock uint8) *runtime.Stmt {
	i, suffix := 0, limitSuffix
	if withOffset {
		i, suffix = 1, limitOffsetSuffix
	}
	c := lockCaches[lock][i]
	suffix += lockSuffix[lock]
	if st := c.Get(toks); st != nil {
		return st
	}
	return c.Put(toks, runtime.SpliceTree(selectPrefix, toks, lowering, suffix))
}

// existsStmtFor compiles the existence probe: SELECT 1, no ORDER BY,
// LIMIT 1 — the planner stops at the first matching tuple instead of
// sorting every match to return the "first" of an order nobody reads.
func existsStmtFor(toks []runtime.Tok) *runtime.Stmt {
	if st := existsCache.Get(toks); st != nil {
		return st
	}
	return existsCache.Put(toks, runtime.SpliceTree(existsPrefix, toks, lowering, existsSuffix))
}

func countStmtFor(toks []runtime.Tok) *runtime.Stmt {
	if st := countCache.Get(toks); st != nil {
		return st
	}
	// A count ignores ordering as well as LIMIT: ordering a scalar is
	// wasted work, and the token stream is trimmed before it gets here.
	return countCache.Put(toks, runtime.SpliceTree(countPrefix, toks, lowering, ""))
}

// Composition seams, for the generated CONTEXT package and it alone:
// cross-table statements (a filtered semi-join spans two packages) are
// assembled there from each side's tokens, fragments and bindings. Ids
// only — no SQL text and no value crosses here.

// FragOf is the compiled fragment table, exported for composition.
func FragOf(op, col uint32) runtime.Frag { return fragOf(op, col) }

// Lowering is this package's back-end text, exported for composition.
func Lowering() runtime.Lowering { return lowering }

// StmtPieces are the statement's constant parts, exported for composition.
func StmtPieces() (selectPfx, countPfx, limitSfx string) {
	return selectPrefix, countPrefix, limitSuffix
}

// PredToks appends this query's predicate stream to dst: top-level
// conjuncts reduced to one entry, order excluded.
func (q Query) PredToks(dst []runtime.Tok) []runtime.Tok {
	var buf [21]runtime.Tok
	return append(dst, q.preds(&buf)...)
}

// OrderToks appends this query's ordering — explicit, or the default
// unless Unordered.
func (q Query) OrderToks(dst []runtime.Tok) []runtime.Tok {
	if q.no == 0 {
		if q.noOrder {
			return dst
		}
		return append(dst, defaultOrder[:]...)
	}
	return append(dst, q.otoks[:q.no]...)
}

// BindPreds binds this query's predicate values into b, appending to v.
func (q Query) BindPreds(b *Binder, v []any) []any {
	return append(v, q.bindPreds(b)...)
}

// BindPaging appends the LIMIT (and OFFSET when set) arguments.
func (q Query) BindPaging(b *Binder, v []any) []any {
	b.limit = q.limit
	v = append(v, &b.limit)
	if q.offset > 0 {
		b.offset = q.offset
		v = append(v, &b.offset)
	}
	return v
}

// Shape is a fingerprint of this query's structure — equal shapes share a
// compiled statement. Values do not contribute, which is the point.
func (q Query) Shape() uint64 {
	var buf [21]runtime.Tok
	return runtime.HashToks(q.stream(&buf))
}

// SQL returns the compiled text for this query's structure.
func (q Query) SQL() string {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0, q.lock).SQL
}

// Scan decodes one row from raw wire bytes into r, copying text into sl.
//
// Exported for the context package, which assembles batched results and
// therefore has to decode rows it did not issue the query for.
func Scan(rv [][]byte, r *Row, sl *runtime.Slab) error { return scan(rv, r, sl) }

// scan decodes one row straight from the wire. No reflect, no `any`, no
// driver.Value: the generator knows every column's type already.
//
// It returns an error only for a value the Go type cannot carry — a
// numeric past 18 significant digits, or a NaN. Those must not become a
// plausible zero, and a row scanner is the last place that can tell.
func scan(rv [][]byte, r *Row, sl *runtime.Slab) error {
	r.CreatedAt = runtime.Timestamptz(rv[0])
	r.SortOrder = runtime.Int4(rv[1])
	r.Code = sl.Str(rv[2])
	r.DisplayName = sl.Str(rv[3])
	r.DefaultEffect = sl.Str(rv[4])
	r.Status = sl.Str(rv[5])
	r.Resolution = runtime.JSON(runtime.JSONB(rv[6], sl))
	r.UiSchema = runtime.JSON(runtime.JSONB(rv[7], sl))
	return nil
}

type binder struct {
	vals   []any
	strs   [6]string
	nums   [6]int64
	tims   [4]time.Time
	jsns   [2]runtime.JSON
	anyStr [3][]string
	anyI32 [3][]int32
	limit  int64
	offset int64
}

var binders = runtime.NewPool(func() *binder {
	return &binder{vals: make([]any, 0, 17)}
})

// Binder is the pooled argument buffer.
type Binder = binder

func GetBinder() *Binder  { return binders.Get() }
func PutBinder(b *Binder) { putBinder(b) }

// putBinder clears every field that references memory OUTSIDE the binder
// before pooling it. A pooled binder otherwise PINS the caller's data —
// the slice behind an In(...) and the bytes behind every bound string —
// for as long as the pool holds it, which is forever. The numeric, time
// and uuid arenas are value arrays and pin nothing; vals points at the
// binder's own fields. A few nil stores against a round trip is free.
func putBinder(b *binder) {
	for i := range b.strs {
		b.strs[i] = ""
	}
	for i := range b.anyStr {
		b.anyStr[i] = nil
	}
	for i := range b.anyI32 {
		b.anyI32[i] = nil
	}
	binders.Put(b)
}

// bindPreds copies arena values into the pooled buffer and points the
// []any at the buffer's own fields — boxing a pointer does not allocate.
// Count and Exists stop here: their statements carry no LIMIT or OFFSET.
func (q Query) bindPreds(b *binder) []any {
	v := b.vals[:0]
	var ns, nn, ntm, njs, nas, nai32 uint8
	for i := uint8(0); i < q.nt; i++ {
		t := q.toks[i]
		// KLeaf binds a predicate's value; KCol binds a keyset cursor's.
		// Both live in the same per-type arenas in stream order, so the
		// column switch below handles them identically. A KCol carries no
		// operator — its op is opNone, which matches no case in the
		// operator switch and falls straight through.
		if k := t.Kind(); k != runtime.KLeaf && k != runtime.KCol {
			continue
		}
		switch runtime.Op(t.Op()) {
		case opIsNull, opIsNotNull:
			continue
		case opIn, opNotIn, opArrayContains, opArrayContainedBy, opArrayOverlaps, opHasAnyKey, opHasAllKeys:
			switch t.Col() {
			case 1:
				b.anyI32[nai32] = q.anyI32[nai32]
				v = append(v, &b.anyI32[nai32])
				nai32++
			case 2:
				b.anyStr[nas] = q.anyStr[nas]
				v = append(v, &b.anyStr[nas])
				nas++
			case 3:
				b.anyStr[nas] = q.anyStr[nas]
				v = append(v, &b.anyStr[nas])
				nas++
			case 4:
				b.anyStr[nas] = q.anyStr[nas]
				v = append(v, &b.anyStr[nas])
				nas++
			case 5:
				b.anyStr[nas] = q.anyStr[nas]
				v = append(v, &b.anyStr[nas])
				nas++
			case 6:
				b.anyStr[nas] = q.anyStr[nas]
				v = append(v, &b.anyStr[nas])
				nas++
			case 7:
				b.anyStr[nas] = q.anyStr[nas]
				v = append(v, &b.anyStr[nas])
				nas++
			}
			continue
		}
		switch t.Col() {
		case 0:
			b.tims[ntm] = q.tims[ntm]
			v = append(v, &b.tims[ntm])
			ntm++
		case 1:
			b.nums[nn] = q.nums[nn]
			v = append(v, &b.nums[nn])
			nn++
		case 2:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 3:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 4:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 5:
			b.strs[ns] = q.strs[ns]
			v = append(v, &b.strs[ns])
			ns++
		case 6:
			b.jsns[njs] = q.jsns[njs]
			v = append(v, &b.jsns[njs])
			njs++
		case 7:
			b.jsns[njs] = q.jsns[njs]
			v = append(v, &b.jsns[njs])
			njs++
		}
	}
	b.vals = v
	return v
}

// bind is bindPreds plus the paging arguments, in suffix order.
func (q Query) bind(b *binder) []any {
	v := q.bindPreds(b)
	b.limit = q.limit
	v = append(v, &b.limit)
	// An offset of zero is absent from the statement, so binding it
	// would leave an argument nothing consumes.
	if q.offset > 0 {
		b.offset = q.offset
		v = append(v, &b.offset)
	}
	b.vals = v
	return v
}

// All runs the query and decodes every row.
func (q Query) All(ctx context.Context, ex runtime.Executor, dst []Row) ([]Row, error) {
	var sl runtime.Slab
	return q.AllInto(ctx, ex, dst, &sl)
}

// AllInto lets the caller own the string arena.
func (q Query) AllInto(ctx context.Context, ex runtime.Executor, dst []Row, sl *runtime.Slab) ([]Row, error) {
	if err := q.Err(); err != nil {
		return dst, err
	}
	var buf [21]runtime.Tok
	st := stmtFor(q.stream(&buf), q.offset > 0, q.lock)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return dst, st.Err
	}
	sl.Reserve(st.SlabHint())
	b := binders.Get()
	defer putBinder(b)

	rows, err := ex.Query(ctx, st.SQL, q.bind(b))
	if err != nil {
		return dst, err
	}
	defer rows.Close()
	for rows.Next() {
		dst = append(dst, Row{})
		if err := scan(rows.RawValues(), &dst[len(dst)-1], sl); err != nil {
			return dst, err
		}
	}
	st.ObserveSlab(sl.Size())
	return dst, rows.Err()
}

// One returns the first row, if any.
func (q Query) One(ctx context.Context, ex runtime.Executor) (Row, bool, error) {
	var sl runtime.Slab
	var buf [1]Row
	out, err := q.Limit(1).AllInto(ctx, ex, buf[:0], &sl)
	if err != nil || len(out) == 0 {
		return Row{}, false, err
	}
	return out[0], true, nil
}

// Count ignores Limit: counting a truncated set is a bug, not a feature.
func (q Query) Count(ctx context.Context, ex runtime.Executor) (int64, error) {
	if err := q.Err(); err != nil {
		return 0, err
	}
	if q.lock != 0 {
		return 0, errCountLocked
	}
	var buf [21]runtime.Tok
	st := countStmtFor(q.preds(&buf))
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return 0, st.Err
	}
	b := binders.Get()
	defer putBinder(b)
	// bindPreds, not bind: a count has no LIMIT and no OFFSET. The old
	// form bound everything and sliced the last argument off, which was
	// the limit — unless Offset was set, in which case it silently kept
	// the limit and dropped the offset, and the statement mismatched.
	rows, err := ex.Query(ctx, st.SQL, q.bindPreds(b))
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	var n int64
	if rows.Next() {
		n = runtime.Int8(rows.RawValues()[0])
	}
	return n, rows.Err()
}

// Exists asks the one-bit question with a one-bit statement: SELECT 1,
// no ORDER BY, LIMIT 1. It was previously One() with the row thrown
// away, which projected every column AND carried the default ordering —
// measured on 50k rows, the planner top-N-sorted all 16,667 matches to
// return the "first" of an order nobody was going to read.
func (q Query) Exists(ctx context.Context, ex runtime.Executor) (bool, error) {
	if err := q.Err(); err != nil {
		return false, err
	}
	if q.lock != 0 {
		return false, errExistsLocked
	}
	var buf [21]runtime.Tok
	st := existsStmtFor(q.preds(&buf))
	if st.Err != nil {
		return false, st.Err
	}
	b := binders.Get()
	defer putBinder(b)
	rows, err := ex.Query(ctx, st.SQL, q.bindPreds(b))
	if err != nil {
		return false, err
	}
	defer rows.Close()
	return rows.Next(), rows.Err()
}

// Prepare resolves the structure and binds arguments without executing.
func (q Query) Prepare(b *Binder) (string, []any) {
	var buf [21]runtime.Tok
	return stmtFor(q.stream(&buf), q.offset > 0, q.lock).SQL, q.bind(b)
}

// insertSQL does not vary: the column list is fixed by the table, so
// the placeholders are known at build time and nothing is spliced.
const insertSQL = `INSERT INTO "scope_axes" ("created_at", "sort_order", "code", "display_name", "default_effect", "status", "resolution", "ui_schema") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "created_at", "sort_order", "code", "display_name", "default_effect", "status", "resolution", "ui_schema"`

const updatePrefix = `UPDATE "scope_axes" SET `
const deletePrefix = `DELETE FROM "scope_axes"`

// Dirty bits. One per updatable column; the set of them is an UPDATE's
// identity, exactly as a token stream is a SELECT's.
const (
	dCreatedAt     uint64 = 1 << 0
	dSortOrder     uint64 = 1 << 1
	dDisplayName   uint64 = 1 << 2
	dDefaultEffect uint64 = 1 << 3
	dStatus        uint64 = 1 << 4
	dResolution    uint64 = 1 << 5
	dUiSchema      uint64 = 1 << 6
)

const nUpdatable = 7

// setFrags is every assignment this table can make, lowered at build time.
var setFrags = [nUpdatable]runtime.Frag{
	{A: "\"created_at\" = $", B: ""},     // created_at
	{A: "\"sort_order\" = $", B: ""},     // sort_order
	{A: "\"display_name\" = $", B: ""},   // display_name
	{A: "\"default_effect\" = $", B: ""}, // default_effect
	{A: "\"status\" = $", B: ""},         // status
	{A: "\"resolution\" = $", B: ""},     // resolution
	{A: "\"ui_schema\" = $", B: ""},      // ui_schema
}

// pkFrags addresses one row.
var pkFrags = [1]runtime.Frag{
	{A: "\"code\" = $", B: ""}, // code
}

// Insert bits. A masked INSERT names only the columns the caller
// assigned, so every other column takes its database default — which is
// the only way a DEFAULT gen_random_uuid() can ever fire.
const (
	iCreatedAt     uint64 = 1 << 0
	iSortOrder     uint64 = 1 << 1
	iCode          uint64 = 1 << 2
	iDisplayName   uint64 = 1 << 3
	iDefaultEffect uint64 = 1 << 4
	iStatus        uint64 = 1 << 5
	iResolution    uint64 = 1 << 6
	iUiSchema      uint64 = 1 << 7
)

const nInsertable = 8

// insCols is the quoted column name for each insert bit.
var insCols = [nInsertable]string{
	"\"created_at\"",
	"\"sort_order\"",
	"\"code\"",
	"\"display_name\"",
	"\"default_effect\"",
	"\"status\"",
	"\"resolution\"",
	"\"ui_schema\"",
}

// insParts and insPlaceholder come from the back end at build time; the
// runtime splicer chooses none of them.
var insParts = runtime.InsertParts{Open: " (", Sep: ", ", Mid: ") VALUES (", Close: ")"}
var insPlaceholder = runtime.Placeholder{}

const insPrefix = "INSERT INTO \"scope_axes\""
const insReturning = " RETURNING \"created_at\", \"sort_order\", \"code\", \"display_name\", \"default_effect\", \"status\", \"resolution\", \"ui_schema\""

var insCache = runtime.NewMaskCache()

// insOpCache is the batch path's, keyed the same way. Separate because
// the statements differ by their RETURNING and one cache would hand a
// batch the statement that asks for rows back.
var insOpCache = runtime.NewMaskCache()
var updCache = runtime.NewMaskCache()

// Masks reports how many distinct UPDATE shapes have compiled.
func Masks() int { return updCache.Masks() }

// Mut is a row staged for update: the values, plus which of them were
// actually assigned. An UPDATE writes the assigned ones and no others,
// so a read-modify-write cannot clobber a column it never looked at.
type Mut struct {
	row   Row
	dirty uint64
}

// Mutate stages a row read from the database.
func Mutate(r Row) Mut { return Mut{row: r} }

// Row returns the staged values.
func (m Mut) Row() Row { return m.row }

// Dirty reports the assigned-column mask, which is also the statement key.
func (m Mut) Dirty() uint64 { return m.dirty }

// Setters. There is deliberately no setter for the primary key, for an
// Immutable column, or for the version column: the absence of a method is
// the enforcement, so misuse does not compile rather than failing later.
func (m *Mut) SetCreatedAt(v time.Time) {
	m.row.CreatedAt = v
	m.dirty |= dCreatedAt
}

func (m *Mut) SetSortOrder(v int32) {
	m.row.SortOrder = v
	m.dirty |= dSortOrder
}

func (m *Mut) SetDisplayName(v string) {
	m.row.DisplayName = v
	m.dirty |= dDisplayName
}

func (m *Mut) SetDefaultEffect(v string) {
	m.row.DefaultEffect = v
	m.dirty |= dDefaultEffect
}

func (m *Mut) SetStatus(v string) {
	m.row.Status = v
	m.dirty |= dStatus
}

func (m *Mut) SetResolution(v runtime.JSON) {
	m.row.Resolution = v
	m.dirty |= dResolution
}

func (m *Mut) SetUiSchema(v runtime.JSON) {
	m.row.UiSchema = v
	m.dirty |= dUiSchema
}

// Ins stages a new row. Unlike Mut it has a setter for every insertable
// column including the primary key and Immutable ones — supplying your
// own id is legitimate, changing it later is not.
//
// A column left unset is absent from the statement, so the database
// applies its default. Absence is tracked by the mask, never inferred
// from a zero value: that inference is why other ORMs cannot insert a
// false, a 0 or an empty string into a column that has a default.
type Ins struct {
	row Row
	set uint64

	// conflict is the upsert target, as a bit per unique-constraint
	// column set. Zero means a plain insert, and a duplicate is an error
	// — which is the right default: silently updating a row you meant to
	// create is a data-loss bug that looks like success.
	conflict uint8
}

// Create stages a new row.
func Create() Ins { return Ins{} }

// Assigned reports the mask, which is also the statement key.
func (n Ins) Assigned() uint64 { return n.set }

func (n *Ins) SetCreatedAt(v time.Time) {
	n.row.CreatedAt = v
	n.set |= iCreatedAt
}

func (n *Ins) SetSortOrder(v int32) {
	n.row.SortOrder = v
	n.set |= iSortOrder
}

func (n *Ins) SetCode(v string) {
	n.row.Code = v
	n.set |= iCode
}

func (n *Ins) SetDisplayName(v string) {
	n.row.DisplayName = v
	n.set |= iDisplayName
}

func (n *Ins) SetDefaultEffect(v string) {
	n.row.DefaultEffect = v
	n.set |= iDefaultEffect
}

func (n *Ins) SetStatus(v string) {
	n.row.Status = v
	n.set |= iStatus
}

func (n *Ins) SetResolution(v runtime.JSON) {
	n.row.Resolution = v
	n.set |= iResolution
}

func (n *Ins) SetUiSchema(v runtime.JSON) {
	n.row.UiSchema = v
	n.set |= iUiSchema
}

// The conflict encoding. One byte holds both which unique index an
// upsert names and what it does on collision, so the insert statement
// cache stays keyed by one mask and one byte:
//
//	0        no ON CONFLICT clause
//	1        ON CONFLICT DO NOTHING, on any unique index
//	2+2*i    target i, DO UPDATE
//	3+2*i    target i, DO NOTHING
const conflictAny = 1

// upsertTail builds the ON CONFLICT clause for one encoded conflict
// and one insert mask.
//
// The mask is what makes an upsert correct: it overwrites only the
// columns the caller ASSIGNED. Assigning every column would revert
// each one the caller left out to its default, on the row that
// already exists — a silent data loss that reads as an upsert working.
func upsertTail(conflict uint8, mask uint64) string {
	if conflict == conflictAny {
		return " ON CONFLICT DO NOTHING"
	}
	spec, i := conflictSpecs[(conflict-2)/2], (conflict-2)/2
	if conflict%2 == 1 {
		return spec + " DO NOTHING"
	}
	set := assignable(i, mask)
	if len(set) == 0 {
		// Nothing to overwrite. DO UPDATE SET with an empty list is not
		// SQL, and leaving the row alone is what the caller asked for.
		return spec + " DO NOTHING"
	}
	return spec + " DO UPDATE SET " + joinAssign(set)
}

// conflictSpecs is one inference specification per target, in
// declaration order. A PARTIAL unique index carries its predicate:
// PostgreSQL infers the index from the keys and the predicate
// together, and without it the insert fails at run time — on the first
// row that collides, which a test inserting distinct rows never sees.
var conflictSpecs = []string{
	" ON CONFLICT (\"code\")",
}

// assignable is the columns target i may overwrite, given the mask.
func assignable(i uint8, mask uint64) []string {
	set := make([]string, 0, 7)
	switch i {
	case 0:
		if mask&(1<<0) != 0 {
			set = append(set, "created_at")
		}
		if mask&(1<<1) != 0 {
			set = append(set, "sort_order")
		}
		if mask&(1<<3) != 0 {
			set = append(set, "display_name")
		}
		if mask&(1<<4) != 0 {
			set = append(set, "default_effect")
		}
		if mask&(1<<5) != 0 {
			set = append(set, "status")
		}
		if mask&(1<<6) != 0 {
			set = append(set, "resolution")
		}
		if mask&(1<<7) != 0 {
			set = append(set, "ui_schema")
		}
	}
	return set
}

// OnConflictCode upserts on the unique index over (code).
//
// The row that already exists keeps every column this insert did
// not assign. Follow with DoNothing() to leave it untouched
// entirely.
func (n *Ins) OnConflictCode() *Ins {
	n.conflict = 2
	return n
}

// DoNothing makes the insert a no-op when the row is already there —
// the idempotent insert, and the commonest upsert there is.
//
// On its own it names no index, so ANY unique violation is the no-op:
//
//	n.DoNothing()                  // ON CONFLICT DO NOTHING
//	n.OnConflictCode().DoNothing()  // only on that one index
//
// Insert then returns runtime.ErrNoRows when nothing was written,
// because DO NOTHING suppresses the RETURNING row: there is no row to
// return, and reporting a zero-valued one as inserted would be a lie.
func (n *Ins) DoNothing() *Ins {
	if n.conflict < 2 {
		n.conflict = conflictAny
		return n
	}
	n.conflict |= 1
	return n
}

// joinAssign renders the DO UPDATE SET list for the columns the caller
// assigned. The punctuation comes from the back end, never from here.
func joinAssign(set []string) string {
	out := ""
	for i, c := range set {
		if i > 0 {
			out += ", "
		}
		out += assignExcluded(c)
	}
	return out
}

var assignFor = map[string]string{
	"created_at":     "\"created_at\" = EXCLUDED.\"created_at\"",
	"sort_order":     "\"sort_order\" = EXCLUDED.\"sort_order\"",
	"display_name":   "\"display_name\" = EXCLUDED.\"display_name\"",
	"default_effect": "\"default_effect\" = EXCLUDED.\"default_effect\"",
	"status":         "\"status\" = EXCLUDED.\"status\"",
	"resolution":     "\"resolution\" = EXCLUDED.\"resolution\"",
	"ui_schema":      "\"ui_schema\" = EXCLUDED.\"ui_schema\"",
}

func assignExcluded(c string) string { return assignFor[c] }

func stmtForInsert(mask uint64, conflict uint8) *runtime.Stmt {
	// The conflict clause is part of the statement, so it must be part of
	// the key. Packing it above the column bits keeps one cache for both.
	key := mask | uint64(conflict)<<nInsertable
	if st := insCache.Get(key); st != nil {
		return st
	}
	cols := make([]string, 0, nInsertable)
	for i := 0; i < nInsertable; i++ {
		if mask&(1<<uint(i)) != 0 {
			cols = append(cols, insCols[i])
		}
	}
	suffix := insReturning
	if conflict > 0 {
		suffix = upsertTail(conflict, mask) + insReturning
	}
	return insCache.Put(key, runtime.SpliceInsertWith(insPrefix, insParts, cols, insPlaceholder, suffix))
}

// Insert writes the assigned columns and reads every column back, so
// database-computed values land in the returned Row rather than needing a
// second SELECT that would race every other writer.
func (n *Ins) Insert(ctx context.Context, ex runtime.Executor) (Row, error) {
	if n.set == 0 {
		return Row{}, runtime.ErrNothingAssigned
	}
	st := stmtForInsert(n.set, n.conflict)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return Row{}, st.Err
	}
	args := make([]any, 0, st.NArg)
	for i := 0; i < nInsertable; i++ {
		if n.set&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, n.row.CreatedAt)
		case 1:
			args = append(args, n.row.SortOrder)
		case 2:
			args = append(args, n.row.Code)
		case 3:
			args = append(args, n.row.DisplayName)
		case 4:
			args = append(args, n.row.DefaultEffect)
		case 5:
			args = append(args, n.row.Status)
		case 6:
			args = append(args, n.row.Resolution)
		case 7:
			args = append(args, n.row.UiSchema)
		}
	}
	var out Row
	rows, err := ex.Query(ctx, st.SQL, args)
	if err != nil {
		return out, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return out, err
		}
		if n.conflict != 0 && n.conflict%2 == 1 {
			// DO NOTHING suppresses RETURNING, so no row means the row was
			// already there — the success case of an idempotent insert.
			return out, runtime.ErrConflict
		}
		return out, runtime.ErrNoRow
	}
	var sl runtime.Slab
	if err := scan(rows.RawValues(), &out, &sl); err != nil {
		return out, err
	}
	return out, rows.Err()
}

// Inserts reports how many distinct INSERT column sets have compiled.
func Inserts() int { return insCache.Masks() }

// Insert writes one row and reads back every column, so database-computed
// defaults — a generated id, a now() timestamp — land in r rather than
// needing a second SELECT that would race every other writer.
//
// Every insertable column is written, including zero values. storm does
// not treat a zero as 'unset': that guess is why other ORMs cannot insert
// a false, a 0 or an empty string into a column with a default.
func Insert(ctx context.Context, ex runtime.Executor, r *Row) error {
	args := make([]any, 0, 8)
	args = append(args, r.CreatedAt)
	args = append(args, r.SortOrder)
	args = append(args, r.Code)
	args = append(args, r.DisplayName)
	args = append(args, r.DefaultEffect)
	args = append(args, r.Status)
	args = append(args, r.Resolution)
	args = append(args, r.UiSchema)
	rows, err := ex.Query(ctx, insertSQL, args)
	if err != nil {
		return err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return err
		}
		return runtime.ErrNoRow
	}
	// The returned strings live as long as this Slab, and the Slab lives
	// as long as r — a Row from an insert owns its own arena, unlike a Row
	// from a scan, which shares the result set's.
	var sl runtime.Slab
	if err := scan(rows.RawValues(), r, &sl); err != nil {
		return err
	}
	return rows.Err()
}

// copyCols is the fixed column list of a bulk load. Unlike Ins there is
// no mask: COPY sends one shape for the whole stream, so every row must
// supply every column and database defaults do not apply. Fill the row
// yourself, or use Create() per row and give up the bulk path.
var copyCols = []string{
	"created_at",
	"sort_order",
	"code",
	"display_name",
	"default_effect",
	"status",
	"resolution",
	"ui_schema",
}

// rowSource walks a []Row for CopyFrom without copying any of it.
type rowSource struct {
	rows []Row
	i    int
	buf  [8]any
}

func (s *rowSource) Next() bool {
	s.i++
	return s.i <= len(s.rows)
}

// Values reuses one buffer across every row, and fills it with POINTERS
// into the caller's slice rather than copies.
//
// Both halves matter. The driver consumes each slice before asking for
// the next, so one buffer is safe. And boxing a pointer into an `any`
// does not allocate while boxing a value does — at a thousand rows that
// is one allocation per column per row, or none. Measured: the first cut
// boxed values and cost 7 allocations per row.
func (s *rowSource) Values() []any {
	r := &s.rows[s.i-1]
	s.buf[0] = &r.CreatedAt
	s.buf[1] = &r.SortOrder
	s.buf[2] = &r.Code
	s.buf[3] = &r.DisplayName
	s.buf[4] = &r.DefaultEffect
	s.buf[5] = &r.Status
	s.buf[6] = &r.Resolution
	s.buf[7] = &r.UiSchema
	return s.buf[:]
}

func (s *rowSource) Err() error { return nil }

// InsertAll bulk-loads rows through the driver's COPY protocol: ONE round
// trip regardless of row count, because COPY is a different wire path and
// not a faster loop over INSERT.
//
// It returns no rows. COPY has no RETURNING, so a caller who needs
// database-generated ids must supply them — which is why the primary key
// is in copyCols and must be set on every row.
func InsertAll(ctx context.Context, ex runtime.Executor, rows []Row) (int64, error) {
	if len(rows) == 0 {
		return 0, nil
	}
	src := &rowSource{rows: rows}
	return ex.CopyFrom(ctx, "scope_axes", copyCols, src)
}

// InsertOp is an insert as a queueable statement. It writes every
// insertable column, because a batch of a thousand rows that each chose
// a different column set would compile a thousand statements and defeat
// the point of batching them.
//
// WantRows is false: a batched insert reports a count. Asking for
// RETURNING here would mean scanning a result per statement, which is
// exactly the per-row work a batch exists to avoid.
func InsertOp(r Row) runtime.BatchOp {
	var mask uint64
	mask |= 1 << 0
	mask |= 1 << 1
	mask |= 1 << 2
	mask |= 1 << 3
	mask |= 1 << 4
	mask |= 1 << 5
	mask |= 1 << 6
	mask |= 1 << 7
	st := stmtForInsertNoReturn(mask, 0)
	args := make([]any, 0, 8)
	args = append(args, r.CreatedAt)
	args = append(args, r.SortOrder)
	args = append(args, r.Code)
	args = append(args, r.DisplayName)
	args = append(args, r.DefaultEffect)
	args = append(args, r.Status)
	args = append(args, r.Resolution)
	args = append(args, r.UiSchema)
	return runtime.BatchOp{SQL: st.SQL, Args: args}
}

// Op is this Ins as a queueable statement, conflict clause and all —
// the bulk upsert.
//
// InsertOp above takes a Row and writes every column, so a thousand of
// them share one statement. This takes the BUILDER, so it carries the
// mask and the ON CONFLICT the caller chose: ingesting a batch that
// should overwrite what is already there, or skip it, needs both and
// could otherwise only be done one round trip at a time.
//
// One statement per distinct (mask, conflict) pair, cached like every
// other. Assign the same columns on every row of a batch and it stays
// one; vary them and it is one per shape, which is the cost of asking.
//
// WantRows is false, as for InsertOp: a batch reports counts. A DO
// NOTHING that skipped a row is a zero in that count — the batch
// cannot say which rows were skipped, only how many.
func (n *Ins) Op() (runtime.BatchOp, error) {
	if n.set == 0 {
		return runtime.BatchOp{}, runtime.ErrNothingAssigned
	}
	st := stmtForInsertNoReturn(n.set, n.conflict)
	if st.Err != nil {
		return runtime.BatchOp{}, st.Err
	}
	args := make([]any, 0, st.NArg)
	for i := 0; i < nInsertable; i++ {
		if n.set&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, n.row.CreatedAt)
		case 1:
			args = append(args, n.row.SortOrder)
		case 2:
			args = append(args, n.row.Code)
		case 3:
			args = append(args, n.row.DisplayName)
		case 4:
			args = append(args, n.row.DefaultEffect)
		case 5:
			args = append(args, n.row.Status)
		case 6:
			args = append(args, n.row.Resolution)
		case 7:
			args = append(args, n.row.UiSchema)
		}
	}
	return runtime.BatchOp{SQL: st.SQL, Args: args}, nil
}

// stmtForInsertNoReturn is stmtForInsert without RETURNING, for the
// batch path. Its own cache: the two differ by a suffix, and sharing
// one would hand a batch the statement that asks for rows back.
func stmtForInsertNoReturn(mask uint64, conflict uint8) *runtime.Stmt {
	key := mask | uint64(conflict)<<nInsertable
	if st := insOpCache.Get(key); st != nil {
		return st
	}
	cols := make([]string, 0, nInsertable)
	for i := 0; i < nInsertable; i++ {
		if mask&(1<<uint(i)) != 0 {
			cols = append(cols, insCols[i])
		}
	}
	suffix := ""
	if conflict > 0 {
		suffix = upsertTail(conflict, mask)
	}
	return insOpCache.Put(key, runtime.SpliceInsertWith(insPrefix, insParts, cols, insPlaceholder, suffix))
}

// UpdateOp is this Mut's update as a queueable statement.
//
// The optimistic lock still applies, but the caller must check the
// affected count the batch reports: a stale write inside a batch is not
// an error the driver raises, it is a zero the caller has to notice.
func (m *Mut) UpdateOp() (runtime.BatchOp, bool) {
	if m.dirty == 0 {
		return runtime.BatchOp{}, false
	}
	st := stmtForMask(m.dirty)
	args := make([]any, 0, st.NArg)
	for i := 0; i < nUpdatable; i++ {
		if m.dirty&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, m.row.CreatedAt)
		case 1:
			args = append(args, m.row.SortOrder)
		case 2:
			args = append(args, m.row.DisplayName)
		case 3:
			args = append(args, m.row.DefaultEffect)
		case 4:
			args = append(args, m.row.Status)
		case 5:
			args = append(args, m.row.Resolution)
		case 6:
			args = append(args, m.row.UiSchema)
		}
	}
	args = append(args, m.row.Code)
	return runtime.BatchOp{SQL: st.SQL, Args: args}, true
}

// DeleteOp is a delete as a queueable statement.
func DeleteOp(code string) runtime.BatchOp {
	return runtime.BatchOp{SQL: deleteSQL, Args: []any{code}}
}

// Table is the table these statements write, so a Unit can order a mixed
// batch by foreign key without knowing what any of them are.
const Table = "scope_axes"

// stmtForMask compiles the UPDATE for one dirty mask, once.
func stmtForMask(mask uint64) *runtime.Stmt {
	if st := updCache.Get(mask); st != nil {
		return st
	}
	set := make([]runtime.Frag, 0, nUpdatable+1)
	for i := 0; i < nUpdatable; i++ {
		if mask&(1<<uint(i)) != 0 {
			set = append(set, setFrags[i])
		}
	}
	where := make([]runtime.Frag, 0, 2)
	where = append(where, pkFrags[:]...)
	return updCache.Put(mask, runtime.SpliceSections(updatePrefix, []runtime.Section{
		{Lead: "", Sep: ", ", Frags: set},
		{Lead: " WHERE ", Sep: " AND ", Frags: where},
	}, ""))
}

// Update writes the assigned columns of one row.
//
// Assigning nothing is not an error and issues no statement — an UPDATE
// with an empty SET list is not valid SQL, and a caller looping over
// possibly-changed fields should not have to special-case the empty case.
func (m *Mut) Update(ctx context.Context, ex runtime.Executor) error {
	if m.dirty == 0 {
		return nil
	}
	st := stmtForMask(m.dirty)
	if st.Err != nil {
		// A malformed token stream is a code-generation bug. Executing it
		// would run a query whose filter is not the one that was asked for.
		return st.Err
	}
	args := make([]any, 0, st.NArg)
	for i := 0; i < nUpdatable; i++ {
		if m.dirty&(1<<uint(i)) == 0 {
			continue
		}
		switch i {
		case 0:
			args = append(args, m.row.CreatedAt)
		case 1:
			args = append(args, m.row.SortOrder)
		case 2:
			args = append(args, m.row.DisplayName)
		case 3:
			args = append(args, m.row.DefaultEffect)
		case 4:
			args = append(args, m.row.Status)
		case 5:
			args = append(args, m.row.Resolution)
		case 6:
			args = append(args, m.row.UiSchema)
		}
	}
	args = append(args, m.row.Code)
	n, err := ex.Exec(ctx, st.SQL, args)
	if err != nil {
		return err
	}
	if n == 0 {
		return runtime.ErrNoRow
	}
	m.dirty = 0
	return nil
}

var deleteSQL = runtime.SpliceSections(deletePrefix, []runtime.Section{
	{Lead: " WHERE ", Sep: " AND ", Frags: pkFrags[:]},
}, "").SQL

// Delete removes one row by primary key. A row that was already gone is
// runtime.ErrNoRow, not success: a caller deleting something that is not
// there usually has a bug, and swallowing it hides the bug.
func Delete(ctx context.Context, ex runtime.Executor, code string) error {
	n, err := ex.Exec(ctx, deleteSQL, []any{code})
	if err != nil {
		return err
	}
	if n == 0 {
		return runtime.ErrNoRow
	}
	return nil
}
