// Code generated by storm v1.1.0. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/storm/runtime"

	gaterquery "github.com/gsoultan/anubis/internal/gate/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanAxisRow)
	storm.RegisterScanner(scanNodeRow)
	storm.RegisterScanner(scanGrantRow)
	storm.RegisterScanner(scanGrantScopeRow)
	storm.RegisterScanner(scanRolePermissionRow)
	storm.RegisterScanner(scanPermissionRow)
	storm.RegisterScanner(scanIdentityRow)
	storm.RegisterScanner(scanRouteRow)
	storm.RegisterScanner(scanTenantRow)
	storm.RegisterScanner(scanCatalogVersionRow)
	storm.RegisterScanner(scanSessionIDRow)
	storm.RegisterStatement(`
SELECT code, default_effect, status, sort_order FROM scope_axes
WHERE status = 'active'`)
	storm.RegisterStatement(`
SELECT g.id::text AS id, g.identity_id::text AS identity_id,
       g.role_id::text AS role_id, g.self_scoped, g.valid_from, g.valid_until
FROM grants g
WHERE g.tenant_id = $1 AND g.revoked_at IS NULL`)
	storm.RegisterStatement(`
SELECT gs.grant_id::text AS grant_id, gs.axis_code,
       gs.scope_node_id::text AS scope_node_id, gs.inherit,
       gs.mode = 'exclude' AS exclude
FROM grant_scopes gs
WHERE gs.tenant_id = $1`)
	storm.RegisterStatement(`
SELECT id::text AS id FROM sessions
WHERE tenant_id = $1
  AND revoked_at IS NOT NULL
  AND revoked_at > now() - $2::text::interval`)
	storm.RegisterStatement(`
SELECT id::text AS id, parent_id::text AS parent_id FROM scope_nodes
WHERE tenant_id = $1`)
	storm.RegisterStatement(`
SELECT id::text AS id, slug FROM tenants WHERE status = 'active'`)
	storm.RegisterStatement(`
SELECT id::text AS id, token_epoch, status, assurance_level,
       (disabled_at IS NOT NULL OR anonymized_at IS NOT NULL) AS blocked
FROM identities
WHERE tenant_id = $1`)
	storm.RegisterStatement(`
SELECT p.key, p.risk, p.min_assurance, p.requires_amr,
       COALESCE(extract(epoch FROM p.max_auth_age), 0)::bigint AS max_auth_age_secs
FROM permissions p
WHERE p.tenant_id = $1 AND p.deprecated_at IS NULL`)
	storm.RegisterStatement(`
SELECT rp.id::text AS id, rp.priority, rp.effect, rp.path_pattern,
       rp.host_pattern, rp.methods, rp.scope_bindings,
       p.key AS permission_key, a.slug AS application_slug
FROM route_policies rp
JOIN applications a ON a.id = rp.application_id
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE rp.tenant_id = $1
ORDER BY a.slug, rp.priority`)
	storm.RegisterStatement(`
SELECT rpe.role_id::text AS role_id, p.key
FROM role_permissions_effective rpe
JOIN permissions p ON p.id = rpe.permission_id
WHERE p.tenant_id = $1 AND p.deprecated_at IS NULL`)
	storm.RegisterStatement(`
SELECT version, changed_at FROM catalog_version WHERE tenant_id = $1`)
}

func scanAxisRow(rv [][]byte, r *gaterquery.AxisRow, sl *runtime.Slab) error {
	r.Code = sl.Str(rv[0])
	r.DefaultEffect = sl.Str(rv[1])
	r.Status = sl.Str(rv[2])
	r.SortOrder = runtime.Int4(rv[3])
	return nil
}

func scanNodeRow(rv [][]byte, r *gaterquery.NodeRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.ParentID = runtime.NullText(rv[1], sl)
	return nil
}

func scanGrantRow(rv [][]byte, r *gaterquery.GrantRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.RoleID = sl.Str(rv[2])
	r.SelfScoped = runtime.Bool(rv[3])
	r.ValidFrom = runtime.Timestamptz(rv[4])
	r.ValidUntil = runtime.Nullable(rv[5], runtime.Timestamptz)
	return nil
}

func scanGrantScopeRow(rv [][]byte, r *gaterquery.GrantScopeRow, sl *runtime.Slab) error {
	r.GrantID = sl.Str(rv[0])
	r.AxisCode = sl.Str(rv[1])
	r.ScopeNodeID = sl.Str(rv[2])
	r.Inherit = runtime.Bool(rv[3])
	r.Exclude = runtime.Bool(rv[4])
	return nil
}

func scanRolePermissionRow(rv [][]byte, r *gaterquery.RolePermissionRow, sl *runtime.Slab) error {
	r.RoleID = sl.Str(rv[0])
	r.Key = sl.Str(rv[1])
	return nil
}

func scanPermissionRow(rv [][]byte, r *gaterquery.PermissionRow, sl *runtime.Slab) error {
	var decErr error
	r.Key = sl.Str(rv[0])
	r.Risk = sl.Str(rv[1])
	r.MinAssurance = runtime.Int2(rv[2])
	r.RequiresAmr, decErr = runtime.TextArray(rv[3], sl)
	if decErr != nil {
		return decErr
	}
	r.MaxAuthAgeSecs = runtime.Int8(rv[4])
	return nil
}

func scanIdentityRow(rv [][]byte, r *gaterquery.IdentityRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TokenEpoch = runtime.Int4(rv[1])
	r.Status = sl.Str(rv[2])
	r.AssuranceLevel = runtime.Int2(rv[3])
	r.Blocked = runtime.Bool(rv[4])
	return nil
}

func scanRouteRow(rv [][]byte, r *gaterquery.RouteRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.Priority = runtime.Int4(rv[1])
	r.Effect = sl.Str(rv[2])
	r.PathPattern = sl.Str(rv[3])
	r.HostPattern = runtime.NullText(rv[4], sl)
	r.Methods, decErr = runtime.TextArray(rv[5], sl)
	if decErr != nil {
		return decErr
	}
	r.ScopeBindings = runtime.JSON(runtime.JSONB(rv[6], sl))
	r.PermissionKey = runtime.NullText(rv[7], sl)
	r.ApplicationSlug = sl.Str(rv[8])
	return nil
}

func scanTenantRow(rv [][]byte, r *gaterquery.TenantRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.Slug = sl.Str(rv[1])
	return nil
}

func scanCatalogVersionRow(rv [][]byte, r *gaterquery.CatalogVersionRow, sl *runtime.Slab) error {
	r.Version = runtime.Int8(rv[0])
	r.ChangedAt = runtime.Timestamptz(rv[1])
	return nil
}

func scanSessionIDRow(rv [][]byte, r *gaterquery.SessionIDRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}
