// Code generated by storm (devel). DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/storm/runtime"

	platformrquery "github.com/gsoultan/anubis/internal/platform/database/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanAcquiredRow)
	storm.RegisterScanner(scanReleasedRow)
	storm.RegisterStatement(`
SELECT pg_advisory_unlock($1) AS released`)
	storm.RegisterStatement(`
SELECT pg_try_advisory_lock($1) AS acquired`)
}

func scanAcquiredRow(rv [][]byte, r *platformrquery.AcquiredRow, sl *runtime.Slab) error {
	r.Acquired = runtime.Bool(rv[0])
	return nil
}

func scanReleasedRow(rv [][]byte, r *platformrquery.ReleasedRow, sl *runtime.Slab) error {
	r.Released = runtime.Bool(rv[0])
	return nil
}
