// Code generated by storm v0.14.2. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/storm/runtime"

	auditrquery "github.com/gsoultan/anubis/internal/audit/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"audit_log": 0,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanDoneRow)
	storm.RegisterScanner(scanDecisionCountsRow)
	storm.RegisterScanner(scanReuseSignalRow)
	storm.RegisterStatement(`
SELECT (ensure_month_partitions('audit_log', 'occurred_at', 3) IS NULL) AS done`)
	storm.RegisterStatement(`
SELECT (ensure_month_partitions('refresh_tokens', 'expires_at', 3) IS NULL) AS done`)
	storm.RegisterStatement(`
SELECT (pg_advisory_xact_lock(hashtextextended('audit:' || $1::text, 0)) IS NULL) AS done`)
	storm.RegisterStatement(`
SELECT count(*) AS n,
       COALESCE(max(occurred_at), 'epoch'::timestamptz) AS latest
FROM audit_log
WHERE tenant_id = $1 AND action = 'token.reuse_detected'
  AND occurred_at > now() - interval '7 days'`)
	storm.RegisterStatement(`
SELECT count(*) FILTER (WHERE result = 'allow') AS allows,
       count(*) FILTER (WHERE result = 'deny')  AS denies
FROM audit_log
WHERE tenant_id = $1 AND action = 'authorize'
  AND occurred_at > now() - interval '24 hours'`)
}

func scanDoneRow(rv [][]byte, r *auditrquery.DoneRow, sl *runtime.Slab) error {
	r.Done = runtime.Bool(rv[0])
	return nil
}

func scanDecisionCountsRow(rv [][]byte, r *auditrquery.DecisionCountsRow, sl *runtime.Slab) error {
	r.Allows = runtime.Int8(rv[0])
	r.Denies = runtime.Int8(rv[1])
	return nil
}

func scanReuseSignalRow(rv [][]byte, r *auditrquery.ReuseSignalRow, sl *runtime.Slab) error {
	r.N = runtime.Int8(rv[0])
	r.Latest = runtime.Timestamptz(rv[1])
	return nil
}
