// Code generated by storm v0.15.0. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/anubis/internal/audit/adapter/postgres/rmodel"
)

// _assertAuditLogShape fails to compile if m0.AuditLog gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertAuditLogShape(m m0.AuditLog) {
	type shape m0.AuditLog
	_ = shape{
		m.OccurredAt,
		m.ID,
		m.TenantID,
		m.ActorID,
		m.TargetID,
		m.SessionID,
		m.Seq,
		m.Action,
		m.Result,
		m.ActorKind,
		m.IP,
		m.Detail,
		m.PrevHash,
		m.EntryHash,
	}
}
