// Command stormddl turns a change to the schema of record into a migration.
//
//	stormddl -check                 # fail if the model and the database differ
//	stormddl -write                 # emit the next numbered migration
//	stormddl                        # print the plan without writing anything
//
// The model is internal/platform/schema; migrations/ is what runs. The model
// is edited, the migration is reviewed, and nothing here applies anything —
// `anubisd migrate` does that, as it always has.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	platformschema "github.com/gsoultan/anubis/internal/platform/schema"
	"github.com/gsoultan/storm"
	"github.com/gsoultan/storm/migrate"
	"github.com/jackc/pgx/v5"
)

func main() {
	var (
		check = flag.Bool("check", false, "exit non-zero if the model and the database disagree")
		write = flag.Bool("write", false, "write the plan as the next migrations/ file")
		name  = flag.String("name", "model_change", "name for the written migration")
		dsn   = flag.String("dsn", os.Getenv("ANUBIS_DB_URL"), "database to diff against")
		dir   = flag.String("dir", "migrations", "migrations directory")
	)
	flag.Parse()

	if *dsn == "" {
		fail("no -dsn and no $ANUBIS_DB_URL")
	}
	model, err := storm.Build(platformschema.All()...)
	if err != nil {
		fail("the schema of record does not build: %v", err)
	}

	ctx := context.Background()
	conn, err := pgx.Connect(ctx, *dsn)
	if err != nil {
		fail("connect: %v", err)
	}
	defer conn.Close(ctx)

	plan, err := migrate.ForWith(ctx, conn, "public", model, migrate.Options{})
	if err != nil {
		fail("diff: %v", err)
	}

	if plan.Empty() {
		fmt.Println("ok: the schema of record matches the database")
		return
	}

	switch {
	case *check:
		fmt.Fprintf(os.Stderr,
			"FAIL: the schema of record and the database disagree.\n"+
				"Either the model changed and needs a migration (stormddl -write),\n"+
				"or a migration changed the database without the model following it.\n\n%s\n",
			plan.SQL())
		os.Exit(1)
	case *write:
		path, err := writeMigration(*dir, *name, plan)
		if err != nil {
			fail("write: %v", err)
		}
		fmt.Printf("wrote %s\n", path)
		// Deliberately NOT applied. A migration is reviewed before it runs;
		// that is the whole difference between this and an automigrate.
		fmt.Println("review it, then apply with: go run ./cmd/anubisd migrate")
	default:
		fmt.Println(plan.SQL())
	}
}

// writeMigration emits the next numbered file.
//
// Numbered from the directory rather than from a clock, so two people
// generating on different branches COLLIDE in git rather than silently
// interleaving — the same property migrations/ has always had.
func writeMigration(dir, name string, plan migrate.Plan) (string, error) {
	seq, err := nextSeq(dir)
	if err != nil {
		return "", err
	}
	slug := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			return r
		case r >= 'A' && r <= 'Z':
			return r + 32
		case r == ' ', r == '-', r == '_':
			return '_'
		}
		return -1
	}, name)

	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by cmd/stormddl from internal/platform/schema on %s.\n",
		time.Now().UTC().Format("2006-01-02"))
	b.WriteString("--\n-- Review before applying. The model is the source of truth; this file is\n")
	b.WriteString("-- what runs, and what the checksum in schema_migrations pins.\n")
	if plan.Destructive() {
		b.WriteString("--\n-- CONTAINS DESTRUCTIVE STEPS — read every one before this is applied to\n")
		b.WriteString("-- anything holding data.\n")
	}
	b.WriteString("\n")
	b.WriteString(plan.SQL())
	if !strings.HasSuffix(plan.SQL(), "\n") {
		b.WriteString("\n")
	}

	path := filepath.Join(dir, fmt.Sprintf("%04d_%s.sql", seq, slug))
	return path, os.WriteFile(path, []byte(b.String()), 0o644)
}

func nextSeq(dir string) (int, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0, err
	}
	max := 0
	for _, e := range entries {
		var n int
		if _, err := fmt.Sscanf(e.Name(), "%04d_", &n); err == nil && n > max {
			max = n
		}
	}
	return max + 1, nil
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "stormddl: "+format+"\n", args...)
	os.Exit(1)
}
