// Code generated by storm v0.15.0. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"context"
	"fmt"

	"github.com/gsoultan/anubis/internal/control/adapter/postgres/rgen/platformapikey"
	"github.com/gsoultan/anubis/internal/control/adapter/postgres/rgen/platformassignment"
	"github.com/gsoultan/anubis/internal/control/adapter/postgres/rgen/platformrefreshtoken"
	"github.com/gsoultan/anubis/internal/control/adapter/postgres/rgen/platformuser"
	"github.com/gsoultan/storm/runtime"

	controlrquery "github.com/gsoultan/anubis/internal/control/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"platform_users":          0,
	"platform_api_keys":       1,
	"platform_assignments":    2,
	"platform_refresh_tokens": 3,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// defaultChildLimit caps a relation load. Any constant is arbitrary — too
// low truncates a legitimate load, too high is the unbounded read the dba
// profile vetoes — so what is settled here is only the BEHAVIOUR on
// reaching it: an error, never a partial result. Override per plan with
// ChildLimit.
const defaultChildLimit = 1 << 20

// PlatformAPIKeyWithCreatedByRow is platform_api_keys with its CreatedBy loaded.
type PlatformAPIKeyWithCreatedByRow struct {
	platformapikey.Row
	// A pointer because the link is optional. nil means the row has no
	// CreatedBy, which is different from having one that failed to load.
	CreatedBy *platformuser.Row
}

type PlatformAPIKeyWithCreatedByQuery struct {
	q platformapikey.Query
}

// PlatformAPIKeyWithCreatedBy starts the plan.
func PlatformAPIKeyWithCreatedBy() PlatformAPIKeyWithCreatedByQuery {
	return PlatformAPIKeyWithCreatedByQuery{q: platformapikey.New()}
}

func (p PlatformAPIKeyWithCreatedByQuery) Where(ps ...platformapikey.Pred) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p PlatformAPIKeyWithCreatedByQuery) WhereIf(cond bool, pr platformapikey.Pred) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p PlatformAPIKeyWithCreatedByQuery) Any(ps ...platformapikey.Pred) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p PlatformAPIKeyWithCreatedByQuery) Not(pr platformapikey.Pred) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p PlatformAPIKeyWithCreatedByQuery) NotAny(ps ...platformapikey.Pred) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p PlatformAPIKeyWithCreatedByQuery) Order(ts ...platformapikey.Sort) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p PlatformAPIKeyWithCreatedByQuery) Limit(n int64) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p PlatformAPIKeyWithCreatedByQuery) Offset(n int64) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p PlatformAPIKeyWithCreatedByQuery) After(r PlatformAPIKeyWithCreatedByRow) PlatformAPIKeyWithCreatedByQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p PlatformAPIKeyWithCreatedByQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p PlatformAPIKeyWithCreatedByQuery) All(ctx context.Context, ex runtime.Executor) ([]PlatformAPIKeyWithCreatedByRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]PlatformAPIKeyWithCreatedByRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = PlatformAPIKeyWithCreatedByRow{Row: r}
		key, ok := r.CreatedBy.Get()
		if !ok {
			continue
		}
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := platformuser.New().Unordered().
		Where(platformuser.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key, ok := out[i].Row.CreatedBy.Get()
		if !ok {
			continue
		}
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "platform_api_keys", "platform_users")
		}
		out[i].CreatedBy = &targets[j]
	}
	return out, nil
}

// PlatformAPIKeyWithPlatformUserRow is platform_api_keys with its PlatformUser loaded.
type PlatformAPIKeyWithPlatformUserRow struct {
	platformapikey.Row
	PlatformUser platformuser.Row
}

type PlatformAPIKeyWithPlatformUserQuery struct {
	q platformapikey.Query
}

// PlatformAPIKeyWithPlatformUser starts the plan.
func PlatformAPIKeyWithPlatformUser() PlatformAPIKeyWithPlatformUserQuery {
	return PlatformAPIKeyWithPlatformUserQuery{q: platformapikey.New()}
}

func (p PlatformAPIKeyWithPlatformUserQuery) Where(ps ...platformapikey.Pred) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p PlatformAPIKeyWithPlatformUserQuery) WhereIf(cond bool, pr platformapikey.Pred) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p PlatformAPIKeyWithPlatformUserQuery) Any(ps ...platformapikey.Pred) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p PlatformAPIKeyWithPlatformUserQuery) Not(pr platformapikey.Pred) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p PlatformAPIKeyWithPlatformUserQuery) NotAny(ps ...platformapikey.Pred) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p PlatformAPIKeyWithPlatformUserQuery) Order(ts ...platformapikey.Sort) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p PlatformAPIKeyWithPlatformUserQuery) Limit(n int64) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p PlatformAPIKeyWithPlatformUserQuery) Offset(n int64) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p PlatformAPIKeyWithPlatformUserQuery) After(r PlatformAPIKeyWithPlatformUserRow) PlatformAPIKeyWithPlatformUserQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p PlatformAPIKeyWithPlatformUserQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p PlatformAPIKeyWithPlatformUserQuery) All(ctx context.Context, ex runtime.Executor) ([]PlatformAPIKeyWithPlatformUserRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]PlatformAPIKeyWithPlatformUserRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = PlatformAPIKeyWithPlatformUserRow{Row: r}
		key := r.PlatformUserID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := platformuser.New().Unordered().
		Where(platformuser.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].Row.PlatformUserID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "platform_api_keys", "platform_users")
		}
		out[i].PlatformUser = targets[j]
	}
	return out, nil
}

// PlatformAssignmentWithGrantedByRow is platform_assignments with its GrantedBy loaded.
type PlatformAssignmentWithGrantedByRow struct {
	platformassignment.Row
	// A pointer because the link is optional. nil means the row has no
	// GrantedBy, which is different from having one that failed to load.
	GrantedBy *platformuser.Row
}

type PlatformAssignmentWithGrantedByQuery struct {
	q platformassignment.Query
}

// PlatformAssignmentWithGrantedBy starts the plan.
func PlatformAssignmentWithGrantedBy() PlatformAssignmentWithGrantedByQuery {
	return PlatformAssignmentWithGrantedByQuery{q: platformassignment.New()}
}

func (p PlatformAssignmentWithGrantedByQuery) Where(ps ...platformassignment.Pred) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p PlatformAssignmentWithGrantedByQuery) WhereIf(cond bool, pr platformassignment.Pred) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p PlatformAssignmentWithGrantedByQuery) Any(ps ...platformassignment.Pred) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p PlatformAssignmentWithGrantedByQuery) Not(pr platformassignment.Pred) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p PlatformAssignmentWithGrantedByQuery) NotAny(ps ...platformassignment.Pred) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p PlatformAssignmentWithGrantedByQuery) Order(ts ...platformassignment.Sort) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p PlatformAssignmentWithGrantedByQuery) Limit(n int64) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p PlatformAssignmentWithGrantedByQuery) Offset(n int64) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p PlatformAssignmentWithGrantedByQuery) After(r PlatformAssignmentWithGrantedByRow) PlatformAssignmentWithGrantedByQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p PlatformAssignmentWithGrantedByQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p PlatformAssignmentWithGrantedByQuery) All(ctx context.Context, ex runtime.Executor) ([]PlatformAssignmentWithGrantedByRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]PlatformAssignmentWithGrantedByRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = PlatformAssignmentWithGrantedByRow{Row: r}
		key, ok := r.GrantedBy.Get()
		if !ok {
			continue
		}
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := platformuser.New().Unordered().
		Where(platformuser.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key, ok := out[i].Row.GrantedBy.Get()
		if !ok {
			continue
		}
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "platform_assignments", "platform_users")
		}
		out[i].GrantedBy = &targets[j]
	}
	return out, nil
}

// PlatformAssignmentWithOperatorRow is platform_assignments with its Operator loaded.
type PlatformAssignmentWithOperatorRow struct {
	platformassignment.Row
	Operator platformuser.Row
}

type PlatformAssignmentWithOperatorQuery struct {
	q platformassignment.Query
}

// PlatformAssignmentWithOperator starts the plan.
func PlatformAssignmentWithOperator() PlatformAssignmentWithOperatorQuery {
	return PlatformAssignmentWithOperatorQuery{q: platformassignment.New()}
}

func (p PlatformAssignmentWithOperatorQuery) Where(ps ...platformassignment.Pred) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p PlatformAssignmentWithOperatorQuery) WhereIf(cond bool, pr platformassignment.Pred) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p PlatformAssignmentWithOperatorQuery) Any(ps ...platformassignment.Pred) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p PlatformAssignmentWithOperatorQuery) Not(pr platformassignment.Pred) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p PlatformAssignmentWithOperatorQuery) NotAny(ps ...platformassignment.Pred) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p PlatformAssignmentWithOperatorQuery) Order(ts ...platformassignment.Sort) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p PlatformAssignmentWithOperatorQuery) Limit(n int64) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p PlatformAssignmentWithOperatorQuery) Offset(n int64) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p PlatformAssignmentWithOperatorQuery) After(r PlatformAssignmentWithOperatorRow) PlatformAssignmentWithOperatorQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p PlatformAssignmentWithOperatorQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p PlatformAssignmentWithOperatorQuery) All(ctx context.Context, ex runtime.Executor) ([]PlatformAssignmentWithOperatorRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]PlatformAssignmentWithOperatorRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = PlatformAssignmentWithOperatorRow{Row: r}
		key := r.OperatorID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := platformuser.New().Unordered().
		Where(platformuser.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].Row.OperatorID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "platform_assignments", "platform_users")
		}
		out[i].Operator = targets[j]
	}
	return out, nil
}

// PlatformRefreshTokenWithPlatformUserRow is platform_refresh_tokens with its PlatformUser loaded.
type PlatformRefreshTokenWithPlatformUserRow struct {
	platformrefreshtoken.Row
	PlatformUser platformuser.Row
}

type PlatformRefreshTokenWithPlatformUserQuery struct {
	q platformrefreshtoken.Query
}

// PlatformRefreshTokenWithPlatformUser starts the plan.
func PlatformRefreshTokenWithPlatformUser() PlatformRefreshTokenWithPlatformUserQuery {
	return PlatformRefreshTokenWithPlatformUserQuery{q: platformrefreshtoken.New()}
}

func (p PlatformRefreshTokenWithPlatformUserQuery) Where(ps ...platformrefreshtoken.Pred) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p PlatformRefreshTokenWithPlatformUserQuery) WhereIf(cond bool, pr platformrefreshtoken.Pred) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p PlatformRefreshTokenWithPlatformUserQuery) Any(ps ...platformrefreshtoken.Pred) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p PlatformRefreshTokenWithPlatformUserQuery) Not(pr platformrefreshtoken.Pred) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p PlatformRefreshTokenWithPlatformUserQuery) NotAny(ps ...platformrefreshtoken.Pred) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p PlatformRefreshTokenWithPlatformUserQuery) Order(ts ...platformrefreshtoken.Sort) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p PlatformRefreshTokenWithPlatformUserQuery) Limit(n int64) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p PlatformRefreshTokenWithPlatformUserQuery) Offset(n int64) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p PlatformRefreshTokenWithPlatformUserQuery) After(r PlatformRefreshTokenWithPlatformUserRow) PlatformRefreshTokenWithPlatformUserQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p PlatformRefreshTokenWithPlatformUserQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p PlatformRefreshTokenWithPlatformUserQuery) All(ctx context.Context, ex runtime.Executor) ([]PlatformRefreshTokenWithPlatformUserRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]PlatformRefreshTokenWithPlatformUserRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = PlatformRefreshTokenWithPlatformUserRow{Row: r}
		key := r.PlatformUserID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := platformuser.New().Unordered().
		Where(platformuser.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].Row.PlatformUserID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "platform_refresh_tokens", "platform_users")
		}
		out[i].PlatformUser = targets[j]
	}
	return out, nil
}

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanAPIKeyLookupRow)
	storm.RegisterScanner(scanAPIKeyListRow)
	storm.RegisterScanner(scanAssignmentRow)
	storm.RegisterScanner(scanPresentRow)
	storm.RegisterScanner(scanPlatformUserRow)
	storm.RegisterScanner(scanPlatformUserListRow)
	storm.RegisterScanner(scanIDRow)
	storm.RegisterScanner(scanRefreshRow)
	storm.RegisterStatement(`
DELETE FROM platform_refresh_tokens
WHERE expires_at < now() - interval '1 day'`)
	storm.RegisterStatement(`
INSERT INTO platform_refresh_tokens (id, platform_user_id, family_id, token_hash, expires_at)
SELECT g.u, $1, g.u, $2, $3 FROM (SELECT uuidv7() AS u) g
RETURNING id::text AS id`)
	storm.RegisterStatement(`
SELECT EXISTS (
    SELECT 1 FROM platform_assignments
     WHERE tenant_id IS NULL AND role = 'owner' AND revoked_at IS NULL
) AS present`)
	storm.RegisterStatement(`
SELECT a.id::text AS id, a.operator_id::text AS operator_id,
       COALESCE(a.tenant_id::text, '') AS tenant_id,
       '' AS tenant_slug,
       a.role, COALESCE(a.granted_by::text, '') AS granted_by,
       a.reason, a.valid_until, a.revoked_at, a.created_at
  FROM platform_assignments a
  JOIN platform_users u ON u.id = a.operator_id
 WHERE a.operator_id = $1
   AND a.revoked_at IS NULL
   AND u.status = 'active'
 ORDER BY a.tenant_id NULLS FIRST`)
	storm.RegisterStatement(`
SELECT a.id::text AS id, a.operator_id::text AS operator_id,
       COALESCE(a.tenant_id::text, '') AS tenant_id,
       COALESCE(t.slug, '') AS tenant_slug,
       a.role, COALESCE(a.granted_by::text, '') AS granted_by,
       a.reason, a.valid_until, a.revoked_at, a.created_at
  FROM platform_assignments a
  LEFT JOIN tenants t ON t.id = a.tenant_id
 WHERE a.revoked_at IS NULL
 ORDER BY a.operator_id, a.tenant_id NULLS FIRST`)
	storm.RegisterStatement(`
SELECT id::text AS id, platform_user_id::text AS platform_user_id,
       family_id::text AS family_id, created_at, expires_at, used_at, revoked_at
FROM platform_refresh_tokens
WHERE token_hash = $1`)
	storm.RegisterStatement(`
SELECT id::text AS id, username, email, password_hash, status, token_epoch,
       last_login_at, disabled_at, created_at,
       totp_secret_enc, totp_enrolled_at, totp_last_step
  FROM platform_users WHERE lower(username) = lower($1)`)
	storm.RegisterStatement(`
SELECT id::text AS id, username, email, status, token_epoch, last_login_at,
       disabled_at, created_at, totp_enrolled_at
  FROM platform_users
 WHERE ($1::text = '' OR username ILIKE '%' || $1::text || '%')
   AND ($2::text = '' OR username > $2::text)
 ORDER BY username
 LIMIT $3`)
	storm.RegisterStatement(`
SELECT k.id::text AS id, k.platform_user_id::text AS platform_user_id,
       k.secret_hash, k.expires_at, k.revoked_at,
       u.username, u.status AS owner_status, u.token_epoch
FROM platform_api_keys k
JOIN platform_users u ON u.id = k.platform_user_id
WHERE k.lookup = $1 AND k.revoked_at IS NULL`)
	storm.RegisterStatement(`
SELECT k.id::text AS id, k.platform_user_id::text AS platform_user_id, u.username,
       k.label, k.lookup, k.created_at, k.last_used_at, k.expires_at, k.revoked_at
FROM platform_api_keys k
JOIN platform_users u ON u.id = k.platform_user_id
ORDER BY k.created_at DESC`)
	storm.RegisterStatement(`
UPDATE platform_api_keys SET last_used_at = now() WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE platform_api_keys SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL`)
	storm.RegisterStatement(`
UPDATE platform_assignments
   SET revoked_at = now(), updated_at = now()
 WHERE id = $1 AND revoked_at IS NULL`)
	storm.RegisterStatement(`
UPDATE platform_refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL`)
	storm.RegisterStatement(`
UPDATE platform_refresh_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL`)
	storm.RegisterStatement(`
UPDATE platform_users
   SET status = $2, updated_at = now(),
       disabled_at = CASE WHEN $2::text = 'disabled' THEN now() ELSE NULL END,
       token_epoch = token_epoch + CASE WHEN $2::text = 'disabled' THEN 1 ELSE 0 END
 WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE platform_users
   SET totp_enrolled_at = now(), totp_last_step = $2, updated_at = now()
 WHERE id = $1 AND totp_secret_enc IS NOT NULL`)
	storm.RegisterStatement(`
UPDATE platform_users
   SET totp_last_step = $2, updated_at = now()
 WHERE id = $1 AND totp_last_step < $2`)
	storm.RegisterStatement(`
UPDATE platform_users
   SET totp_secret_enc = $2, updated_at = now()
 WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE platform_users
   SET totp_secret_enc = NULL, totp_enrolled_at = NULL, totp_last_step = 0,
       updated_at = now()
 WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE platform_users SET last_login_at = now() WHERE id = $1`)
}

func scanAPIKeyLookupRow(rv [][]byte, r *controlrquery.APIKeyLookupRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.PlatformUserID = sl.Str(rv[1])
	r.SecretHash = sl.Str(rv[2])
	r.ExpiresAt = runtime.Timestamptz(rv[3])
	r.RevokedAt = runtime.Nullable(rv[4], runtime.Timestamptz)
	r.Username = sl.Str(rv[5])
	r.OwnerStatus = sl.Str(rv[6])
	r.TokenEpoch = runtime.Int4(rv[7])
	return nil
}

func scanAPIKeyListRow(rv [][]byte, r *controlrquery.APIKeyListRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.PlatformUserID = sl.Str(rv[1])
	r.Username = sl.Str(rv[2])
	r.Label = sl.Str(rv[3])
	r.Lookup = sl.Str(rv[4])
	r.CreatedAt = runtime.Timestamptz(rv[5])
	r.LastUsedAt = runtime.Nullable(rv[6], runtime.Timestamptz)
	r.ExpiresAt = runtime.Timestamptz(rv[7])
	r.RevokedAt = runtime.Nullable(rv[8], runtime.Timestamptz)
	return nil
}

func scanAssignmentRow(rv [][]byte, r *controlrquery.AssignmentRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.OperatorID = sl.Str(rv[1])
	r.TenantID = sl.Str(rv[2])
	r.TenantSlug = sl.Str(rv[3])
	r.Role = sl.Str(rv[4])
	r.GrantedBy = sl.Str(rv[5])
	r.Reason = sl.Str(rv[6])
	r.ValidUntil = runtime.Nullable(rv[7], runtime.Timestamptz)
	r.RevokedAt = runtime.Nullable(rv[8], runtime.Timestamptz)
	r.CreatedAt = runtime.Timestamptz(rv[9])
	return nil
}

func scanPresentRow(rv [][]byte, r *controlrquery.PresentRow, sl *runtime.Slab) error {
	r.Present = runtime.Bool(rv[0])
	return nil
}

func scanPlatformUserRow(rv [][]byte, r *controlrquery.PlatformUserRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.Username = sl.Str(rv[1])
	r.Email = runtime.NullText(rv[2], sl)
	r.PasswordHash = sl.Str(rv[3])
	r.Status = sl.Str(rv[4])
	r.TokenEpoch = runtime.Int4(rv[5])
	r.LastLoginAt = runtime.Nullable(rv[6], runtime.Timestamptz)
	r.DisabledAt = runtime.Nullable(rv[7], runtime.Timestamptz)
	r.CreatedAt = runtime.Timestamptz(rv[8])
	r.TotpSecretEnc = runtime.Bytes(rv[9])
	r.TotpEnrolledAt = runtime.Nullable(rv[10], runtime.Timestamptz)
	r.TotpLastStep = runtime.Int8(rv[11])
	return nil
}

func scanPlatformUserListRow(rv [][]byte, r *controlrquery.PlatformUserListRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.Username = sl.Str(rv[1])
	r.Email = runtime.NullText(rv[2], sl)
	r.Status = sl.Str(rv[3])
	r.TokenEpoch = runtime.Int4(rv[4])
	r.LastLoginAt = runtime.Nullable(rv[5], runtime.Timestamptz)
	r.DisabledAt = runtime.Nullable(rv[6], runtime.Timestamptz)
	r.CreatedAt = runtime.Timestamptz(rv[7])
	r.TotpEnrolledAt = runtime.Nullable(rv[8], runtime.Timestamptz)
	return nil
}

func scanIDRow(rv [][]byte, r *controlrquery.IDRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}

func scanRefreshRow(rv [][]byte, r *controlrquery.RefreshRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.PlatformUserID = sl.Str(rv[1])
	r.FamilyID = sl.Str(rv[2])
	r.CreatedAt = runtime.Timestamptz(rv[3])
	r.ExpiresAt = runtime.Timestamptz(rv[4])
	r.UsedAt = runtime.Nullable(rv[5], runtime.Timestamptz)
	r.RevokedAt = runtime.Nullable(rv[6], runtime.Timestamptz)
	return nil
}
