// Code generated by storm v1.1.0. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/anubis/internal/control/adapter/postgres/rmodel"
)

// _assertPlatformAPIKeyShape fails to compile if m0.PlatformAPIKey gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertPlatformAPIKeyShape(m m0.PlatformAPIKey) {
	type shape m0.PlatformAPIKey
	_ = shape{
		m.ID,
		m.PlatformUser,
		m.Label,
		m.Lookup,
		m.SecretHash,
		m.CreatedAt,
		m.CreatedBy,
		m.LastUsedAt,
		m.ExpiresAt,
		m.RevokedAt,
	}
}

// _assertPlatformAssignmentShape fails to compile if m0.PlatformAssignment gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertPlatformAssignmentShape(m m0.PlatformAssignment) {
	type shape m0.PlatformAssignment
	_ = shape{
		m.Model,
		m.Operator,
		m.TenantID,
		m.Role,
		m.GrantedBy,
		m.Reason,
		m.ValidUntil,
		m.RevokedAt,
	}
}

// _assertPlatformRefreshTokenShape fails to compile if m0.PlatformRefreshToken gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertPlatformRefreshTokenShape(m m0.PlatformRefreshToken) {
	type shape m0.PlatformRefreshToken
	_ = shape{
		m.ID,
		m.PlatformUser,
		m.FamilyID,
		m.TokenHash,
		m.CreatedAt,
		m.ExpiresAt,
		m.UsedAt,
		m.RevokedAt,
	}
}

// _assertPlatformUserShape fails to compile if m0.PlatformUser gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertPlatformUserShape(m m0.PlatformUser) {
	type shape m0.PlatformUser
	_ = shape{
		m.Model,
		m.Username,
		m.Email,
		m.PasswordHash,
		m.Status,
		m.TokenEpoch,
		m.LastLoginAt,
		m.DisabledAt,
		m.TotpSecretEnc,
		m.TotpEnrolledAt,
		m.TotpLastStep,
	}
}
