#!/usr/bin/env bash
# ADR-0009 (amended 2026-08-25): SQL lives in db/queries/<context>/*.sql,
# migrations/*.sql, or a context's designated rquery package — never anywhere
# else in hand-written Go.
set -euo pipefail
cd "$(dirname "$0")/../.."
# Two patterns: quoted SQL on one line, and multi-line backtick SQL (whose
# body puts the keyword at column 0). The second is what keeps storm.SQL
# declarations from quietly spreading beyond rquery.
hits=$(grep -rn --include='*.go' -E \
  '("(SELECT|INSERT INTO|UPDATE [a-z_]+ SET|DELETE FROM)[ "]|^(SELECT|INSERT INTO|UPDATE [a-z_]+ SET|DELETE FROM) )' \
  cmd internal pkg 2>/dev/null \
  | grep -v '/adapter/postgres/gen/' \
  | grep -v '/adapter/postgres/rgen/' \
  | grep -v '/adapter/postgres/rquery/' \
  | grep -v '\.sql\.go:' \
  | grep -v 'internal/platform/migrate/' \
  | grep -v 'internal/scope/adapter/feed/' \
  | grep -v '_test.go' || true)
# Documented exemptions, all in ADR-0009:
#   platform/migrate      — the hand-written runner (ADR-0002) executes SQL
#                           before the schema it would be generated against
#                           exists.
#   scope/adapter/feed    — reads FOREIGN databases (sync sources). Their
#                           schemas are unknown at build time, so they cannot
#                           be compile-checked; identifiers are validated and
#                           quoted instead.
#   adapter/postgres/rquery — THE designated home for a context's raw SQL as
#                           storm.SQL[T] declarations, PREPAREd against the
#                           live schema at generation time (ADR-0009 §5).
#   adapter/postgres/gen, /rgen — generated by sqlc / storm, not hand-written.
if [ -n "$hits" ]; then
  echo "FAIL: SQL string literals in hand-written Go:" >&2
  echo "$hits" >&2
  exit 1
fi
echo "ok: no SQL in hand-written Go outside designated homes"
