#!/usr/bin/env bash
# ADR-0009 (§8, 2026-09-18): SQL lives in migrations/*.sql or a context's
# designated rquery package — never anywhere else in hand-written Go. There is
# no db/queries/ any more; sqlc is gone.
set -euo pipefail
cd "$(dirname "$0")/../.."
# Two patterns: quoted SQL on one line, and multi-line backtick SQL (whose
# body puts the keyword at column 0). The second is what keeps storm.SQL
# declarations from quietly spreading beyond rquery.
hits=$(grep -rn --include='*.go' -E \
  '("(SELECT|INSERT INTO|UPDATE [a-z_]+ SET|DELETE FROM)[ "]|^(SELECT|INSERT INTO|UPDATE [a-z_]+ SET|DELETE FROM) )' \
  cmd internal pkg 2>/dev/null \
  | grep -v '/rgen/' \
  | grep -v '/rquery/' \
  | grep -v 'internal/platform/schema/' \
  | grep -v '\.sql\.go:' \
  | grep -v 'internal/platform/migrate/' \
  | grep -v 'internal/scope/adapter/feed/' \
  | grep -v '_test.go' || true)
# Documented exemptions, all in ADR-0009:
#   platform/migrate      — the hand-written runner (ADR-0002) executes SQL
#                           before the schema it would be generated against
#                           exists.
#   scope/adapter/feed    — reads FOREIGN databases (sync sources). Their
#                           schemas are unknown at build time, so they cannot
#                           be compile-checked; identifiers are validated and
#                           quoted instead.
#   adapter/postgres/rquery — THE designated home for a context's raw SQL as
#                           storm.SQL[T] declarations, PREPAREd against the
#                           live schema at generation time (ADR-0009 §5).
#   adapter/postgres/rgen — generated by storm, not hand-written.
#   (There was a /gen/ exemption for sqlc's output. sqlc is gone, nothing
#   under cmd/internal/pkg is named gen/ any more, and buf writes to the
#   root gen/go this script never scans — so it matched nothing, and a
#   dead exemption is a hole waiting for somebody's new gen/ directory.)
#
#   internal/platform/schema — the SCHEMA OF RECORD. It declares the database's
#   functions, view and triggers, whose bodies are PL/pgSQL and SQL by
#   definition; a schema that could not hold them would not describe this
#   database. cmd/stormddl turns a change here into a reviewed migration, so
#   the SQL still lands in migrations/ before it runs.
#
# The patterns match any rquery/, gen/ or rgen/ directory rather than only the
# ones under adapter/postgres: the TECHNICAL context's designated home is
# internal/platform/database/rquery, because it has no adapter/postgres and its
# two statements are advisory locks that belong to no table. The rule ADR-0009
# states is "one designated package per context", not "one path shape".
if [ -n "$hits" ]; then
  echo "FAIL: SQL string literals in hand-written Go:" >&2
  echo "$hits" >&2
  exit 1
fi
echo "ok: no SQL in hand-written Go outside designated homes"
