// Code generated by storm v0.16.0. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"context"
	"fmt"

	"github.com/gsoultan/anubis/internal/tenancy/adapter/postgres/rgen/application"
	"github.com/gsoultan/anubis/internal/tenancy/adapter/postgres/rgen/authpage"
	"github.com/gsoultan/anubis/internal/tenancy/adapter/postgres/rgen/catalogversion"
	"github.com/gsoultan/anubis/internal/tenancy/adapter/postgres/rgen/tenant"
	"github.com/gsoultan/storm/runtime"

	tenancyrquery "github.com/gsoultan/anubis/internal/tenancy/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"tenants":         0,
	"applications":    1,
	"auth_pages":      2,
	"catalog_version": 3,
	"route_policies":  4,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// defaultChildLimit caps a relation load. Any constant is arbitrary — too
// low truncates a legitimate load, too high is the unbounded read the dba
// profile vetoes — so what is settled here is only the BEHAVIOUR on
// reaching it: an error, never a partial result. Override per plan with
// ChildLimit.
const defaultChildLimit = 1 << 20

// ApplicationWithTenantRow is applications with its Tenant loaded.
type ApplicationWithTenantRow struct {
	application.Row
	Tenant tenant.Row
}

type ApplicationWithTenantQuery struct {
	q application.Query
}

// ApplicationWithTenant starts the plan.
func ApplicationWithTenant() ApplicationWithTenantQuery {
	return ApplicationWithTenantQuery{q: application.New()}
}

func (p ApplicationWithTenantQuery) Where(ps ...application.Pred) ApplicationWithTenantQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p ApplicationWithTenantQuery) WhereIf(cond bool, pr application.Pred) ApplicationWithTenantQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p ApplicationWithTenantQuery) Any(ps ...application.Pred) ApplicationWithTenantQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p ApplicationWithTenantQuery) Not(pr application.Pred) ApplicationWithTenantQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p ApplicationWithTenantQuery) NotAny(ps ...application.Pred) ApplicationWithTenantQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p ApplicationWithTenantQuery) Order(ts ...application.Sort) ApplicationWithTenantQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p ApplicationWithTenantQuery) Limit(n int64) ApplicationWithTenantQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p ApplicationWithTenantQuery) Offset(n int64) ApplicationWithTenantQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p ApplicationWithTenantQuery) After(r ApplicationWithTenantRow) ApplicationWithTenantQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p ApplicationWithTenantQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p ApplicationWithTenantQuery) All(ctx context.Context, ex runtime.Executor) ([]ApplicationWithTenantRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]ApplicationWithTenantRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = ApplicationWithTenantRow{Row: r}
		key := r.TenantID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := tenant.New().Unordered().
		Where(tenant.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].Row.TenantID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "applications", "tenants")
		}
		out[i].Tenant = targets[j]
	}
	return out, nil
}

// AuthPageWithTenantRow is auth_pages with its Tenant loaded.
type AuthPageWithTenantRow struct {
	authpage.Row
	Tenant tenant.Row
}

type AuthPageWithTenantQuery struct {
	q authpage.Query
}

// AuthPageWithTenant starts the plan.
func AuthPageWithTenant() AuthPageWithTenantQuery { return AuthPageWithTenantQuery{q: authpage.New()} }

func (p AuthPageWithTenantQuery) Where(ps ...authpage.Pred) AuthPageWithTenantQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p AuthPageWithTenantQuery) WhereIf(cond bool, pr authpage.Pred) AuthPageWithTenantQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p AuthPageWithTenantQuery) Any(ps ...authpage.Pred) AuthPageWithTenantQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p AuthPageWithTenantQuery) Not(pr authpage.Pred) AuthPageWithTenantQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p AuthPageWithTenantQuery) NotAny(ps ...authpage.Pred) AuthPageWithTenantQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p AuthPageWithTenantQuery) Order(ts ...authpage.Sort) AuthPageWithTenantQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p AuthPageWithTenantQuery) Limit(n int64) AuthPageWithTenantQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p AuthPageWithTenantQuery) Offset(n int64) AuthPageWithTenantQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p AuthPageWithTenantQuery) After(r AuthPageWithTenantRow) AuthPageWithTenantQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p AuthPageWithTenantQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p AuthPageWithTenantQuery) All(ctx context.Context, ex runtime.Executor) ([]AuthPageWithTenantRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]AuthPageWithTenantRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = AuthPageWithTenantRow{Row: r}
		key := r.TenantID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := tenant.New().Unordered().
		Where(tenant.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].Row.TenantID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "auth_pages", "tenants")
		}
		out[i].Tenant = targets[j]
	}
	return out, nil
}

// CatalogVersionWithTenantRow is catalog_version with its Tenant loaded.
type CatalogVersionWithTenantRow struct {
	catalogversion.Row
	Tenant tenant.Row
}

type CatalogVersionWithTenantQuery struct {
	q catalogversion.Query
}

// CatalogVersionWithTenant starts the plan.
func CatalogVersionWithTenant() CatalogVersionWithTenantQuery {
	return CatalogVersionWithTenantQuery{q: catalogversion.New()}
}

func (p CatalogVersionWithTenantQuery) Where(ps ...catalogversion.Pred) CatalogVersionWithTenantQuery {
	p.q = p.q.Where(ps...)
	return p
}

func (p CatalogVersionWithTenantQuery) WhereIf(cond bool, pr catalogversion.Pred) CatalogVersionWithTenantQuery {
	p.q = p.q.WhereIf(cond, pr)
	return p
}

func (p CatalogVersionWithTenantQuery) Any(ps ...catalogversion.Pred) CatalogVersionWithTenantQuery {
	p.q = p.q.Any(ps...)
	return p
}

func (p CatalogVersionWithTenantQuery) Not(pr catalogversion.Pred) CatalogVersionWithTenantQuery {
	p.q = p.q.Not(pr)
	return p
}

func (p CatalogVersionWithTenantQuery) NotAny(ps ...catalogversion.Pred) CatalogVersionWithTenantQuery {
	p.q = p.q.NotAny(ps...)
	return p
}

func (p CatalogVersionWithTenantQuery) Order(ts ...catalogversion.Sort) CatalogVersionWithTenantQuery {
	p.q = p.q.Order(ts...)
	return p
}

func (p CatalogVersionWithTenantQuery) Limit(n int64) CatalogVersionWithTenantQuery {
	p.q = p.q.Limit(n)
	return p
}

func (p CatalogVersionWithTenantQuery) Offset(n int64) CatalogVersionWithTenantQuery {
	p.q = p.q.Offset(n)
	return p
}

// After pages the PARENTS past one already seen — keyset pagination over
// the plan. It takes the plan's row type, so the cursor is a row you
// actually received rather than one you had to unwrap.
func (p CatalogVersionWithTenantQuery) After(r CatalogVersionWithTenantRow) CatalogVersionWithTenantQuery {
	p.q = p.q.After(r.Row)
	return p
}

// Err reports a parent query that outgrew its buffers or was given a
// mixed ordering to page. Terminals return it too; this is for checking
// a composed plan before running it.
func (p CatalogVersionWithTenantQuery) Err() error { return p.q.Err() }

// All runs the plan in exactly TWO round trips. Distinct parent keys are
// de-duplicated before the second, so a thousand rows pointing at three
// orgs fetch three orgs.
func (p CatalogVersionWithTenantQuery) All(ctx context.Context, ex runtime.Executor) ([]CatalogVersionWithTenantRow, error) {
	parents, err := p.q.All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	if len(parents) == 0 {
		return nil, nil
	}
	out := make([]CatalogVersionWithTenantRow, len(parents))
	seen := make(map[[16]byte]bool, len(parents))
	ids := make([][16]byte, 0, len(parents))
	for i, r := range parents {
		out[i] = CatalogVersionWithTenantRow{Row: r}
		key := r.TenantID
		if !seen[key] {
			seen[key] = true
			ids = append(ids, key)
		}
	}
	if len(ids) == 0 {
		return out, nil
	}
	targets, err := tenant.New().Unordered().
		Where(tenant.ID.In(ids...)).
		Limit(int64(len(ids))).
		All(ctx, ex, nil)
	if err != nil {
		return nil, err
	}
	by := make(map[[16]byte]int, len(targets))
	for i := range targets {
		by[targets[i].ID] = i
	}
	for i := range out {
		key := out[i].Row.TenantID
		j, ok := by[key]
		if !ok {
			// A foreign key pointing at a row that is not there. The database
			// forbids it, so reaching this means the constraint was dropped.
			return nil, fmt.Errorf("storm: %s references a missing %s row", "catalog_version", "tenants")
		}
		out[i].Tenant = targets[j]
	}
	return out, nil
}

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanApplicationWithSecsRow)
	storm.RegisterScanner(scanApplicationRow)
	storm.RegisterScanner(scanCreatedApplicationRow)
	storm.RegisterScanner(scanManifestVersionRow)
	storm.RegisterScanner(scanRoutePolicyRow)
	storm.RegisterScanner(scanAuthPageRow)
	storm.RegisterScanner(scanResolvedPageRow)
	storm.RegisterScanner(scanSigninPageRow)
	storm.RegisterScanner(scanDoneRow)
	storm.RegisterScanner(scanCountRow)
	storm.RegisterScanner(scanTenantStatsRow)
	storm.RegisterStatement(`
DELETE FROM auth_pages
WHERE id = $1 AND tenant_id = $2 AND NOT is_default`)
	storm.RegisterStatement(`
DELETE FROM route_policies WHERE application_id = $1`)
	storm.RegisterStatement(`
INSERT INTO applications (tenant_id, slug, name, kind, redirect_uris,
                          post_logout_redirect_uris, backchannel_logout_uri,
                          token_format, client_secret_hash,
                          access_token_ttl, refresh_token_ttl)
VALUES ($1, $2, $3, $4, $5::text[], $6::text[], nullif($7, ''), $8,
        nullif($9, ''), $10::text::interval, $11::text::interval)
RETURNING id::text AS id, manifest_version`)
	storm.RegisterStatement(`
INSERT INTO signin_pages (tenant_id, config, updated_at)
VALUES ($1, $2::jsonb, now())
ON CONFLICT (tenant_id) DO UPDATE
    SET config = EXCLUDED.config, updated_at = now()`)
	storm.RegisterStatement(`
SELECT
       id::text AS id, tenant_id::text AS tenant_id, slug, name, kind, status,
       redirect_uris, post_logout_redirect_uris, backchannel_logout_uri,
       token_format, client_secret_hash, manifest_version,
       access_token_ttl::text AS access_token_ttl,
       refresh_token_ttl::text AS refresh_token_ttl
FROM applications
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
SELECT
       id::text AS id, tenant_id::text AS tenant_id, slug, name, kind, status,
       redirect_uris, post_logout_redirect_uris, backchannel_logout_uri,
       token_format, client_secret_hash, manifest_version,
       access_token_ttl::text AS access_token_ttl,
       refresh_token_ttl::text AS refresh_token_ttl
FROM applications
WHERE tenant_id = $1
  AND ($2::text = '' OR slug ILIKE '%' || $2::text || '%' OR name ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR slug > $3::text)
ORDER BY slug
LIMIT $4`)
	storm.RegisterStatement(`
SELECT
       id::text AS id, tenant_id::text AS tenant_id, slug, name, kind, status,
       redirect_uris, post_logout_redirect_uris, backchannel_logout_uri,
       token_format, client_secret_hash, manifest_version,
       access_token_ttl::text AS access_token_ttl,
       refresh_token_ttl::text AS refresh_token_ttl
FROM applications
WHERE tenant_id = $1
ORDER BY slug`)
	storm.RegisterStatement(`
SELECT
       id::text AS id, tenant_id::text AS tenant_id, slug, name, kind, status,
       redirect_uris, post_logout_redirect_uris, backchannel_logout_uri,
       token_format, client_secret_hash, manifest_version,
       access_token_ttl::text AS access_token_ttl,
       refresh_token_ttl::text AS refresh_token_ttl,
       extract(epoch FROM access_token_ttl)::bigint  AS access_token_ttl_secs,
       extract(epoch FROM refresh_token_ttl)::bigint AS refresh_token_ttl_secs
FROM applications
WHERE tenant_id = $1 AND slug = $2`)
	storm.RegisterStatement(`
SELECT
       p.id::text AS id, p.tenant_id::text AS tenant_id, p.kind, p.slug, p.name,
       p.status, p.is_default,
       p.application_id::text AS application_id, a.slug AS application_slug,
       p.realm_id::text AS realm_id, r.code AS realm_code, p.config
FROM auth_pages p
LEFT JOIN applications a ON a.id = p.application_id
LEFT JOIN realms r ON r.id = p.realm_id
WHERE p.tenant_id = $1 AND p.kind = $2 AND p.is_default AND p.status = 'active'`)
	storm.RegisterStatement(`
SELECT
       p.id::text AS id, p.tenant_id::text AS tenant_id, p.kind, p.slug, p.name,
       p.status, p.is_default,
       p.application_id::text AS application_id, a.slug AS application_slug,
       p.realm_id::text AS realm_id, r.code AS realm_code, p.config
FROM auth_pages p
LEFT JOIN applications a ON a.id = p.application_id
LEFT JOIN realms r ON r.id = p.realm_id
WHERE p.tenant_id = $1 AND p.kind = $2 AND p.slug = $3 AND p.status = 'active'`)
	storm.RegisterStatement(`
SELECT
       p.id::text AS id, p.tenant_id::text AS tenant_id, p.kind, p.slug, p.name,
       p.status, p.is_default,
       p.application_id::text AS application_id, a.slug AS application_slug,
       p.realm_id::text AS realm_id, r.code AS realm_code, p.config, p.created_at, p.updated_at
FROM auth_pages p
LEFT JOIN applications a ON a.id = p.application_id
LEFT JOIN realms r ON r.id = p.realm_id
WHERE p.id = $1 AND p.tenant_id = $2`)
	storm.RegisterStatement(`
SELECT
       p.id::text AS id, p.tenant_id::text AS tenant_id, p.kind, p.slug, p.name,
       p.status, p.is_default,
       p.application_id::text AS application_id, a.slug AS application_slug,
       p.realm_id::text AS realm_id, r.code AS realm_code, p.config, p.created_at, p.updated_at
FROM auth_pages p
LEFT JOIN applications a ON a.id = p.application_id
LEFT JOIN realms r ON r.id = p.realm_id
WHERE p.tenant_id = $1 AND ($2::text IS NULL OR p.kind = $2)
ORDER BY p.kind, p.is_default DESC, p.slug`)
	storm.RegisterStatement(`
SELECT
  (SELECT count(*) FROM identities  i WHERE i.tenant_id = $1) AS identities,
  (SELECT count(*) FROM grants      g WHERE g.tenant_id = $1 AND g.revoked_at IS NULL) AS grants,
  (SELECT count(*) FROM scope_nodes n WHERE n.tenant_id = $1 AND n.status = 'active') AS scope_nodes,
  (SELECT count(*) FROM memberships m WHERE m.tenant_id = $1) AS memberships`)
	storm.RegisterStatement(`
SELECT (bump_catalog_version($1) IS NULL) AS done`)
	storm.RegisterStatement(`
SELECT count(*) AS n FROM identities i WHERE i.tenant_id = $1`)
	storm.RegisterStatement(`
SELECT rp.id::text AS id, rp.application_id::text AS application_id,
       rp.priority, rp.effect, rp.path_pattern, rp.host_pattern,
       rp.methods, rp.scope_bindings, p.key AS permission_key
FROM route_policies rp
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE rp.application_id = $1
ORDER BY rp.priority`)
	storm.RegisterStatement(`
SELECT tenant_id::text AS tenant_id, config, updated_at
FROM signin_pages WHERE tenant_id = $1`)
	storm.RegisterStatement(`
UPDATE applications
SET name = $3, status = $4, redirect_uris = $5::text[],
    post_logout_redirect_uris = $6::text[],
    backchannel_logout_uri = nullif($7, ''), token_format = $8,
    access_token_ttl = $9::text::interval,
    refresh_token_ttl = $10::text::interval,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE applications SET client_secret_hash = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE applications SET manifest_version = manifest_version + 1, updated_at = now()
WHERE id = $1
RETURNING manifest_version`)
	storm.RegisterStatement(`
UPDATE auth_pages
SET name = $3, status = $4, application_id = $5, realm_id = $6,
    config = $7::jsonb, updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE auth_pages SET is_default = false, updated_at = now()
WHERE tenant_id = $1 AND kind = $2 AND is_default`)
	storm.RegisterStatement(`
UPDATE auth_pages SET is_default = true, status = 'active', updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE tenants SET name = $2, updated_at = now() WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE tenants SET status = $2, updated_at = now() WHERE id = $1`)
}

func scanApplicationWithSecsRow(rv [][]byte, r *tenancyrquery.ApplicationWithSecsRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Slug = sl.Str(rv[2])
	r.Name = sl.Str(rv[3])
	r.Kind = sl.Str(rv[4])
	r.Status = sl.Str(rv[5])
	r.RedirectUris, decErr = runtime.TextArray(rv[6], sl)
	if decErr != nil {
		return decErr
	}
	r.PostLogoutRedirectUris, decErr = runtime.TextArray(rv[7], sl)
	if decErr != nil {
		return decErr
	}
	r.BackchannelLogoutURI = runtime.NullText(rv[8], sl)
	r.TokenFormat = sl.Str(rv[9])
	r.ClientSecretHash = runtime.NullText(rv[10], sl)
	r.ManifestVersion = runtime.Int4(rv[11])
	r.AccessTokenTtl = sl.Str(rv[12])
	r.RefreshTokenTtl = sl.Str(rv[13])
	r.AccessTokenTtlSecs = runtime.Int8(rv[14])
	r.RefreshTokenTtlSecs = runtime.Int8(rv[15])
	return nil
}

func scanApplicationRow(rv [][]byte, r *tenancyrquery.ApplicationRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Slug = sl.Str(rv[2])
	r.Name = sl.Str(rv[3])
	r.Kind = sl.Str(rv[4])
	r.Status = sl.Str(rv[5])
	r.RedirectUris, decErr = runtime.TextArray(rv[6], sl)
	if decErr != nil {
		return decErr
	}
	r.PostLogoutRedirectUris, decErr = runtime.TextArray(rv[7], sl)
	if decErr != nil {
		return decErr
	}
	r.BackchannelLogoutURI = runtime.NullText(rv[8], sl)
	r.TokenFormat = sl.Str(rv[9])
	r.ClientSecretHash = runtime.NullText(rv[10], sl)
	r.ManifestVersion = runtime.Int4(rv[11])
	r.AccessTokenTtl = sl.Str(rv[12])
	r.RefreshTokenTtl = sl.Str(rv[13])
	return nil
}

func scanCreatedApplicationRow(rv [][]byte, r *tenancyrquery.CreatedApplicationRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.ManifestVersion = runtime.Int4(rv[1])
	return nil
}

func scanManifestVersionRow(rv [][]byte, r *tenancyrquery.ManifestVersionRow, sl *runtime.Slab) error {
	r.ManifestVersion = runtime.Int4(rv[0])
	return nil
}

func scanRoutePolicyRow(rv [][]byte, r *tenancyrquery.RoutePolicyRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.ApplicationID = sl.Str(rv[1])
	r.Priority = runtime.Int4(rv[2])
	r.Effect = sl.Str(rv[3])
	r.PathPattern = sl.Str(rv[4])
	r.HostPattern = runtime.NullText(rv[5], sl)
	r.Methods, decErr = runtime.TextArray(rv[6], sl)
	if decErr != nil {
		return decErr
	}
	r.ScopeBindings = runtime.JSON(runtime.JSONB(rv[7], sl))
	r.PermissionKey = runtime.NullText(rv[8], sl)
	return nil
}

func scanAuthPageRow(rv [][]byte, r *tenancyrquery.AuthPageRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Kind = sl.Str(rv[2])
	r.Slug = sl.Str(rv[3])
	r.Name = sl.Str(rv[4])
	r.Status = sl.Str(rv[5])
	r.IsDefault = runtime.Bool(rv[6])
	r.ApplicationID = runtime.NullText(rv[7], sl)
	r.ApplicationSlug = runtime.NullText(rv[8], sl)
	r.RealmID = runtime.NullText(rv[9], sl)
	r.RealmCode = runtime.NullText(rv[10], sl)
	r.Config = runtime.JSON(runtime.JSONB(rv[11], sl))
	r.CreatedAt = runtime.Timestamptz(rv[12])
	r.UpdatedAt = runtime.Timestamptz(rv[13])
	return nil
}

func scanResolvedPageRow(rv [][]byte, r *tenancyrquery.ResolvedPageRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Kind = sl.Str(rv[2])
	r.Slug = sl.Str(rv[3])
	r.Name = sl.Str(rv[4])
	r.Status = sl.Str(rv[5])
	r.IsDefault = runtime.Bool(rv[6])
	r.ApplicationID = runtime.NullText(rv[7], sl)
	r.ApplicationSlug = runtime.NullText(rv[8], sl)
	r.RealmID = runtime.NullText(rv[9], sl)
	r.RealmCode = runtime.NullText(rv[10], sl)
	r.Config = runtime.JSON(runtime.JSONB(rv[11], sl))
	return nil
}

func scanSigninPageRow(rv [][]byte, r *tenancyrquery.SigninPageRow, sl *runtime.Slab) error {
	r.TenantID = sl.Str(rv[0])
	r.Config = runtime.JSON(runtime.JSONB(rv[1], sl))
	r.UpdatedAt = runtime.Timestamptz(rv[2])
	return nil
}

func scanDoneRow(rv [][]byte, r *tenancyrquery.DoneRow, sl *runtime.Slab) error {
	r.Done = runtime.Bool(rv[0])
	return nil
}

func scanCountRow(rv [][]byte, r *tenancyrquery.CountRow, sl *runtime.Slab) error {
	r.N = runtime.Int8(rv[0])
	return nil
}

func scanTenantStatsRow(rv [][]byte, r *tenancyrquery.TenantStatsRow, sl *runtime.Slab) error {
	r.Identities = runtime.Int8(rv[0])
	r.Grants = runtime.Int8(rv[1])
	r.ScopeNodes = runtime.Int8(rv[2])
	r.Memberships = runtime.Int8(rv[3])
	return nil
}
