// Code generated by storm v0.14.2. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/anubis/internal/tenancy/adapter/postgres/rmodel"
)

// _assertApplicationShape fails to compile if m0.Application gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertApplicationShape(m m0.Application) {
	type shape m0.Application
	_ = shape{
		m.Model,
		m.AccessTokenTtl,
		m.RefreshTokenTtl,
		m.Tenant,
		m.ManifestVersion,
		m.Kind,
		m.Status,
		m.Slug,
		m.Name,
		m.ClientSecretHash,
		m.RedirectUris,
		m.BackchannelLogoutURI,
		m.TokenFormat,
		m.PostLogoutRedirectUris,
	}
}

// _assertAuthPageShape fails to compile if m0.AuthPage gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertAuthPageShape(m m0.AuthPage) {
	type shape m0.AuthPage
	_ = shape{
		m.Model,
		m.Tenant,
		m.ApplicationID,
		m.RealmID,
		m.IsDefault,
		m.Kind,
		m.Status,
		m.Slug,
		m.Name,
		m.Config,
	}
}

// _assertCatalogVersionShape fails to compile if m0.CatalogVersion gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertCatalogVersionShape(m m0.CatalogVersion) {
	type shape m0.CatalogVersion
	_ = shape{
		m.ChangedAt,
		m.Version,
		m.Tenant,
	}
}

// _assertRoutePolicyShape fails to compile if m0.RoutePolicy gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertRoutePolicyShape(m m0.RoutePolicy) {
	type shape m0.RoutePolicy
	_ = shape{
		m.CreatedAt,
		m.ID,
		m.ApplicationID,
		m.TenantID,
		m.PermissionID,
		m.Priority,
		m.Effect,
		m.PathPattern,
		m.HostPattern,
		m.Methods,
		m.ScopeBindings,
	}
}

// _assertTenantShape fails to compile if m0.Tenant gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertTenantShape(m m0.Tenant) {
	type shape m0.Tenant
	_ = shape{
		m.Model,
		m.Status,
		m.Slug,
		m.Name,
		m.Settings,
	}
}
