// Code generated by storm v0.16.0. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/storm/runtime"

	identityrquery "github.com/gsoultan/anubis/internal/identity/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"consents":         0,
	"credentials":      1,
	"pii_keys":         2,
	"realm_categories": 3,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanLoginRow)
	storm.RegisterScanner(scanIdentityRow)
	storm.RegisterScanner(scanCreatedIdentityRow)
	storm.RegisterScanner(scanTokenEpochRow)
	storm.RegisterScanner(scanAuthStateRow)
	storm.RegisterScanner(scanErasedRow)
	storm.RegisterScanner(scanRealmCountRow)
	storm.RegisterScanner(scanCountRow)
	storm.RegisterScanner(scanCategoryCountRow)
	storm.RegisterScanner(scanPasswordRow)
	storm.RegisterScanner(scanCreatedCredentialRow)
	storm.RegisterScanner(scanKindRow)
	storm.RegisterScanner(scanActiveCredentialRow)
	storm.RegisterScanner(scanIDRow)
	storm.RegisterScanner(scanShreddedRow)
	storm.RegisterScanner(scanAttributesRow)
	storm.RegisterScanner(scanResealableRow)
	storm.RegisterScanner(scanRealmWithSecsRow)
	storm.RegisterScanner(scanRealmRow)
	storm.RegisterScanner(scanRealmIDRow)
	storm.RegisterStatement(`
INSERT INTO credentials (identity_id, tenant_id, kind, secret, lookup_key,
                         label, params, expires_at)
VALUES ($1, $2, $3, nullif($4, ''), nullif($5, ''), nullif($6, ''), $7::jsonb, $8)
RETURNING id::text AS id, created_at`)
	storm.RegisterStatement(`
INSERT INTO identities (tenant_id, realm_id, username, email, external_ref,
                        assurance_level, category_id, status)
VALUES ($1, $2, $3, nullif($4, ''), nullif($5, ''), $6, $7, $8)
RETURNING id::text AS id, created_at, token_epoch`)
	storm.RegisterStatement(`
INSERT INTO identity_links (tenant_id, primary_id, secondary_id, linked_by, method, evidence)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)`)
	storm.RegisterStatement(`
INSERT INTO realms (tenant_id, code, kind, display_name, min_assurance,
                    self_registration, email_verification_required, pii_encryption,
                    allowed_factors, required_factors, password_policy,
                    session_ttl, access_token_ttl, refresh_token_ttl,
                    default_retention, factor_enrolment_deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::text[], $10::text[], $11::jsonb,
        $12::text::interval, $13::text::interval, $14::text::interval,
        nullif($15, '')::interval, $16::timestamptz)
RETURNING id::text AS id`)
	storm.RegisterStatement(`
SELECT
       i.id::text AS id, i.tenant_id::text AS tenant_id, i.token_epoch, i.status,
       i.username, i.email, i.external_ref, i.assurance_level,
       i.disabled_at, i.anonymized_at, i.created_at, i.last_login_at,
       i.retention_until, i.realm_id::text AS realm_id,
       i.category_id::text AS category_id,
       r.code AS realm_code, r.kind AS realm_kind, c.code AS category_code
FROM identities i
LEFT JOIN realms r ON r.id = i.realm_id
LEFT JOIN realm_categories c ON c.id = i.category_id
WHERE i.id = $1 AND i.tenant_id = $2`)
	storm.RegisterStatement(`
SELECT
       i.id::text AS id, i.tenant_id::text AS tenant_id, i.token_epoch, i.status,
       i.username, i.email, i.external_ref, i.assurance_level,
       i.disabled_at, i.anonymized_at, i.created_at, i.last_login_at,
       i.retention_until, i.realm_id::text AS realm_id,
       i.category_id::text AS category_id,
       r.code AS realm_code, r.kind AS realm_kind, c.code AS category_code
FROM identities i
LEFT JOIN realms r ON r.id = i.realm_id
LEFT JOIN realm_categories c ON c.id = i.category_id
WHERE i.tenant_id = $1
  AND ($2::uuid IS NULL OR i.realm_id = $2)
  AND ($3::text IS NULL OR i.status = $3)
  AND ($4::text IS NULL
       OR i.username ILIKE '%' || $4 || '%'
       OR i.email    ILIKE '%' || $4 || '%')
  AND ($5::uuid IS NULL OR i.id > $5)
ORDER BY i.id
LIMIT $6`)
	storm.RegisterStatement(`
SELECT
       id::text AS id, tenant_id::text AS tenant_id, code, kind, display_name,
       min_assurance, self_registration, email_verification_required,
       pii_encryption, allowed_factors, required_factors, password_policy,
       factor_enrolment_deadline,
       session_ttl::text  AS session_ttl,
       access_token_ttl::text AS access_token_ttl,
       refresh_token_ttl::text AS refresh_token_ttl,
       COALESCE(default_retention::text, '')::text AS default_retention
FROM realms
WHERE tenant_id = $1
ORDER BY code`)
	storm.RegisterStatement(`
SELECT
       id::text AS id, tenant_id::text AS tenant_id, code, kind, display_name,
       min_assurance, self_registration, email_verification_required,
       pii_encryption, allowed_factors, required_factors, password_policy,
       factor_enrolment_deadline,
       session_ttl::text  AS session_ttl,
       access_token_ttl::text AS access_token_ttl,
       refresh_token_ttl::text AS refresh_token_ttl,
       COALESCE(default_retention::text, '')::text AS default_retention,
       extract(epoch FROM session_ttl)::bigint       AS session_ttl_secs,
       extract(epoch FROM access_token_ttl)::bigint  AS access_token_ttl_secs,
       extract(epoch FROM refresh_token_ttl)::bigint AS refresh_token_ttl_secs
FROM realms
WHERE id = $1`)
	storm.RegisterStatement(`
SELECT
       id::text AS id, tenant_id::text AS tenant_id, code, kind, display_name,
       min_assurance, self_registration, email_verification_required,
       pii_encryption, allowed_factors, required_factors, password_policy,
       factor_enrolment_deadline,
       session_ttl::text  AS session_ttl,
       access_token_ttl::text AS access_token_ttl,
       refresh_token_ttl::text AS refresh_token_ttl,
       COALESCE(default_retention::text, '')::text AS default_retention,
       extract(epoch FROM session_ttl)::bigint       AS session_ttl_secs,
       extract(epoch FROM access_token_ttl)::bigint  AS access_token_ttl_secs,
       extract(epoch FROM refresh_token_ttl)::bigint AS refresh_token_ttl_secs
FROM realms
WHERE tenant_id = $1 AND code = $2`)
	storm.RegisterStatement(`
SELECT DISTINCT kind FROM credentials
WHERE identity_id = $1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())`)
	storm.RegisterStatement(`
SELECT category_id::text AS category_id, count(*) AS n
FROM identities
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR realm_id = $2)
  AND category_id IS NOT NULL
GROUP BY category_id`)
	storm.RegisterStatement(`
SELECT count(*) AS n FROM identities
WHERE tenant_id = $1 AND retention_until IS NOT NULL
  AND retention_until < now() AND anonymized_at IS NULL`)
	storm.RegisterStatement(`
SELECT i.attributes, i.pii_key_id::text AS pii_key_id, k.key_enc
FROM identities i
LEFT JOIN pii_keys k ON k.id = i.pii_key_id
WHERE i.id = $1 AND i.tenant_id = $2`)
	storm.RegisterStatement(`
SELECT i.id::text AS id, i.tenant_id::text AS tenant_id, i.token_epoch, i.status,
       i.username, i.email, i.assurance_level, i.disabled_at, i.anonymized_at,
       i.realm_id::text AS realm_id, r.code AS realm_code, r.kind AS realm_kind
FROM identities i
LEFT JOIN realms r ON r.id = i.realm_id
WHERE i.tenant_id = $1
  AND i.realm_id = $2
  AND lower(i.username) = lower($3)`)
	storm.RegisterStatement(`
SELECT id::text AS id, identity_id::text AS identity_id,
       tenant_id::text AS tenant_id, kind, secret, secret_kid, params, sign_counter
FROM credentials
WHERE identity_id = $1 AND kind = $2
  AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
LIMIT 1`)
	storm.RegisterStatement(`
SELECT id::text AS id, identity_id::text AS identity_id,
       tenant_id::text AS tenant_id, secret, params, expires_at
FROM credentials
WHERE identity_id = $1 AND kind = 'password' AND revoked_at IS NULL`)
	storm.RegisterStatement(`
SELECT k.id::text AS key_id, i.id::text AS identity_id, k.key_enc
FROM pii_keys k
JOIN identities i ON i.pii_key_id = k.id
WHERE k.key_enc IS NOT NULL AND k.shredded_at IS NULL
ORDER BY k.id`)
	storm.RegisterStatement(`
SELECT pii_shred($1, $2) AS shredded`)
	storm.RegisterStatement(`
SELECT r.code AS realm, r.kind, count(i.id) AS n
FROM realms r
LEFT JOIN identities i ON i.realm_id = r.id AND i.tenant_id = r.tenant_id
WHERE r.tenant_id = $1
GROUP BY r.code, r.kind
ORDER BY r.code`)
	storm.RegisterStatement(`
SELECT token_epoch, status, disabled_at, anonymized_at
FROM identities
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE consents SET withdrawn_at = now()
WHERE id = $1 AND tenant_id = $2 AND withdrawn_at IS NULL`)
	storm.RegisterStatement(`
UPDATE credentials
SET last_used_at = now(),
    sign_counter = GREATEST(sign_counter, $2),
    updated_at = now()
WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE credentials
SET revoked_at = now(), last_used_at = now(), updated_at = now()
WHERE id = (
    SELECT c.id FROM credentials c
     WHERE c.identity_id = $1
       AND c.kind = 'recovery_code'
       AND c.revoked_at IS NULL
       AND c.secret = $2
     LIMIT 1)
RETURNING id::text AS id`)
	storm.RegisterStatement(`
UPDATE credentials SET params = $2::jsonb, updated_at = now() WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE credentials SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL`)
	storm.RegisterStatement(`
UPDATE credentials SET revoked_at = now(), updated_at = now()
WHERE identity_id = $1 AND kind = $2 AND revoked_at IS NULL`)
	storm.RegisterStatement(`
UPDATE credentials SET secret = $2, secret_kid = $3, updated_at = now() WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE identities
SET anonymized_at = now(),
    status        = 'disabled',
    username      = 'anon_' || left(replace(id::text, '-', ''), 16),
    email         = NULL,
    external_ref  = NULL,
    attributes    = '{}'::jsonb,
    token_epoch   = token_epoch + 1,
    updated_at    = now()
WHERE retention_until IS NOT NULL
  AND retention_until < now()
  AND anonymized_at IS NULL
RETURNING id::text AS id, tenant_id::text AS tenant_id, pii_key_id::text AS pii_key_id`)
	storm.RegisterStatement(`
UPDATE identities
SET anonymized_at = now(),
    status        = 'disabled',
    username      = 'anon_' || left(replace(id::text, '-', ''), 16),
    email         = NULL,
    external_ref  = NULL,
    attributes    = '{}'::jsonb,
    token_epoch   = token_epoch + 1,
    updated_at    = now(),
    pii_key_id    = NULL
WHERE id = $1 AND tenant_id = $2
  AND anonymized_at IS NULL
RETURNING id::text AS id, tenant_id::text AS tenant_id, pii_key_id::text AS pii_key_id`)
	storm.RegisterStatement(`
UPDATE identities SET attributes = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE identities SET deletion_requested_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deletion_requested_at IS NULL`)
	storm.RegisterStatement(`
UPDATE identities SET last_login_at = now() WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE identities SET pii_key_id = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE identities SET status = 'active', disabled_at = NULL, updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE identities SET status = 'disabled', disabled_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND disabled_at IS NULL`)
	storm.RegisterStatement(`
UPDATE identities SET token_epoch = token_epoch + 1, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING token_epoch`)
	storm.RegisterStatement(`
UPDATE identities i
SET retention_until = now() + r.default_retention, updated_at = now()
FROM realms r
WHERE i.realm_id = r.id
  AND r.default_retention IS NOT NULL
  AND i.retention_until IS NULL
  AND i.anonymized_at IS NULL`)
	storm.RegisterStatement(`
UPDATE pii_keys SET key_enc = $2, kms_key_ref = $3 WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE realms SET
    display_name = $2,
    min_assurance = $3,
    self_registration = $4,
    email_verification_required = $5,
    pii_encryption = $6,
    allowed_factors = $7::text[],
    required_factors = $8::text[],
    password_policy = $9::jsonb,
    session_ttl = $10::text::interval,
    access_token_ttl = $11::text::interval,
    refresh_token_ttl = $12::text::interval,
    default_retention = nullif($13, '')::interval,
    -- NULL takes the policy out of force again; enrolments already made
    -- survive, so a second rollout starts ahead of the first.
    factor_enrolment_deadline = $14::timestamptz,
    updated_at = now()
WHERE id = $1
RETURNING id::text AS id`)
	storm.RegisterStatement(`
UPDATE realms SET code = $3, kind = $4, updated_at = now()
WHERE realms.id = $1
  AND realms.tenant_id = $2
  AND NOT EXISTS (SELECT 1 FROM identities i WHERE i.realm_id = realms.id)`)
}

func scanLoginRow(rv [][]byte, r *identityrquery.LoginRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.TokenEpoch = runtime.Int4(rv[2])
	r.Status = sl.Str(rv[3])
	r.Username = sl.Str(rv[4])
	r.Email = runtime.NullText(rv[5], sl)
	r.AssuranceLevel = runtime.Int2(rv[6])
	r.DisabledAt = runtime.Nullable(rv[7], runtime.Timestamptz)
	r.AnonymizedAt = runtime.Nullable(rv[8], runtime.Timestamptz)
	r.RealmID = runtime.NullText(rv[9], sl)
	r.RealmCode = runtime.NullText(rv[10], sl)
	r.RealmKind = runtime.NullText(rv[11], sl)
	return nil
}

func scanIdentityRow(rv [][]byte, r *identityrquery.IdentityRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.TokenEpoch = runtime.Int4(rv[2])
	r.Status = sl.Str(rv[3])
	r.Username = sl.Str(rv[4])
	r.Email = runtime.NullText(rv[5], sl)
	r.ExternalRef = runtime.NullText(rv[6], sl)
	r.AssuranceLevel = runtime.Int2(rv[7])
	r.DisabledAt = runtime.Nullable(rv[8], runtime.Timestamptz)
	r.AnonymizedAt = runtime.Nullable(rv[9], runtime.Timestamptz)
	r.CreatedAt = runtime.Timestamptz(rv[10])
	r.LastLoginAt = runtime.Nullable(rv[11], runtime.Timestamptz)
	r.RetentionUntil = runtime.Nullable(rv[12], runtime.Timestamptz)
	r.RealmID = runtime.NullText(rv[13], sl)
	r.CategoryID = runtime.NullText(rv[14], sl)
	r.RealmCode = runtime.NullText(rv[15], sl)
	r.RealmKind = runtime.NullText(rv[16], sl)
	r.CategoryCode = runtime.NullText(rv[17], sl)
	return nil
}

func scanCreatedIdentityRow(rv [][]byte, r *identityrquery.CreatedIdentityRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.CreatedAt = runtime.Timestamptz(rv[1])
	r.TokenEpoch = runtime.Int4(rv[2])
	return nil
}

func scanTokenEpochRow(rv [][]byte, r *identityrquery.TokenEpochRow, sl *runtime.Slab) error {
	r.TokenEpoch = runtime.Int4(rv[0])
	return nil
}

func scanAuthStateRow(rv [][]byte, r *identityrquery.AuthStateRow, sl *runtime.Slab) error {
	r.TokenEpoch = runtime.Int4(rv[0])
	r.Status = sl.Str(rv[1])
	r.DisabledAt = runtime.Nullable(rv[2], runtime.Timestamptz)
	r.AnonymizedAt = runtime.Nullable(rv[3], runtime.Timestamptz)
	return nil
}

func scanErasedRow(rv [][]byte, r *identityrquery.ErasedRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.PiiKeyID = runtime.NullText(rv[2], sl)
	return nil
}

func scanRealmCountRow(rv [][]byte, r *identityrquery.RealmCountRow, sl *runtime.Slab) error {
	r.Realm = sl.Str(rv[0])
	r.Kind = sl.Str(rv[1])
	r.N = runtime.Int8(rv[2])
	return nil
}

func scanCountRow(rv [][]byte, r *identityrquery.CountRow, sl *runtime.Slab) error {
	r.N = runtime.Int8(rv[0])
	return nil
}

func scanCategoryCountRow(rv [][]byte, r *identityrquery.CategoryCountRow, sl *runtime.Slab) error {
	r.CategoryID = sl.Str(rv[0])
	r.N = runtime.Int8(rv[1])
	return nil
}

func scanPasswordRow(rv [][]byte, r *identityrquery.PasswordRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.TenantID = sl.Str(rv[2])
	r.Secret = runtime.NullText(rv[3], sl)
	r.Params = runtime.JSON(runtime.JSONB(rv[4], sl))
	r.ExpiresAt = runtime.Nullable(rv[5], runtime.Timestamptz)
	return nil
}

func scanCreatedCredentialRow(rv [][]byte, r *identityrquery.CreatedCredentialRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.CreatedAt = runtime.Timestamptz(rv[1])
	return nil
}

func scanKindRow(rv [][]byte, r *identityrquery.KindRow, sl *runtime.Slab) error {
	r.Kind = sl.Str(rv[0])
	return nil
}

func scanActiveCredentialRow(rv [][]byte, r *identityrquery.ActiveCredentialRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.TenantID = sl.Str(rv[2])
	r.Kind = sl.Str(rv[3])
	r.Secret = runtime.NullText(rv[4], sl)
	r.SecretKid = runtime.NullText(rv[5], sl)
	r.Params = runtime.JSON(runtime.JSONB(rv[6], sl))
	r.SignCounter = runtime.Int8(rv[7])
	return nil
}

func scanIDRow(rv [][]byte, r *identityrquery.IDRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}

func scanShreddedRow(rv [][]byte, r *identityrquery.ShreddedRow, sl *runtime.Slab) error {
	r.Shredded = runtime.Bool(rv[0])
	return nil
}

func scanAttributesRow(rv [][]byte, r *identityrquery.AttributesRow, sl *runtime.Slab) error {
	r.Attributes = runtime.JSON(runtime.JSONB(rv[0], sl))
	r.PiiKeyID = runtime.NullText(rv[1], sl)
	r.KeyEnc = runtime.Bytes(rv[2])
	return nil
}

func scanResealableRow(rv [][]byte, r *identityrquery.ResealableRow, sl *runtime.Slab) error {
	r.KeyID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.KeyEnc = runtime.Bytes(rv[2])
	return nil
}

func scanRealmWithSecsRow(rv [][]byte, r *identityrquery.RealmWithSecsRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Code = sl.Str(rv[2])
	r.Kind = sl.Str(rv[3])
	r.DisplayName = sl.Str(rv[4])
	r.MinAssurance = runtime.Int2(rv[5])
	r.SelfRegistration = runtime.Bool(rv[6])
	r.EmailVerificationRequired = runtime.Bool(rv[7])
	r.PiiEncryption = runtime.Bool(rv[8])
	r.AllowedFactors, decErr = runtime.TextArray(rv[9], sl)
	if decErr != nil {
		return decErr
	}
	r.RequiredFactors, decErr = runtime.TextArray(rv[10], sl)
	if decErr != nil {
		return decErr
	}
	r.PasswordPolicy = runtime.JSON(runtime.JSONB(rv[11], sl))
	r.FactorEnrolmentDeadline = runtime.Nullable(rv[12], runtime.Timestamptz)
	r.SessionTtl = sl.Str(rv[13])
	r.AccessTokenTtl = sl.Str(rv[14])
	r.RefreshTokenTtl = sl.Str(rv[15])
	r.DefaultRetention = sl.Str(rv[16])
	r.SessionTtlSecs = runtime.Int8(rv[17])
	r.AccessTokenTtlSecs = runtime.Int8(rv[18])
	r.RefreshTokenTtlSecs = runtime.Int8(rv[19])
	return nil
}

func scanRealmRow(rv [][]byte, r *identityrquery.RealmRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Code = sl.Str(rv[2])
	r.Kind = sl.Str(rv[3])
	r.DisplayName = sl.Str(rv[4])
	r.MinAssurance = runtime.Int2(rv[5])
	r.SelfRegistration = runtime.Bool(rv[6])
	r.EmailVerificationRequired = runtime.Bool(rv[7])
	r.PiiEncryption = runtime.Bool(rv[8])
	r.AllowedFactors, decErr = runtime.TextArray(rv[9], sl)
	if decErr != nil {
		return decErr
	}
	r.RequiredFactors, decErr = runtime.TextArray(rv[10], sl)
	if decErr != nil {
		return decErr
	}
	r.PasswordPolicy = runtime.JSON(runtime.JSONB(rv[11], sl))
	r.FactorEnrolmentDeadline = runtime.Nullable(rv[12], runtime.Timestamptz)
	r.SessionTtl = sl.Str(rv[13])
	r.AccessTokenTtl = sl.Str(rv[14])
	r.RefreshTokenTtl = sl.Str(rv[15])
	r.DefaultRetention = sl.Str(rv[16])
	return nil
}

func scanRealmIDRow(rv [][]byte, r *identityrquery.RealmIDRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}
