// Code generated by storm v1.1.0. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/anubis/internal/identity/adapter/postgres/rmodel"
)

// _assertConsentShape fails to compile if m0.Consent gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertConsentShape(m m0.Consent) {
	type shape m0.Consent
	_ = shape{
		m.GrantedAt,
		m.WithdrawnAt,
		m.ExpiresAt,
		m.ID,
		m.TenantID,
		m.IdentityID,
		m.Purpose,
		m.PolicyVersion,
		m.Evidence,
	}
}

// _assertCredentialShape fails to compile if m0.Credential gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertCredentialShape(m m0.Credential) {
	type shape m0.Credential
	_ = shape{
		m.Model,
		m.LastUsedAt,
		m.ExpiresAt,
		m.RevokedAt,
		m.IdentityID,
		m.TenantID,
		m.SignCounter,
		m.Kind,
		m.Secret,
		m.SecretKid,
		m.LookupKey,
		m.Label,
		m.Params,
	}
}

// _assertPIIKeyShape fails to compile if m0.PIIKey gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertPIIKeyShape(m m0.PIIKey) {
	type shape m0.PIIKey
	_ = shape{
		m.CreatedAt,
		m.ShreddedAt,
		m.ID,
		m.TenantID,
		m.KeyEnc,
		m.KmsKeyRef,
	}
}

// _assertRealmCategoryShape fails to compile if m0.RealmCategory gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertRealmCategoryShape(m m0.RealmCategory) {
	type shape m0.RealmCategory
	_ = shape{
		m.CreatedAt,
		m.SortOrder,
		m.ID,
		m.TenantID,
		m.RealmID,
		m.Code,
		m.DisplayName,
	}
}
