// Code generated by storm v1.1.0. DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/storm/runtime"

	authrquery "github.com/gsoultan/anubis/internal/auth/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"api_keys":        0,
	"one_time_tokens": 1,
	"refresh_tokens":  2,
	"sessions":        3,
	"signing_keys":    4,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanCreatedSessionRow)
	storm.RegisterScanner(scanLiveSessionRow)
	storm.RegisterScanner(scanSessionStateRow)
	storm.RegisterScanner(scanSessionListRow)
	storm.RegisterScanner(scanRevokedSessionRow)
	storm.RegisterScanner(scanRevokedAllRow)
	storm.RegisterScanner(scanAuthTimeRow)
	storm.RegisterScanner(scanCookieSessionRow)
	storm.RegisterScanner(scanIDRow)
	storm.RegisterScanner(scanClaimedRefreshRow)
	storm.RegisterScanner(scanRefreshTokenRow)
	storm.RegisterScanner(scanConsumedTokenRow)
	storm.RegisterScanner(scanAPIKeyAuthRow)
	storm.RegisterScanner(scanAPIKeyListRow)
	storm.RegisterStatement(`
DELETE FROM one_time_tokens
WHERE token_hash = $1 AND kind = $2 AND expires_at > now()
RETURNING id::text AS id, tenant_id::text AS tenant_id, payload`)
	storm.RegisterStatement(`
DELETE FROM one_time_tokens WHERE expires_at < now() - interval '1 hour'`)
	storm.RegisterStatement(`
INSERT INTO refresh_tokens (session_id, tenant_id, family_id, generation,
                            token_hash, expires_at, bound_key, client_id)
VALUES ($1, $2, $3, $4, $5, $6, nullif($7, ''), nullif($8, ''))
RETURNING id::text AS id`)
	storm.RegisterStatement(`
INSERT INTO sessions (identity_id, tenant_id, application_id, amr, device_fp,
                      ip, user_agent, active_scopes, expires_at)
VALUES ($1, $2, $3, $4::text[], nullif($5, ''), nullif($6, '')::inet,
        nullif($7, ''), $8::jsonb, $9)
RETURNING id::text AS id, created_at, auth_time, expires_at`)
	storm.RegisterStatement(`
SELECT id::text AS id, created_at, last_seen_at, expires_at, amr,
       COALESCE(host(ip)::text, '')::text AS ip, user_agent
FROM sessions
WHERE identity_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at DESC`)
	storm.RegisterStatement(`
SELECT id::text AS id, session_id::text AS session_id,
       tenant_id::text AS tenant_id, family_id::text AS family_id,
       generation, status, created_at, expires_at, consumed_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1`)
	storm.RegisterStatement(`
SELECT k.id::text AS id, k.label, k.lookup, k.created_at, k.last_used_at,
       k.expires_at, k.revoked_at, COALESCE(u.username, '') AS created_by
  FROM api_keys k
  LEFT JOIN platform_users u ON u.id = k.created_by
 WHERE k.tenant_id = $1
 ORDER BY k.created_at DESC`)
	storm.RegisterStatement(`
SELECT k.id::text AS id, k.tenant_id::text AS tenant_id, k.label, k.secret_hash,
       k.expires_at, k.revoked_at, t.slug AS tenant_slug, t.status AS tenant_status
  FROM api_keys k
  JOIN tenants t ON t.id = k.tenant_id
 WHERE k.lookup = $1 AND k.revoked_at IS NULL`)
	storm.RegisterStatement(`
SELECT s.id::text AS id, s.identity_id::text AS identity_id,
       s.tenant_id::text AS tenant_id, s.amr, s.auth_time, s.expires_at,
       s.active_scopes, i.username, i.realm_id::text AS realm_id, r.code AS realm_code
FROM sessions s
JOIN identities i ON i.id = s.identity_id AND i.tenant_id = s.tenant_id
LEFT JOIN realms r ON r.id = i.realm_id
WHERE s.cookie_hash = $1
  AND s.revoked_at IS NULL AND s.expires_at > now()`)
	storm.RegisterStatement(`
SELECT s.id::text AS id, s.identity_id::text AS identity_id,
       s.tenant_id::text AS tenant_id, s.application_id::text AS application_id,
       s.amr, s.created_at, s.last_seen_at, s.auth_time, s.expires_at,
       s.active_scopes, s.device_fp,
       i.token_epoch, i.status AS identity_status,
       i.assurance_level, i.username, i.email, i.realm_id::text AS realm_id,
       r.code AS realm_code
FROM sessions s
JOIN identities i ON i.id = s.identity_id AND i.tenant_id = s.tenant_id
LEFT JOIN realms r ON r.id = i.realm_id
WHERE s.id = $1
  AND s.revoked_at IS NULL AND s.expires_at > now()`)
	storm.RegisterStatement(`
SELECT s.revoked_at, s.expires_at, i.token_epoch, i.status AS identity_status,
       i.disabled_at, i.anonymized_at
FROM sessions s
JOIN identities i ON i.id = s.identity_id AND i.tenant_id = s.tenant_id
WHERE s.id = $1 AND s.tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE api_keys SET revoked_at = now()
 WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL`)
	storm.RegisterStatement(`
UPDATE refresh_tokens
SET status = 'consumed', consumed_at = now()
WHERE token_hash = $1
  AND status = 'active'
  AND expires_at > now()
RETURNING id::text AS id, session_id::text AS session_id,
          tenant_id::text AS tenant_id, family_id::text AS family_id,
          generation, expires_at, coalesce(client_id, '') AS client_id`)
	storm.RegisterStatement(`
UPDATE refresh_tokens
SET status = 'revoked', revoked_at = now()
WHERE family_id = $1 AND status = 'active'`)
	storm.RegisterStatement(`
UPDATE refresh_tokens
SET status = 'revoked', revoked_at = now()
WHERE session_id = $1 AND status = 'active'`)
	storm.RegisterStatement(`
UPDATE refresh_tokens
SET status = 'revoked', revoked_at = now()
WHERE session_id = ANY($1::uuid[]) AND status = 'active'`)
	storm.RegisterStatement(`
UPDATE refresh_tokens SET successor_id = $2
WHERE id = $1 AND expires_at = $3`)
	storm.RegisterStatement(`
UPDATE sessions
SET revoked_at = now(), revoke_reason = $3, cookie_hash = NULL
WHERE id = $1 AND tenant_id = $2 AND revoked_at IS NULL
RETURNING id::text AS id, identity_id::text AS identity_id,
          application_id::text AS application_id`)
	storm.RegisterStatement(`
UPDATE sessions
SET revoked_at = now(), revoke_reason = $3, cookie_hash = NULL
WHERE identity_id = $1 AND tenant_id = $2 AND revoked_at IS NULL
RETURNING id::text AS id, application_id::text AS application_id`)
	storm.RegisterStatement(`
UPDATE sessions SET active_scopes = $2::jsonb WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE sessions SET amr = $2::text[], auth_time = now()
WHERE id = $1 AND revoked_at IS NULL
RETURNING auth_time`)
	storm.RegisterStatement(`
UPDATE sessions SET cookie_hash = $2 WHERE id = $1`)
	storm.RegisterStatement(`
UPDATE signing_keys
SET status = $2,
    retired_at = CASE WHEN $2 = 'retired' THEN now() ELSE retired_at END
WHERE kid = $1`)
	storm.RegisterStatement(`
UPDATE signing_keys SET status = 'active'
WHERE purpose = $1 AND status = 'pending'`)
	storm.RegisterStatement(`
UPDATE signing_keys SET status = 'retiring'
WHERE purpose = $1 AND status = 'active'`)
}

func scanCreatedSessionRow(rv [][]byte, r *authrquery.CreatedSessionRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.CreatedAt = runtime.Timestamptz(rv[1])
	r.AuthTime = runtime.Timestamptz(rv[2])
	r.ExpiresAt = runtime.Timestamptz(rv[3])
	return nil
}

func scanLiveSessionRow(rv [][]byte, r *authrquery.LiveSessionRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.TenantID = sl.Str(rv[2])
	r.ApplicationID = runtime.NullText(rv[3], sl)
	r.Amr, decErr = runtime.TextArray(rv[4], sl)
	if decErr != nil {
		return decErr
	}
	r.CreatedAt = runtime.Timestamptz(rv[5])
	r.LastSeenAt = runtime.Timestamptz(rv[6])
	r.AuthTime = runtime.Timestamptz(rv[7])
	r.ExpiresAt = runtime.Timestamptz(rv[8])
	r.ActiveScopes = runtime.JSON(runtime.JSONB(rv[9], sl))
	r.DeviceFp = runtime.NullText(rv[10], sl)
	r.TokenEpoch = runtime.Int4(rv[11])
	r.IdentityStatus = sl.Str(rv[12])
	r.AssuranceLevel = runtime.Int2(rv[13])
	r.Username = runtime.NullText(rv[14], sl)
	r.Email = runtime.NullText(rv[15], sl)
	r.RealmID = runtime.NullText(rv[16], sl)
	r.RealmCode = runtime.NullText(rv[17], sl)
	return nil
}

func scanSessionStateRow(rv [][]byte, r *authrquery.SessionStateRow, sl *runtime.Slab) error {
	r.RevokedAt = runtime.Nullable(rv[0], runtime.Timestamptz)
	r.ExpiresAt = runtime.Timestamptz(rv[1])
	r.TokenEpoch = runtime.Int4(rv[2])
	r.IdentityStatus = sl.Str(rv[3])
	r.DisabledAt = runtime.Nullable(rv[4], runtime.Timestamptz)
	r.AnonymizedAt = runtime.Nullable(rv[5], runtime.Timestamptz)
	return nil
}

func scanSessionListRow(rv [][]byte, r *authrquery.SessionListRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.CreatedAt = runtime.Timestamptz(rv[1])
	r.LastSeenAt = runtime.Timestamptz(rv[2])
	r.ExpiresAt = runtime.Timestamptz(rv[3])
	r.Amr, decErr = runtime.TextArray(rv[4], sl)
	if decErr != nil {
		return decErr
	}
	r.IP = sl.Str(rv[5])
	r.UserAgent = runtime.NullText(rv[6], sl)
	return nil
}

func scanRevokedSessionRow(rv [][]byte, r *authrquery.RevokedSessionRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.ApplicationID = runtime.NullText(rv[2], sl)
	return nil
}

func scanRevokedAllRow(rv [][]byte, r *authrquery.RevokedAllRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.ApplicationID = runtime.NullText(rv[1], sl)
	return nil
}

func scanAuthTimeRow(rv [][]byte, r *authrquery.AuthTimeRow, sl *runtime.Slab) error {
	r.AuthTime = runtime.Timestamptz(rv[0])
	return nil
}

func scanCookieSessionRow(rv [][]byte, r *authrquery.CookieSessionRow, sl *runtime.Slab) error {
	var decErr error
	r.ID = sl.Str(rv[0])
	r.IdentityID = sl.Str(rv[1])
	r.TenantID = sl.Str(rv[2])
	r.Amr, decErr = runtime.TextArray(rv[3], sl)
	if decErr != nil {
		return decErr
	}
	r.AuthTime = runtime.Timestamptz(rv[4])
	r.ExpiresAt = runtime.Timestamptz(rv[5])
	r.ActiveScopes = runtime.JSON(runtime.JSONB(rv[6], sl))
	r.Username = runtime.NullText(rv[7], sl)
	r.RealmID = runtime.NullText(rv[8], sl)
	r.RealmCode = runtime.NullText(rv[9], sl)
	return nil
}

func scanIDRow(rv [][]byte, r *authrquery.IDRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}

func scanClaimedRefreshRow(rv [][]byte, r *authrquery.ClaimedRefreshRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.SessionID = sl.Str(rv[1])
	r.TenantID = sl.Str(rv[2])
	r.FamilyID = sl.Str(rv[3])
	r.Generation = runtime.Int4(rv[4])
	r.ExpiresAt = runtime.Timestamptz(rv[5])
	r.ClientID = sl.Str(rv[6])
	return nil
}

func scanRefreshTokenRow(rv [][]byte, r *authrquery.RefreshTokenRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.SessionID = sl.Str(rv[1])
	r.TenantID = sl.Str(rv[2])
	r.FamilyID = sl.Str(rv[3])
	r.Generation = runtime.Int4(rv[4])
	r.Status = sl.Str(rv[5])
	r.CreatedAt = runtime.Timestamptz(rv[6])
	r.ExpiresAt = runtime.Timestamptz(rv[7])
	r.ConsumedAt = runtime.Nullable(rv[8], runtime.Timestamptz)
	r.RevokedAt = runtime.Nullable(rv[9], runtime.Timestamptz)
	return nil
}

func scanConsumedTokenRow(rv [][]byte, r *authrquery.ConsumedTokenRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Payload = runtime.JSON(runtime.JSONB(rv[2], sl))
	return nil
}

func scanAPIKeyAuthRow(rv [][]byte, r *authrquery.APIKeyAuthRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.Label = sl.Str(rv[2])
	r.SecretHash = sl.Str(rv[3])
	r.ExpiresAt = runtime.Nullable(rv[4], runtime.Timestamptz)
	r.RevokedAt = runtime.Nullable(rv[5], runtime.Timestamptz)
	r.TenantSlug = sl.Str(rv[6])
	r.TenantStatus = sl.Str(rv[7])
	return nil
}

func scanAPIKeyListRow(rv [][]byte, r *authrquery.APIKeyListRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.Label = sl.Str(rv[1])
	r.Lookup = sl.Str(rv[2])
	r.CreatedAt = runtime.Timestamptz(rv[3])
	r.LastUsedAt = runtime.Nullable(rv[4], runtime.Timestamptz)
	r.ExpiresAt = runtime.Nullable(rv[5], runtime.Timestamptz)
	r.RevokedAt = runtime.Nullable(rv[6], runtime.Timestamptz)
	r.CreatedBy = sl.Str(rv[7])
	return nil
}
