// Code generated by storm v1.1.0. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/anubis/internal/auth/adapter/postgres/rmodel"
)

// _assertAPIKeyShape fails to compile if m0.APIKey gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertAPIKeyShape(m m0.APIKey) {
	type shape m0.APIKey
	_ = shape{
		m.CreatedAt,
		m.ID,
		m.TenantID,
		m.Label,
		m.Lookup,
		m.SecretHash,
		m.CreatedBy,
		m.LastUsedAt,
		m.ExpiresAt,
		m.RevokedAt,
	}
}

// _assertOneTimeTokenShape fails to compile if m0.OneTimeToken gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertOneTimeTokenShape(m m0.OneTimeToken) {
	type shape m0.OneTimeToken
	_ = shape{
		m.CreatedAt,
		m.ExpiresAt,
		m.ID,
		m.TenantID,
		m.Kind,
		m.TokenHash,
		m.Payload,
	}
}

// _assertRefreshTokenShape fails to compile if m0.RefreshToken gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertRefreshTokenShape(m m0.RefreshToken) {
	type shape m0.RefreshToken
	_ = shape{
		m.CreatedAt,
		m.ExpiresAt,
		m.ConsumedAt,
		m.RevokedAt,
		m.ID,
		m.SessionID,
		m.TenantID,
		m.FamilyID,
		m.SuccessorID,
		m.Generation,
		m.Status,
		m.TokenHash,
		m.BoundKey,
		m.ClientID,
	}
}

// _assertSessionShape fails to compile if m0.Session gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertSessionShape(m m0.Session) {
	type shape m0.Session
	_ = shape{
		m.CreatedAt,
		m.LastSeenAt,
		m.AuthTime,
		m.ExpiresAt,
		m.RevokedAt,
		m.ID,
		m.IdentityID,
		m.TenantID,
		m.ApplicationID,
		m.Amr,
		m.RevokeReason,
		m.DeviceFp,
		m.IP,
		m.UserAgent,
		m.ActiveScopes,
		m.CookieHash,
	}
}

// _assertSigningKeyShape fails to compile if m0.SigningKey gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertSigningKeyShape(m m0.SigningKey) {
	type shape m0.SigningKey
	_ = shape{
		m.CreatedAt,
		m.NotBefore,
		m.NotAfter,
		m.RetiredAt,
		m.ID,
		m.Kid,
		m.Alg,
		m.Status,
		m.Purpose,
		m.PublicKey,
		m.PrivateKeyEnc,
	}
}
