// Code generated by storm (devel). DO NOT EDIT.
// source: bounded context rgen

package rgen

import (
	"github.com/gsoultan/storm/runtime"

	scopermquery "github.com/gsoultan/anubis/internal/scope/adapter/postgres/rquery"
	"github.com/gsoultan/storm"
)

// FlushOrder ranks tables so that every table's foreign-key targets rank
// strictly lower. It is computed at generate time from the model, so no
// runtime code inspects a schema and no constraint has to be deferred for
// a graph write to succeed.
var FlushOrder = map[string]int{
	"scope_axes":         0,
	"scope_node_types":   1,
	"scope_nodes":        2,
	"scope_sync_sources": 3,
	"scope_sync_runs":    4,
}

// NewUnit stages writes across this context and flushes them in foreign-key
// order as one round trip.
func NewUnit() *runtime.Unit { return runtime.NewUnit(FlushOrder) }

// No relation plans: this context declares no link whose other end is
// also generated here.

// Raw-query scanners, registered by row type. The statements were
// PREPAREd against the model at generate time; these decode their
// results with no reflect and no `any`, exactly like a table scanner.
//
// RegisterStatement is the other half, and it is a security boundary:
// a scanner is keyed by row type, so it would answer for ANY query
// returning that type — including one assembled at run time. Only the
// statements listed here run; see storm.RegisterStatement.
func init() {
	storm.RegisterScanner(scanNodeRow)
	storm.RegisterScanner(scanAncestorRow)
	storm.RegisterScanner(scanNodeIDRow)
	storm.RegisterScanner(scanDoneRow)
	storm.RegisterScanner(scanReportRow)
	storm.RegisterScanner(scanSourceIDRow)
	storm.RegisterScanner(scanSyncRunRow)
	storm.RegisterStatement(`
INSERT INTO scope_sync_runs (source_id, dry, status, finished_at, report)
VALUES ($1, false, 'failed', now(),
        jsonb_build_object(
            'error', $2::text,
            'added', 0, 'renamed', 0, 'moved', 0, 'archived', 0,
            'unchanged', 0, 'errors', '[]'::jsonb))`)
	storm.RegisterStatement(`
INSERT INTO scope_sync_sources (tenant_id, axis_code, kind, config,
                                interval_seconds, next_run_at)
VALUES ($1, $2, $3, $4::jsonb, $5,
        CASE WHEN $5 > 0 THEN now() ELSE NULL END)
RETURNING id::text AS id`)
	storm.RegisterStatement(`
SELECT
       n.id::text AS id, n.tenant_id::text AS tenant_id,
       n.parent_id::text AS parent_id, n.is_axis_root, n.status, n.axis_code,
       n.node_type, n.slug, n.name, n.external_ref,
       (SELECT count(*) FROM scope_nodes c
         WHERE c.parent_id = n.id
           AND ($6::boolean OR c.status = 'active'))::int AS child_count
FROM scope_nodes n
WHERE n.tenant_id = $1
  AND n.axis_code = $2
  AND ($3::uuid IS NULL OR n.parent_id = $3)
  AND ($4::text IS NULL OR n.name ILIKE '%' || $4 || '%')
  AND ($6::boolean OR n.status = 'active')
  AND ($5::text IS NULL
       OR n.name > $5::text
       OR (n.name = $5::text AND n.id > $7::uuid))
ORDER BY n.name, n.id
LIMIT $8`)
	storm.RegisterStatement(`
SELECT
       n.id::text AS id, n.tenant_id::text AS tenant_id,
       n.parent_id::text AS parent_id, n.is_axis_root, n.status, n.axis_code,
       n.node_type, n.slug, n.name, n.external_ref,
       (SELECT count(*) FROM scope_nodes c
         WHERE c.parent_id = n.id AND c.status = 'active')::int AS child_count
FROM scope_nodes n
WHERE n.id = $1 AND n.tenant_id = $2`)
	storm.RegisterStatement(`
SELECT
       n.id::text AS id, n.tenant_id::text AS tenant_id,
       n.parent_id::text AS parent_id, n.is_axis_root, n.status, n.axis_code,
       n.node_type, n.slug, n.name, n.external_ref,
       (SELECT count(*) FROM scope_nodes c
         WHERE c.parent_id = n.id AND c.status = 'active')::int AS child_count
FROM scope_nodes n
WHERE n.tenant_id = $1 AND n.axis_code = $2 AND n.external_ref = $3`)
	storm.RegisterStatement(`
SELECT
       n.id::text AS id, n.tenant_id::text AS tenant_id,
       n.parent_id::text AS parent_id, n.is_axis_root, n.status, n.axis_code,
       n.node_type, n.slug, n.name, n.external_ref,
       (SELECT count(*) FROM scope_nodes c
         WHERE c.parent_id = n.id AND c.status = 'active')::int AS child_count
FROM scope_nodes n
WHERE n.tenant_id = $1 AND n.id = ANY($2::uuid[])`)
	storm.RegisterStatement(`
SELECT (scope_move_node($1, $2) IS NULL) AS done`)
	storm.RegisterStatement(`
SELECT n.id::text AS id, n.axis_code, n.node_type, n.parent_id::text AS parent_id,
       n.slug, n.name, n.external_ref, n.status, n.is_axis_root, c.depth
  FROM scope_closure c
  JOIN scope_nodes n ON n.id = c.ancestor_id
 WHERE c.descendant_id = $1 AND n.tenant_id = $2
 ORDER BY c.depth DESC`)
	storm.RegisterStatement(`
SELECT r.id::text AS id, r.source_id::text AS source_id, s.axis_code,
       r.started_at, r.finished_at, r.dry, r.status, r.report
FROM scope_sync_runs r
JOIN scope_sync_sources s ON s.id = r.source_id
WHERE s.tenant_id = $1 AND r.source_id = $2
ORDER BY r.started_at DESC
LIMIT $3`)
	storm.RegisterStatement(`
SELECT scope_add_node($1, $2, $3, $4, $5, $6, nullif($7, ''))::text AS node_id`)
	storm.RegisterStatement(`
SELECT scope_ensure_root($1, $2)::text AS node_id`)
	storm.RegisterStatement(`
SELECT scope_sync_apply($1, $2::jsonb, $3)::text AS report`)
	storm.RegisterStatement(`
UPDATE scope_axes
SET display_name = $2, default_effect = $3, status = $4,
    sort_order = $5, ui_schema = $6::jsonb
WHERE code = $1`)
	storm.RegisterStatement(`
UPDATE scope_nodes SET name = $3, status = 'active', updated_at = now()
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE scope_nodes SET status = 'archived', updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND NOT is_axis_root`)
	storm.RegisterStatement(`
UPDATE scope_sync_sources
SET config = $3::jsonb,
    status = $4,
    interval_seconds = $5,
    next_run_at = CASE
        WHEN $5 = 0 THEN NULL
        WHEN $5 <> interval_seconds OR next_run_at IS NULL THEN now()
        ELSE next_run_at
    END
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE scope_sync_sources
SET interval_seconds = $3,
    next_run_at = CASE
        WHEN $3 = 0 THEN NULL
        WHEN $3 <> interval_seconds OR next_run_at IS NULL THEN now()
        ELSE next_run_at
    END
WHERE id = $1 AND tenant_id = $2`)
	storm.RegisterStatement(`
UPDATE scope_sync_sources
SET next_run_at = CASE WHEN interval_seconds > 0
                       THEN now() + make_interval(secs => interval_seconds)
                       ELSE NULL END
WHERE id = $1`)
}

func scanNodeRow(rv [][]byte, r *scopermquery.NodeRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.TenantID = sl.Str(rv[1])
	r.ParentID = runtime.NullText(rv[2], sl)
	r.IsAxisRoot = runtime.Bool(rv[3])
	r.Status = sl.Str(rv[4])
	r.AxisCode = sl.Str(rv[5])
	r.NodeType = sl.Str(rv[6])
	r.Slug = sl.Str(rv[7])
	r.Name = sl.Str(rv[8])
	r.ExternalRef = runtime.NullText(rv[9], sl)
	r.ChildCount = runtime.Int4(rv[10])
	return nil
}

func scanAncestorRow(rv [][]byte, r *scopermquery.AncestorRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.AxisCode = sl.Str(rv[1])
	r.NodeType = sl.Str(rv[2])
	r.ParentID = runtime.NullText(rv[3], sl)
	r.Slug = sl.Str(rv[4])
	r.Name = sl.Str(rv[5])
	r.ExternalRef = runtime.NullText(rv[6], sl)
	r.Status = sl.Str(rv[7])
	r.IsAxisRoot = runtime.Bool(rv[8])
	r.Depth = runtime.Int2(rv[9])
	return nil
}

func scanNodeIDRow(rv [][]byte, r *scopermquery.NodeIDRow, sl *runtime.Slab) error {
	r.NodeID = sl.Str(rv[0])
	return nil
}

func scanDoneRow(rv [][]byte, r *scopermquery.DoneRow, sl *runtime.Slab) error {
	r.Done = runtime.Bool(rv[0])
	return nil
}

func scanReportRow(rv [][]byte, r *scopermquery.ReportRow, sl *runtime.Slab) error {
	r.Report = sl.Str(rv[0])
	return nil
}

func scanSourceIDRow(rv [][]byte, r *scopermquery.SourceIDRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	return nil
}

func scanSyncRunRow(rv [][]byte, r *scopermquery.SyncRunRow, sl *runtime.Slab) error {
	r.ID = sl.Str(rv[0])
	r.SourceID = sl.Str(rv[1])
	r.AxisCode = sl.Str(rv[2])
	r.StartedAt = runtime.Timestamptz(rv[3])
	r.FinishedAt = runtime.Nullable(rv[4], runtime.Timestamptz)
	r.Dry = runtime.Bool(rv[5])
	r.Status = sl.Str(rv[6])
	r.Report = runtime.JSON(runtime.JSONB(rv[7], sl))
	return nil
}
