// Code generated by storm v0.16.0. DO NOT EDIT.
//
// The compile-time staleness check: if a model's fields changed and this
// file was not regenerated, the package below does not build.
package rgen

import (
	m0 "github.com/gsoultan/anubis/internal/scope/adapter/postgres/rmodel"
)

// _assertScopeAxisShape fails to compile if m0.ScopeAxis gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertScopeAxisShape(m m0.ScopeAxis) {
	type shape m0.ScopeAxis
	_ = shape{
		m.CreatedAt,
		m.SortOrder,
		m.Code,
		m.DisplayName,
		m.DefaultEffect,
		m.Status,
		m.Resolution,
		m.UiSchema,
	}
}

// _assertScopeNodeShape fails to compile if m0.ScopeNode gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertScopeNodeShape(m m0.ScopeNode) {
	type shape m0.ScopeNode
	_ = shape{
		m.Model,
		m.TenantID,
		m.ParentID,
		m.IsAxisRoot,
		m.Status,
		m.AxisCode,
		m.NodeType,
		m.Slug,
		m.Name,
		m.ExternalRef,
		m.Attributes,
	}
}

// _assertScopeNodeTypeShape fails to compile if m0.ScopeNodeType gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertScopeNodeTypeShape(m m0.ScopeNodeType) {
	type shape m0.ScopeNodeType
	_ = shape{
		m.Code,
		m.AxisCode,
		m.DisplayName,
		m.ParentTypes,
	}
}

// _assertScopeSyncRunShape fails to compile if m0.ScopeSyncRun gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertScopeSyncRunShape(m m0.ScopeSyncRun) {
	type shape m0.ScopeSyncRun
	_ = shape{
		m.StartedAt,
		m.FinishedAt,
		m.ID,
		m.SourceID,
		m.Dry,
		m.Status,
		m.Report,
	}
}

// _assertScopeSyncSourceShape fails to compile if m0.ScopeSyncSource gains, loses, renames or
// reorders a field. Regenerate: `storm generate`.
func _assertScopeSyncSourceShape(m m0.ScopeSyncSource) {
	type shape m0.ScopeSyncSource
	_ = shape{
		m.CreatedAt,
		m.LastRunAt,
		m.ID,
		m.TenantID,
		m.AxisCode,
		m.Kind,
		m.Status,
		m.Config,
		m.NextRunAt,
		m.IntervalSeconds,
	}
}
